### ISSUE TITLE
Transparent window by default has 20% opacity

### ISSUE THREAD

**Issue by Sonic803** [doomemacs/doomemacs#6373] opened 2022-05-05 21:40 UTC
### What did you expect to happen?

When I open Doom Emacs it should not be transparent.

### What actually happened?

When starting emacs it has 20% opacity `picom-trans -s -g`.

### Describe your attempts to resolve the issue

Adding `(add-to-list 'default-frame-alist '(alpha 100 100))` to custom.el solves the problem for the first window.
But when i do M-x lsp-start-plain the window that opens has opacity at 20%.
Modifying frame-alpha-lower-limit doesn't help

### Steps to reproduce

Open Emacs

picom 9.1-3

### System Information

https://pastebin.com/RNEkFBa0

**Comment by hlissner** [comment] 2022-05-05 21:48
Since Doom doesn't tamper with default frame alpha _at all_, I can confidently say this isn't caused by Doom, so I will close it, but feel free to follow up here. 

That said, I can't imagine how this would happen without user input, and there isn't enough information here to investigate further. I suggest scouring your private config (or `~/.doom.d/custom.el`), because the problem likely lies there or in your default picom settings.

**Closed by hlissner** 2022-05-05 21:48 UTC
Labels: invalid
