### ISSUE TITLE
Icons not loading correctly on doom start page, dired, modeline. Fonts are installed properly.

### ISSUE THREAD

**Issue by hrqmonteiro** [doomemacs/doomemacs#7379] opened 2023-08-28 12:13 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

The fonts to load properly

### Current behavior

Icons are not loading

![Screenshot_20230828_091247](https://github.com/doomemacs/doomemacs/assets/17055027/ba71914f-8422-4a74-8202-e3989f353d6a)
![Screenshot_20230828_091258](https://github.com/doomemacs/doomemacs/assets/17055027/da5b987e-bff7-4588-a00f-b04b7fb1583c)

### Steps to reproduce

Just opening emacs. 

### System Information

https://pastebin.com/baRapLAR

**Comment by Tabascl** [comment] 2023-08-29 06:38
I'm also experiencing that problem after a fresh install of Arch Linux and Doom:

![Screenshot_20230829_083821](https://github.com/doomemacs/doomemacs/assets/15350550/5fb13715-da6f-4faf-8066-e9f00d0cedd3)

**Comment by EmptyCupCoffee** [comment] 2023-08-29 09:37
> I'm also experiencing that problem after a fresh install of Arch Linux and Doom:
> 
> ![Screenshot_20230829_083821](https://user-images.githubusercontent.com/15350550/263923223-5fb13715-da6f-4faf-8066-e9f00d0cedd3.png)
> 
> Fonts are installed properly. Some icons do show up, but others are missing.

Have you tried `M-x nerd-icons-install-fonts`  ?

**Comment by Tabascl** [comment] 2023-08-29 19:01
@EmptyCupCoffee that actually did it, thank you!
Is this something that should maybe come with a Doom installation? Or are these fonts usually included in distros? I should start keeping a list of fonts that need to be installed after setting up a new system...

**Comment by hrqmonteiro** [comment] 2023-08-29 21:14
> > I'm also experiencing that problem after a fresh install of Arch Linux and Doom:
> > ![Screenshot_20230829_083821](https://user-images.githubusercontent.com/15350550/263923223-5fb13715-da6f-4faf-8066-e9f00d0cedd3.png)
> > Fonts are installed properly. Some icons do show up, but others are missing.
> 
> Have you tried `M-x nerd-icons-install-fonts` ?

Tried that. Tried M-x all-the-icons-install-fonts` and still doesn't work.

Actually all of the fonts are installed in my system:

![image](https://github.com/doomemacs/doomemacs/assets/17055027/b0b6040d-f743-4ba3-a97f-d1a608a73a13)

They just don't show properly.

**Comment by adamransome** [comment] 2023-08-30 08:36
Same issue here on Fedora 38. Missing fonts like others have shown and after running `M-x nerd-icons-install-fonts` all I see now is an `X` where the icon should be.

**Comment by hrqmonteiro** [comment] 2023-08-30 11:48
> I had a similar problem and had to run `M-x all-the-icons-install-fonts` and `M-x nerd-icons-install-fonts`. The only way to get the missing icons fixed.

Those two commands are not solving here, unfortunately.

**Comment by hrqmonteiro** [comment] 2023-08-30 18:48
Are there no solution to this?

I literally reinstalled Arch on a new machine, installed vanilla emacs and doom (without my config) and this still won't work.

What is happening?

**Comment by dbrw** [comment] 2023-08-31 01:52
> I had a similar problem and had to run `M-x all-the-icons-install-fonts` and `M-x nerd-icons-install-fonts`. The only way to get the missing icons fixed.

This command solve the problem for me, looks like the modeline package using nerd icons font instead of all-the-icon font. Was bitten with this error a week ago in Arch, but today solved.

**Comment by sdmoralesma** [comment] 2023-08-31 07:37
Link to issue related --there is a way to get it solved there too--: https://github.com/doomemacs/doomemacs/issues/7368

**Comment by hlissner** [comment] 2023-09-15 19:42
Doom has been gradually transitioning away from all-the-icons to nerd-icons (#7411), so you will need to install the latter with `M-x nerd-icons-install-fonts` (this is documented in docs/getting_started.org and in the output of `doom install`. `doom doctor` will also tell you this if your fonts are missing). Windows users: `M-x nerd-icons-install-fonts` will only downloads the fonts for you; you must then install manually afterwards.

If it's still not working, it's likely that they did not install correctly. You can also install the fonts through your OS package manager, directly from [the nerd-icons.el repo](https://github.com/rainstormstudio/nerd-icons.el/tree/main/fonts), or the "Symbols Nerd Font" from https://www.nerdfonts.com/font-downloads.

If that *still* fails, make sure Emacs is built with FREETYPE support (you can see it in the `features` column of your `M-x doom/info`).

As this is a local config issue I will close this, but feel free to follow up here.

**Closed by hlissner** 2023-09-15 19:42 UTC
Labels: invalid

**Comment by Katalizatori** [comment] 2023-12-29 21:20
I'm on windows and had the same issue. Installing the font in user folder didn't work, for some reason, so I just put it in desktop. After that drag and drop it to your fonts file, and it was good to go.

**Comment by SamuelBanya** [comment] 2024-09-27 19:56
Using this in my Emacs config fixed this since I'm just using Doom Modeline, as well as LSP config stuff, works for my literate Emacs configuration file, 'config.org':
```
(use-package all-the-icons
  :ensure t
  :init
  ;; Install all-the-icons fonts if they are not already installed
  (unless (member "all-the-icons" (font-family-list))
    (all-the-icons-install-fonts t)))
```

**Comment by hlissner** [comment] 2024-09-27 20:03
@SamuelBanya Please don't suggest to folks they install `all-the-icons`. Both Doom and `doom-modeline` [swapped out all-the-icons for nerd-icons a long time ago](https://github.com/doomemacs/doomemacs/issues/7379#issuecomment-1721756617). If you have to install `all-the-icons` to get icons, the issue is more likely to be a private config issue.

**Comment by girdevstack** [comment] 2025-01-01 00:47
I'm new to using emacs, and doom emacs. I've just newly installed both on a rhel box. The icons don't work and I don't know what else to try. I've installed them, I've restarted, reinstalled, set the permissions of the NFM.ttf in `~/.local/share/fonts` and have seemingly chased around a sea of different issues and PRs about this topic. Is everything this hard with emacs and doom?

**Comment by avbanks** [comment] 2026-08-28 21:11
One thing to note, if you're using Emacs in the terminal you'll need to set your terminal font to a Nerd Font.
