### ISSUE TITLE
+emacs and +emacs-bindings are not loaded in non-evil mode even after disabling evil module

### ISSUE THREAD

**Issue by copyninja** [doomemacs/doomemacs#6835] opened 2022-09-23 11:37 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When using doom in non-evil mode all keybindings should be available with `C-c` and `C-c l`. Current master with this mode `C-c p` points to `persp mode` where as if `+emacs-bindings` is loaded it should be `projectile mode`.  

### Current behavior

None of the keybindings are available in non-evil mode.

### Steps to reproduce

Launch doomemacs with current master of doomemacs repository. I did a git-bisect and found following

```
c5188c43883f73183ca0f4cb6597c75104722b63 is the first bad commit
commit c5188c43883f73183ca0f4cb6597c75104722b63
Author: Henrik Lissner <git@henrik.io>
Date:   Mon Sep 12 23:44:04 2022 +0200

    perf: cache module flags in symbol plists

    For small amounts of data, symbol plists are the most efficient (space
    and time wise) as data access gets in Emacs. Hash tables, though O(1),
    impose a minimum threshold of overhead before it becomes the efficient
    option, but this benefit won't be obvious for datasets of at least 60 or
    less.

    Since modulep! is used *a lot*, and used to determine a module's
    state (and state of its flags), there is a benefit to caching it.
    Still, this is only a read-only cache, and does not replace the
    `doom-modules` hash-table, which will always be the preferred interface
    for the rest of the module API.

 lisp/cli/autoloads.el |  6 ++++++
 lisp/doom-modules.el  | 18 +++++++++++-------
 2 files changed, 17 insertions(+), 7 deletions(-)
```
Also I've tested it with emacs28 as well its breaking in it also. Reporting it as suggested in discord channel by @Gulpy in discord channel

### System Information

https://gist.github.com/copyninja/ae6ac24842862af8f127da3f5162de66

**Comment by hlissner** [comment] 2022-09-24 20:16
I've since pushed a number of changes to the startup process (and how modules are processed/loaded). Could you try updating Doom to see if it resolves this issue?

**Comment by copyninja** [comment] 2022-09-25 09:21
@hlissner I have latest master and still see this issue.
```
* 731764ae (HEAD -> master, origin/master, origin/HEAD) fix(cli): doom install: wrong-number-of-args error
```

**Comment by theSuess** [comment] 2022-09-26 15:58
I might have the same issue, but in evil-mode. Almost no Key-Bindings are present. As an example, `SPC-TAB` and `SPC-P` are unbound but are bound in `evil-bindings.el`.

**Comment by copyninja** [comment] 2022-09-27 03:36
@hlissner it looks like now keybindings are working in non-evil mode. I'm using `3f16c828` from doomemacs repo as master and emacs upstream master branch with commit hash `94380420e2` and things are working just fine. Not sure when the issue got fixed though

**Comment by hlissner** [comment] 2022-10-02 17:19
That is odd. I recommend updating once more, because https://github.com/doomemacs/doomemacs/commit/285b460c80e455fabaf036f0eb48575637586a46 finally put to rest an insidious bug that messed up module load order and caused a few issues like these.

I'll assume that this is a duplicate of https://github.com/doomemacs/doomemacs/issues/6813, in any case, and that it has been resolved. Let me know if it resurfaces and I'll reopen it. Thanks for bringing it to my attention!

**Closed by hlissner** 2022-10-02 17:19 UTC
Labels: duplicate
