### ISSUE TITLE
doom upgrade fails: 'unambigious name for "main"' when it gets to "vertico" repo

### ISSUE THREAD

**Issue by sandoichi** [doomemacs/doomemacs#6388] opened 2022-05-11 17:39 UTC
### What did you expect to happen?

when I run `doom upgrade` on a clean master branch, it should be able to complete successfully

### What actually happened?

```
$ doom upgrade
> Executing 'doom upgrade' with Emacs 28.1 at 2022-05-11 13:35:50
  > Preparing to upgrade Doom Emacs and its packages...
  ✓ Doom is already up-to-date!
  Doom is up-to-date!
  > Synchronizing your config with Doom Emacs...
    > Installing packages...
      - No packages need to be installed
    > (Re)building packages...
      - No packages need rebuilding
    > Updating recipe repos...
    > Updating packages (this may take a while)...
      > In repository "vertico", failed to get status:
      
        Failed to get unambiguous name for "main"
        fatal: Needed a single revision

           1) Abort
```

### Steps to reproduce

1. pull latest `master` branch
2. run `doom upgrade`

### System Information

https://pastebin.com/uh3V3cvW

**Comment by sandoichi** [comment] 2022-05-11 17:50
after commenting out `vertico` in my `init.el`, I hit the same issue on other package repos:
``` 
 > In repository "org", failed to get status:
      
        Failed to get unambiguous name for "main"
        fatal: Needed a single revision

```
```
 > In repository "emacs-python-pytest", failed to get status:
      
        Failed to get unambiguous name for "main"
        fatal: Needed a single revision
```

**Comment by hlissner** [comment] 2022-05-11 18:04
Duplicate of #4984

**Closed by hlissner** 2022-05-11 18:04 UTC
Labels: duplicate
