### ISSUE TITLE
~/.emacs.d/bin/doom install error

### ISSUE THREAD

**Issue by zhaojio** [doomemacs/doomemacs#6487] opened 2022-06-21 13:50 UTC
### What did you expect to happen?

~/.emacs.d/bin/doom install

### What actually happened?

 > Building fd-dired...
  > Cloning emacs-undo-fu...
  x There was an unexpected runtime error
    Message: Wrong type argument
    Details: (arrayp nil)
    Backtrace:
      (substring nil 0 0)
      (replace-regexp-in-string "[^-0-9a-zA-Z_./\n]" "\\\\\\&" nil)
      (shell-quote-argument nil)
      (mapconcat shell-quote-argument ("git" "branch" "-m" nil) " ")
      (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name di...
      (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-...
      (concat (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument ...
      (let* ((inhibit-read-only t) (entry (concat (propertize (format "$ cd ...
      (let* ((result result) (exit (car result)) (invoked (numberp exit)) (s...
      (let ((directory x59) (result x57) (args x55) (program x53)) (let* ((r...
      (let* ((x53 (car entry)) (x54 (cdr entry)) (x55 (car x54)) (x56 (cdr x...
      (save-current-buffer (set-buffer (straight--process-buffer)) (goto-cha...
    ! Wrote extended backtrace to ~/.emacs.d/.local/logs/cli.doom.220621213356.60668.error
  ✓ Finished in 10m 16s

### Steps to reproduce

~/.emacs.d/bin/doom install

### System Information

macos

**Comment by hlissner** [comment] 2022-06-21 13:51
Duplicate of https://github.com/doomemacs/doomemacs/issues/5207.

See https://github.com/doomemacs/doomemacs/issues/5207#issuecomment-1159040527.

**Closed by hlissner** 2022-06-21 13:51 UTC
Labels: duplicate
