### ISSUE TITLE
clangd not starting in cuda-mode

### ISSUE THREAD

**Issue by ethercflow** [doomemacs/doomemacs#7993] opened 2024-08-13 00:50 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When open a `*.cu` or `.cuh`, clangd will start up.

### Current behavior

When open a `*.cu` or `.cuh`, no clangd, no line number.

### Steps to reproduce

1. Open emacs
2. Open a `.cu` or `.cuh` file

### System Information

https://pastebin.com/t7pBbJzq

**Comment by hlissner** [comment] 2024-08-13 01:12
I can't reproduce this.

![image](https://github.com/user-attachments/assets/0ab0acc2-2a25-4db4-8e78-9b70c8edc87f)

I don't have the LSP client installed, but LSP is initializing fine in a *.cu file.

Please [check the \*Messages\* buffer](https://discourse.doomemacs.org/t/how-to-debug-issues/55#the-messages-buffer-1) for any errors or warnings.

**Comment by ethercflow** [comment] 2024-08-13 03:10
Hi @hlissner , below is my `*Messages*` buffer and `*.cu`, seems no any errors or warnings. (I also tried with `emacs --debug-init`, still no any errors or warnings)

<img width="1437" alt="image" src="https://github.com/user-attachments/assets/9c3dc6c5-12cf-4c89-b6b8-df299ba354fe">

**Comment by ethercflow** [comment] 2024-08-13 03:14
And after  run `M-x c++-mode`, it will start clangd:

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/205b929b-db4a-4e19-888c-e18c26490ff7">

**Comment by hlissner** [comment] 2024-08-13 03:19
Ooh, I see. You're using eglot. There's no entry for `cuda-mode` in `eglot-server-programs`, so one will need to be added. See if this fixes it for you:

```elisp
;;; add to $DOOMDIR/config.el
(after! cuda-mode
  (set-eglot-client! 'cuda-mode '("clangd")))
```

**Comment by ethercflow** [comment] 2024-08-13 03:34
> Ooh, I see. You're using eglot. There's no entry for `cuda-mode` in `eglot-server-programs`, so one will need to be added. See if this fixes it for you:
> 
> ```emacs-lisp
> ;;; add to $DOOMDIR/config.el
> (after! cuda-mode
>   (set-eglot-client! 'cuda-mode '("clangd")))
> ```

@hlissner  It works! BTW, it seems still no line number, need other config?

**Comment by hlissner** [comment] 2024-08-13 03:50
> no line number

Oh, that's because `cuda-mode` isn't a proper major mode (waiting for https://github.com/chachi/cuda-mode/pull/11 to be merged), so [these lines](https://github.com/doomemacs/doomemacs/blob/master/lisp/doom-ui.el#L485-L486) won't work for it. You'll have to add this to your config for the time being:

```elisp
;;; add to $DOOMDIR/config.el
(add-hook 'cuda-mode-hook #'display-line-numbers-mode)
```

**Comment by hlissner** [comment] 2024-08-14 01:44
As of 84f7eb2, clangd is now associated with cuda-mode for Eglot users. Thanks for bringing it to my attention!

**Closed** 2024-08-14 01:43 UTC
Labels: is:feature, module:tools/lsp, module:lang/cc, re:eglot

**Comment by gpanago** [comment] 2024-08-14 02:59
The commit https://github.com/chachi/cuda-mode/commit/49df093d42ca0f9ec148597709a1fe7009d4528a makes cuda-mode derive from c++-mode, so I believe it should fix the line number problem. Perhaps bump @hlissner?
