### ISSUE TITLE
Error: (wrong-type-argument json-value-p t) when doom doctor

### ISSUE THREAD

**Issue by lcongdanh** [doomemacs/doomemacs#6426] opened 2022-05-29 11:36 UTC
### What did you expect to happen?

When I run doom doctor, it should not have any errors

### What actually happened?

When I run doom doctor, the error `Error: (wrong-type-argument json-value-p t)` happens. Here the backtrace

```
      Message: Wrong type argument
      Error: (wrong-type-argument json-value-p t)
      Backtrace:
        (json-serialize t)
        (condition-case nil (json-serialize t) (:success t) (json-unavailable nil)...
        (not (condition-case nil (json-serialize t) (:success t) (json-unavailable...
        (and (not (condition-case nil (json-serialize t) (:success t) (json-unavai...
        (if (and (not (condition-case nil (json-serialize t) (:success t) (json-un...
        (eval-buffer #<buffer  *load*-254902> nil "/home/danh/.emacs.d/.local/stra...
        (load-with-code-conversion "/home/danh/.emacs.d/.local/straight/build-27.1...
        (#<subr require> compat)
        (apply #<subr require> compat)
        (progn (fset #'write-region vnew) (apply fn args))
    ! Extended backtrace logged to .emacs.d/.local/doom.error.log`
```

### Describe your attempts to resolve the issue

I did run doom upgrade and doom sync, and even reinstall doom but nothing helps

### Steps to reproduce

open terminal -> doom doctor

### System Information

https://pastebin.com/RmaZu2XM

**Comment by Syphixs** [comment] 2022-05-29 11:57
#6425 related

**Comment by WonderBeat** [comment] 2022-05-29 14:47
Can be reproduced in 27.1
Workaround - switch to 28.1

**Comment by hlissner** [comment] 2022-05-29 22:40
Duplicate of #6425

**Closed by hlissner** 2022-05-29 22:40 UTC
Labels: duplicate
