### ISSUE TITLE
failed to load doom fro early-init.el after renaming the DOOMDIR

### ISSUE THREAD

**Issue by honghuzi** [doomemacs/doomemacs#6781] opened 2022-09-15 04:27 UTC
### What did you expect to happen?

I am trying managing my configurations with the chemacs2 package on Windows. According to [the doc](https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#install-doom-alongside-other-configs-with-chemacs2), 

### What actually happened?

I renamed the configuration folder from _.emacs.d_ to _doom-emacs_, then I typed in the cmd
```cmd
.\doom-emacs\bin\doom sync
```
and get the error
```cmd
Error: Failed to load Doom from ~/doom-emacs/early-init.el
```

### Describe your attempts to resolve the issue

- I tried resetting the _$HOME_ environment variable as c:/Users/username, but still same error
- tried with git bash terminal and powershell, but still got same error
- the develop branch works fine, but i don't want to use it. It seems to die.

### Steps to reproduce

1. git clone the doom project to ~/doom-emacs
2. run `~/doom-emacs/bin/doom sync`

### System Information

https://pastebin.com/QhiiW7Ni

**Comment by ricma** [comment] 2022-09-15 11:15
FWIW, I have the same issue.

A `git bisect run` with an initial _good_ commit at, e.g. 08071f92b7c2359c4759901c63cb52ccdfd636d4 (I did a random pick), and using `bin/doom info || false` in a shell script for `git bisect run` revealed that `doom info` does not work since c05e61536ed9faaef5fe6f7f4351ffb3ab15cc87.

**Comment by podung** [comment] 2022-09-15 20:57
#6777 seems to be the same issue

**Comment by hlissner** [comment] 2022-09-16 14:34
Duplicate of #6777.

Please move this discussion there.

**Closed by hlissner** 2022-09-16 14:34 UTC
Labels: duplicate
