### ISSUE TITLE
Editing files with `sudo` doesn't work under `nushell`

### ISSUE THREAD

**Issue by upbqdn** [doomemacs/doomemacs#7945] opened 2024-07-14 14:15 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

1. Install Doom in nushell.
2. `SPC-f-u`, then select a write-protected file, for example `etc/hosts`.
4. Enter the `sudo` password.
5. Edit the file.

### Current behavior

1. Install Doom in nushell.
2. `SPC-f-u`, then select a write-protected file, for example `etc/hosts`.
4. Enter the `sudo` password.
5. Get:

```
Password:
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #1:1:1]
 1 │ \/bin\/sh -i
   · ────┬────
   ·     ╰── Command `\/bin\/sh` not found
   ╰────
  help: `\/bin\/sh` is neither a Nushell built-in or a known external command
```

### Steps to reproduce

Same as above. Running `doom sync` from nushell is sufficient to get the error instead of installing Doom from scratch in nushell.

### System Information

https://pastebin.com/EjLM726j

**Comment by upbqdn** [comment] 2024-07-14 14:20
I'm guessing this is just due to escaping the slashes in the `/bin/sh` command since `\/bin\/sh` works in bash but returns the same error as above in nushell.

**Comment by upbqdn** [comment] 2024-07-14 14:23
The current workaround I use is to call `doom sync` from bash so that `SHELL` is set to `bash` in the ENV file and so that Doom sticks to `bash`.

**Comment by hlissner** [comment] 2024-07-14 18:32
A lot of Emacs facilities assume a POSIX-compliant shell; TRAMP (which powers Emacs' "remote editing" functionality) is one of these facilities. Users of the Fish shell have similar issues.

I recommend one of two workarounds:

1. Set `shell-file-name` to the path of a POSIX shell, like bash:

```elisp
;; This will ensure all internal processes use bash, rather 
;; than /bin/nu, which is what yours is set to by default, 
;; thanks to $SHELL.
(setq shell-file-name "/bin/bash")
```

2. OR change the shell TRAMP uses:

```elisp
;; This might fix the issue as far as tramp is concerned, but
;; you are likely to run into issues somewhere else, with
;; something else that expects a POSIX shell:
(setq tramp-encoding-shell "bash")
```

In any case, I'll close this issue since this is not a bug with Doom, but feel free to follow up here.

**Closed by hlissner** 2024-07-14 18:32 UTC
Labels: invalid
