### ISSUE TITLE
Disable auto-save and auto-eval of config.el

### ISSUE THREAD

**Issue by tigger04** [doomemacs/doomemacs#7679] opened 2024-02-16 15:52 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I have returned to the doom fold, after I lost my mind a few years ago and spent 100s of hours hand cranking my own setup, which is just getting harder for me to justify the effort in maintaining for myself.

I am particularly loving the performance and responsiveness of Doom, and how much is there with sensible defaults right ootb.

I'm trying hard to keep the config simple. However one thing that has me stumped.

I like to run emacs in the background using launchd, I had achieved this perviously with a little trick of the following in my init:

```
(if (eq system-type 'darwin)
    (shell-command "osascript -e 'tell application \"System Events\" to set visible of process \"Emacs\" to false'")
  )
```

However, putting this in to my new doom `config.el`, I notice this executes every time I make a change in the config.el anywhere, even just to tidy up whitespace.

My cursory research indicates that autosave should be off by default, so I'm confused as to why it's happening mid-edits.

But aside from that, is there some variable or flag I could rely on to restrict this block to only run when config.el is being invoked on launch, as opposed to auto-running on a config change mid-session?

I tried ...

```
(if (and
     (eq system-type 'darwin)
     (not (boundp 'tigger.dev/config-loaded)))
    (shell-command "osascript -e 'tell application \"System Events\" to set visible of process \"Emacs\" to false'")
  )

(setq tigger.dev/config-loaded t)
```

but it still executes on config change mid-session (it even runs when just loading config.el in to the buffer!)

Also tried wrapping it in a function and adding to doom-after-modules-init hook but no joy.

I apologise for posting this in the issues, I posted this to the Discord a week ago and got no bites, i've been rummaging around the documentation ... and ... it seems like every keystroke I hit in the config.el buffer causes the window to vanish. It's driving me BANANAS!

Any help would be most graciously appreciated 🙏 

### Current behavior

`config.el` evaluates on every keystroke when i'm in insert mode

### Steps to reproduce

1. Open `config.el` in Doom Emacs buffer
2. Hit `i` for insert mode, add a space
3. `config.el` evaluates, and in my case, the window vanishes

### System Information

```
generated  Feb 16, 2024 15:50:53 system     MacOS 14.1.1 Darwin 23.1.0 arm64 emacs      30.0.50 ~/.emacs.d/ doom       3.0.0-pre PROFILE=_@0 grafted, HEAD -> master, origin/master, 	   origin/HEAD d38787e 2024-02-02 18:50:31 -0500 ~/.config/doom/ shell      /opt/homebrew/bin/bash features   ACL GIF GLIB GMP GNUTLS JPEG JSON LCMS2 LIBXML2 MODULES 	   NOTIFY KQUEUE NS PDUMPER PNG RSVG SQLITE3 THREADS TIFF 	   TOOLKIT_SCROLL_BARS TREE_SITTER WEBP XIM ZLIB traits     batch server-running envvar-file modules    :config use-package :completion company vertico :ui doom 	   doom-dashboard (emoji +unicode) hl-todo modeline ophints 	   (popup +defaults) (vc-gutter +pretty) vi-tilde-fringe 	   workspaces :editor (evil +everywhere) file-templates fold 	   snippets (format +onsave) :emacs dired electric undo vc 	   :checkers syntax :tools (eval +overlay) lookup magit :os 	   macos :lang emacs-lisp markdown org plantuml python sh 	   :config (default +bindings +smartparens)
```

**Comment by hlissner** [comment] 2024-02-16 20:13
The only thing that comes to mind is the syntax checker, which does not *evaluate* the file, but instead compiles it (in order to consume the errors/warnings it produces to feed back to the user). However, compilation doesn't *evaluate* code either, *unless* that code is in an `(eval-when-compile ...)` block. There's no reason to put arbitrary code in one without a very good reason, so unless that's the case for you somehow, there is no other way I can conceive that would cause elisp getting arbitrarily evaluated (and it has nothing to do with auto-saving, as far as I'm aware). In any case, I can't produce it.

Is your private config up anywhere I can see it?

**Comment by tigger04** [comment] 2024-02-17 00:28
Certainly, it's up [here](github.com/tigger04/doom.tigger.dev) - fairly minimal config from the ootb one so far

**Comment by tigger04** [comment] 2024-02-17 08:53
modified init.el (excerpt) - weirdly I had (format +onsave) in there twice 🤦‍♀️ 

```
       :editor
       ;;(format +onsave)
       (evil +everywhere); come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       ;;(format +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
```

```
🟢~/.doom.d$
❯ doom sync
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.emacs.d/.local/env
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Purging orphaned packages (for the emperor)...
    - Skipping builds
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
  > (Re)building profile in /Users/tigger/.emacs.d/.local/etc/@/...
    > Deleting old init files...
    > Generating 4 init files...
    > Byte-compiling ~/.emacs.d/.local/etc/@init.30.el...
    ✓ Built init.30.elc
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
🟢~/.doom.d$
❯
```

sadly, strange, same behaviour.

Don't suppose you were able to reproduce it? Sorry if that sounds presumptuous, i'm sure you have 10000 better things to do with your time, appreciate your help :)

**Comment by hlissner** [comment] 2024-03-27 02:48
I think I've finally zeroed in on the cause. It is, in fact, the syntax checker. It loads Doom (and your config) before it compiles an elisp file in your Doom config to check for errors. This technically isn't a bug, since the state it derives from loading your config is important to testing for errors, but it will definitely cause issues if you're doing things with expensive/risky side-effects at top-level in your config. 

The simple workaround is to move that `shell-command` call to a hook. E.g.

```elisp
;;; in $DOOMDIR/config.el
(when (eq system-type 'darwin)
  (add-hook! 'emacs-startup-hook 
    (shell-command "osascript -e 'tell application \"System Events\" to set visible of process \"Emacs\" to false'")))
```

This way, it only runs once, at startup, no matter how many times your config is reread by the syntax checker. In any case, I'll close this as a config issue. Thanks for bringing it to my attention, in any case!

**Closed by hlissner** 2024-03-27 02:48 UTC
Labels: invalid

**Comment by tigger04** [comment] 2024-03-29 02:38
huh, so that seems to have done it.

I never would have figured that out in a million years. thanks so much!

is that flycheck running the shell-command? I wonder would it be worth raising an issue on their github page. Seems the unintentional execution of a shelll script during syntax checking has the potential to wreak havoc - what are your thoughts?
