### ISSUE TITLE
Customized maps (keyboard overrides) not working

### ISSUE THREAD

**Issue by agzam** [doomemacs/doomemacs#6816] opened 2022-09-19 16:22 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [ ] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

`:config default` keybindings don't get replaced with customized ones, as they used to.

#### Example: 

In my private modules, if I  have something like:

```
(map! :leader "fed" #'myfunction)
```

I'd expect it to override Doom's default `SPC fe` binding, but that no longer works.

It seems this particular commit is breaking it: 3a0f1aa3ef6623ee65765b7fa68e5aded2c518e4

### System Information

https://pastebin.com/vj5YqR4D

**Comment by agzam** [comment] 2022-09-19 16:34
Possibly related to: https://github.com/doomemacs/doomemacs/issues/6813

**Comment by hlissner** [comment] 2022-09-19 16:35
Duplicate of https://github.com/doomemacs/doomemacs/issues/6813.

**Closed by hlissner** 2022-09-19 16:35 UTC
Labels: duplicate
