### ISSUE TITLE
Cloning corfu-terminal...acsmirror-mirror.. Package was not properly cloned due to a connection failure, please try again later

### ISSUE THREAD

**Issue by tsoernes** [doomemacs/doomemacs#8109] opened 2024-10-08 09:54 UTC
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

`doom sync -u` should finish without error

### Current behavior

```
$ cd ~/.config/emacs        &&    git pull && doom sync -u 

remote: Enumerating objects: 150, done.
remote: Counting objects: 100% (150/150), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 105 (delta 86), reused 63 (delta 45), pack-reused 0 (from 0)
Receiving objects: 100% (105/105), 17.99 KiB | 2.25 MiB/s, done.
Resolving deltas: 100% (86/86), completed with 45 local objects.
From https://github.com/doomemacs/doomemacs
   cf7098528..8b9168de6  master     -> origin/master
Updating c8a5e6ec1..8b9168de6
Fast-forward
 bin/doom.sh                               |   6 ++++++
 lisp/cli/doctor.el                        | 122 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------
 lisp/doom.el                              |   2 +-
 lisp/lib/buffers.el                       |   3 +++
 lisp/lib/config.el                        |  21 ++++++++++++++++-----
 lisp/lib/docs.el                          |   1 +
 lisp/lib/fonts.el                         |   3 +++
 lisp/lib/help.el                          |   3 +++
 lisp/lib/packages.el                      |   3 +++
 lisp/lib/projects.el                      |   3 +++
 lisp/lib/sandbox.el                       |   3 +++
 lisp/lib/scratch.el                       |   3 +++
 lisp/lib/sessions.el                      |   3 +++
 lisp/lib/store.el                         |   3 +++
 lisp/lib/strings.el                       |   3 ++-
 lisp/lib/text.el                          |   3 +++
 lisp/lib/themes.el                        |   3 +++
 lisp/lib/ui.el                            |   3 +++
 lisp/packages.el                          |   2 +-
 modules/config/default/autoload/search.el |   2 +-
 modules/email/mu4e/config.el              |   4 ++--
 modules/email/wanderlust/packages.el      |   2 +-
 modules/lang/cc/README.org                |  32 ++++++++++++++++----------------
 modules/lang/clojure/config.el            |   7 ++++---
 modules/lang/python/config.el             |   4 ++--
 modules/lang/ruby/config.el               |   4 ++--
 modules/ui/doom/packages.el               |   2 +-
 27 files changed, 173 insertions(+), 77 deletions(-)
 create mode 100755 bin/doom.sh
- Using Emacs 31.0.50 @ /usr/local/bin/emacs
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.config/emacs/.local/env
  > Ensuring packages are installed and built...
    > Updating recipe repos...
    > Cloning corfu-terminal...acsmirror-mirror...
    x There was an unexpected runtime error
      Message: Package was not properly cloned due to a connection failure, please try again later
      Backtrace:
        (error "Package was not properly cloned due to a connection failure, please try again later")
        (if (car args) nil (error "Package was not properly cloned due to a connection failure, please try again later"))
        (progn (if (car args) nil (error "Package was not properly cloned due to a connection failure, please try again later")) (apply shell-quote-argument args))
        (shell-quote-argument nil)
        (mapconcat shell-quote-argument ("git" "branch" "-m" nil) " ")
        (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name directory)) (mapconcat #'shell-quote-argument (cons program args) " "))
        (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name directory)) (mapconcat #'shell-quote-argument (cons program args) " ")) 'face 'straight-process-command)
        (concat (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name directory)) (mapconcat #'shell-quote-argument (cons program args) " ")) 'face 'straight-process-command) (if (eq (car result) 'file-...
        (let* ((inhibit-read-only t) (entry (concat (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name directory)) (mapconcat #'shell-quote-argument (cons program args) " ")) 'face 'straight-process-...
        (let* ((result result) (exit (car result)) (invoked (numberp exit)) (success (and invoked (= 0 exit))) (failure (not success)) (stdout (nth 1 result)) (stderr (nth 2 result))) (ignore result exit invoked success failure ...
        (let ((program x56) (args x58) (result x60) (directory x62)) (let* ((result result) (exit (car result)) (invoked (numberp exit)) (success (and invoked (= 0 exit))) (failure (not success)) (stdout (nth 1 result)) (stderr ...
        (progn (ignore (null x63)) (let ((program x56) (args x58) (result x60) (directory x62)) (let* ((result result) (exit (car result)) (invoked (numberp exit)) (success (and invoked (= 0 exit))) (failure (not success)) (stdo...
GNU Emacs     v31.0.50         652a8a0838b38a6eab85c55fc61cedd1c61ef20f
Doom core     v3.0.0-pre       HEAD -> master, origin/master, origin/HEAD 8b9168de6 2024-10-03 02:26:28 -0400
Doom modules  v24.11.0-pre     HEAD -> master, origin/master, origin/HEAD 8b9168de6 2024-10-03 02:26:28 -0400
      ! Wrote extended backtrace to ~/.config/emacs/.local/state/logs/cli.doom.241008114911.23881.error
```
[cli.doom.241008114911.23881.log](https://github.com/user-attachments/files/17291439/cli.doom.241008114911.23881.log)

### Steps to reproduce

`cd ~/.config/emacs        &&    git pull && doom sync -u `

### System Information

https://gist.github.com/tsoernes/a3410e37bf3331c69677616559fbef72

**Comment by hlissner** [comment] 2024-10-08 22:43
As the error says, this is a connection error, and nothing Doom can do anything about. The package clones fine on my local and remote (US and EU-based) test machines, so I suspect codeberg was simply down.

If it still doesn't work, I suggest trying to delete the local repo manually before resyncing:

```sh
$ rm -rf ~/.config/emacs/.local/straight/repos/corfu-terminal
$ doom sync
```

In any case, since this isn't a Doom bug (and I'm currently working on replacing Straight with [Elpaca](https://github.com/progfolio/elpaca), so Doom's package manager is in maintenance mode), I'll close this issue, but feel free to follow up here.

**Closed by hlissner** 2024-10-08 22:43 UTC
Labels: invalid

**Comment by whompyjaw** [comment] 2025-01-27 23:16
In case anyone comes across this, the issue is that `corfu-terminal` doesn't exist in an accessible mirror or MELPA. For whatever reason, my work blocks `codeberg` and so I can never download any packages from there. So then I have to point the package to the specific mirror that has this package. For example, `doom sync` defaults to visual-fill-column from codeberg and can't find it in emacsmirror (idk why), so I need to tell it to install it from there specifically:
```elisp
 (package! visual-fill-column
       :recipe (:host github :repo "emacsmirror/visual-fill-column"))
```
But again, corfu-terminal hasn't made it to `MELPA` or a mirror, so we can't download it. I am trying to figure out how to ignore a package from getting downloaded, atm.
