### ISSUE TITLE
bin/doom: Lisp error

### ISSUE THREAD

**Issue by nicdob** [doomemacs/doomemacs#6800] opened 2022-09-17 17:39 UTC
### What did you expect to happen?

Running any bin/doom command.

### What actually happened?

When running any doom command, a Lisp error is thrown. E.g. for bin/doom doctor:
https://pastebin.com/iKdUxj3U

### Describe your attempts to resolve the issue

I tried went a bit through the commit history of bin/doom. It works in 0c918f3b2d4e91af56a198b2ac0bdf95ebe55fcb (except for #6801 ) and breaks in b914830403631b3d027cd6c9b9d2dd70546af84e.

### Steps to reproduce

1. Install Doom as per:
```
git clone https://github.com/hlissner/doom-emacs ~/doom-emacs
~/doom-emacs/bin/doom install
```
 2. Run bin/doom

### System Information

https://pastebin.com/Si4L96mr

**Comment by hlissner** [comment] 2022-09-17 17:52
Duplicate of #6777.

**Closed by hlissner** 2022-09-17 17:52 UTC
Labels: duplicate
