### ISSUE TITLE
"doom sync" infinite loop

### ISSUE THREAD

**Issue by liar666** [doomemacs/doomemacs#6650] opened 2022-08-08 18:14 UTC
### What did you expect to happen?

Seamless "doom sync/upgrade"

### What actually happened?

'git log' inside ~/.emacs.d/ shows I'm under doom commit 034ade04689806d4e4ab6b6d0f685d019cf7e476.

The attached "init.el" results in infinite loop:
```
$ doom sync
Loaded doomrc: ~/.emacs.d/
> Compiling your literate config...
Loaded doomrc: ~/.emacs.d/
> Compiling your literate config...
Loaded doomrc: ~/.emacs.d/
> Compiling your literate config...
Loaded doomrc: ~/.emacs.d/
> Compiling your literate config...
Loaded doomrc: ~/.emacs.d/
> Compiling your literate config...
Loaded doomrc: ~/.emacs.d/
```

[init.el.txt](https://github.com/doomemacs/doomemacs/files/9284062/init.el.txt)

### Describe your attempts to resolve the issue

- I removed everything inside ~/.doom.d until I found that the problem is in init.el

- Replaced my init.el with doom's template ~/.emacs.d/templates/init.example.el . It works.

### Steps to reproduce

- Put the init.el in your ~/.doom.d/
- Run doom sync
- Observe the infinite loop

### System Information

https://pastebin.com/jxNZwuii

**Comment by hlissner** [comment] 2022-08-08 18:34
Duplicate of #6642.

See https://github.com/doomemacs/doomemacs/issues/6642#issuecomment-1208348903.

**Closed by hlissner** 2022-08-08 18:34 UTC
Labels: duplicate
