### ISSUE TITLE
pyright just doesn't work

### ISSUE THREAD

**Issue by nozomirin** [doomemacs/doomemacs#6678] opened 2022-08-15 09:11 UTC
### What did you expect to happen?

When I open python files it should pop up a childframe to ask me to install pyright. (it acted like this before)

### What actually happened?

It just not pop up that minibuffer and nothing happened.

PS: I want to paste backtrace but I don't know how to operate. I checked
https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org but it was 404.
So I am sorry I can't give you more information.

### Steps to reproduce

1. install doomemacs
2. change init.el to turn on (python +lsp +pyright)
3. run doom sync
4. reload doom emacs
5. open python file

### System Information

https://pastebin.com/67243VvB

**Comment by hlissner** [comment] 2022-08-15 11:05
There's not enough information here to investigate this issue. `lsp-pyright` seems to be an option in `M-x lsp-install-server`, I don't understand the issue to be able to reproduce it either. 

I will revisit this once either of us find more leads, or close it after a month otherwise.

**Comment by nozomirin** [comment] 2022-08-15 11:55
Thanks for your reply.
I am sorry to make you confused. I regarded "minibuffer" as "childframe". I will learn more about emacs.

**Comment by nozomirin** [comment] 2022-08-15 11:57
Thanks for your reply.
I am sorry to make you confused. I regarded "minibuffer" as "childframe". I will learn more about emacs.

Also apology for the misoperation.

**Comment by Jdogzz** [comment] 2023-09-16 23:29
@nozomirin Are you still able to reproduce this? I am unable to reproduce this following your steps, I do get the option to install pyright when opening a python file.

https://pastebin.com/NpqjNWhg

**Closed** 2023-10-07 15:29 UTC
Labels: invalid
