### ISSUE TITLE
Debugger entered--Lisp error: (void-variable eglot-mode-map) after upgrading doom

### ISSUE THREAD

**Issue by offbyone** [doomemacs/doomemacs#7911] opened 2024-06-29 01:21 UTC
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Doom should start

### Current behavior

I have upgraded to doom emacs' most recent version:

```
$ git show --stat
commit d9c5f747abc29991b55009534ee3244e869eb109 (HEAD -> master)
Author: Henrik Lissner <git@henrik.io>
Date:   Fri Jun 28 19:11:28 2024 -0400

    tweak(org): org-effort-property = EFFORT

 modules/lang/org/config.el | 3 +++
 1 file changed, 3 insertions(+)
```

Emacs version is 29.4:

```
GNU Emacs 29.4 (build 2, aarch64-apple-darwin23.5.0, NS appkit-2487.60 Version 14.5 (Build 23F79)) of 2024-06-28
```

On startup, before loading (I think?) any of my customizations, doom fails when initializing eglot:

```
Debugger entered--Lisp error: (void-variable eglot-mode-map)
  (define-key eglot-mode-map [remap xref-find-apropos] #'consult-eglot-symbols)
  (progn (use-package-statistics-gather :init 'consult-eglot nil) (define-key eglot-mode-map [remap xref-find-apropos] #'consult-eglot-symbols) (eval-after-load 'consult-eglot #'(lambda nil (progn (use-package-statistics-gather :config 'consult-eglot nil) (use-package-statistics-gather :config 'consult-eglot t)))) (use-package-statistics-gather :init 'consult-eglot t))
  (if t (progn (use-package-statistics-gather :init 'consult-eglot nil) (define-key eglot-mode-map [remap xref-find-apropos] #'consult-eglot-symbols) (eval-after-load 'consult-eglot #'(lambda nil (progn (use-package-statistics-gather :config 'consult-eglot nil) (use-package-statistics-gather :config 'consult-eglot t)))) (use-package-statistics-gather :init 'consult-eglot t)))
  load-with-code-conversion("/Users/offby1/.config/emacs/modules/tools/lsp/+egl..." "/Users/offby1/.config/emacs/modules/tools/lsp/+egl..." nil t)
  load("/Users/offby1/.config/emacs/modules/tools/lsp/+egl..." nil nomessage)
  (condition-case e (load path noerror 'nomessage) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (setq path (locate-file path load-path (get-load-suffixes))) (signal (cond ((not (and path (featurep ...))) 'error) ((file-in-directory-p path (expand-file-name "cli" doom-core-dir)) 'doom-cli-error) ((file-in-directory-p path doom-core-dir) 'doom-core-error) ((file-in-directory-p path doom-user-dir) 'doom-user-error) ((file-in-directory-p path doom-profile-dir) 'doom-profile-error) ((file-in-directory-p path doom-modules-dir) 'doom-module-error) ('doom-error)) (list path e))))
  doom-load("/Users/offby1/.config/emacs/modules/tools/lsp/+egl..." nil)
  (if t (doom-load (file-name-concat "/Users/offby1/.config/emacs/modules/tools/lsp/" "+eglot") nil) (doom-load (file-name-concat "/Users/offby1/.config/emacs/modules/tools/lsp/" "+lsp") nil))
  load-with-code-conversion("/Users/offby1/.config/emacs/modules/tools/lsp/conf..." "/Users/offby1/.config/emacs/modules/tools/lsp/conf..." nil t)
  load("~/.config/emacs/modules/tools/lsp/config" nil nomessage)
```

### Steps to reproduce

Open emacs

### System Information

https://pastebin.com/FhAd1cii

**Comment by offbyone** [comment] 2024-06-29 01:41
So, there is a fix, ish; I deleted `~/.config/emacs/.local/straight` and re-ran `doom install`; that gave me a working doom.

**Comment by yonghuier** [comment] 2024-06-29 03:29
Hi. I have this same issue. And it can't be fixed by reinstalling.

```
Warning (initialization): An error occurred while loading ‘/Users/wyh/.config/emacs/.local/etc/@/init.29.elc’:

Error in a Doom module: /Users/wyh/.config/emacs/modules/tools/lsp/+eglot.el, (void-variable eglot-mode-map)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

backtrace as follow

```
Debugger entered--Lisp error: (void-variable eglot-mode-map)
  (define-key eglot-mode-map [remap xref-find-apropos] #'consult-eglot-symbols)
  (progn (use-package-statistics-gather :init 'consult-eglot nil) (define-key eglot-mode-map [remap xref-find-apropos] #'consult-eglot-symbols) (eval-after-load 'consult-eglot #'(lambda nil (progn (use-package-statistics-gather :config 'consult-eglot nil) (use-package-statistics-gather :config 'consult-eglot t)))) (use-package-statistics-gather :init 'consult-eglot t))
  (if t (progn (use-package-statistics-gather :init 'consult-eglot nil) (define-key eglot-mode-map [remap xref-find-apropos] #'consult-eglot-symbols) (eval-after-load 'consult-eglot #'(lambda nil (progn (use-package-statistics-gather :config 'consult-eglot nil) (use-package-statistics-gather :config 'consult-eglot t)))) (use-package-statistics-gather :init 'consult-eglot t)))
  load-with-code-conversion("/Users/wyh/.config/emacs/modules/tools/lsp/+eglot...." "/Users/wyh/.config/emacs/modules/tools/lsp/+eglot...." nil t)
  load("/Users/wyh/.config/emacs/modules/tools/lsp/+eglot" nil nomessage)
  (condition-case e (load path noerror 'nomessage) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (setq path (locate-file path load-path (get-load-suffixes))) (signal (cond ((not (and path (featurep ...))) 'error) ((file-in-directory-p path (expand-file-name "cli" doom-core-dir)) 'doom-cli-error) ((file-in-directory-p path doom-core-dir) 'doom-core-error) ((file-in-directory-p path doom-user-dir) 'doom-user-error) ((file-in-directory-p path doom-profile-dir) 'doom-profile-error) ((file-in-directory-p path doom-modules-dir) 'doom-module-error) ('doom-error)) (list path e))))
  doom-load("/Users/wyh/.config/emacs/modules/tools/lsp/+eglot" nil)
  (if t (doom-load (file-name-concat "/Users/wyh/.config/emacs/modules/tools/lsp/" "+eglot") nil) (doom-load (file-name-concat "/Users/wyh/.config/emacs/modules/tools/lsp/" "+lsp") nil))
  load-with-code-conversion("/Users/wyh/.config/emacs/modules/tools/lsp/config...." "/Users/wyh/.config/emacs/modules/tools/lsp/config...." nil t)
  load("~/.config/emacs/modules/tools/lsp/config" nil nomessage)
  (condition-case e (load path noerror 'nomessage) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (setq path (locate-file path load-path (get-load-suffixes))) (signal (cond ((not (and path (featurep ...))) 'error) ((file-in-directory-p path (expand-file-name "cli" doom-core-dir)) 'doom-cli-error) ((file-in-directory-p path doom-core-dir) 'doom-core-error) ((file-in-directory-p path doom-user-dir) 'doom-user-error) ((file-in-directory-p path doom-profile-dir) 'doom-profile-error) ((file-in-directory-p path doom-modules-dir) 'doom-module-error) ('doom-error)) (list path e))))
  doom-load("~/.config/emacs/modules/tools/lsp/config")
  byte-code("\305\306!\204\f\0\305\307!\203\16\3\10\30\310\311!\211\203\"\0\211@\312\1!\210\1A\266\202\202\21\0\210\313\21\314\22\315\316\317\"\210\315\320\321\"\210\315..." [doom-context doom-modules doom-disabled-packages custom-file doom-module-context doom-context-p init reload ensure-list modules doom-context-push #<hash-table equal 65/65 0x49a72e23> (citar-org-roam) setplist :core (nil [0 -110 -110 :core nil nil nil]) :user (nil [1 105 -105 :user nil nil nil]) :completion (company [3 0 0 :completion company nil nil] vertico [4 0 0 :completion vertico (+icons) nil]) :ui (deft [5 0 0 :ui deft nil nil] doom [6 0 0 :ui doom nil nil] doom-dashboard [7 0 0 :ui doom-dashboard nil nil] hl-todo [8 0 0 :ui hl-todo nil nil] ligatures [9 0 0 :ui ligatures nil nil] modeline [10 0 0 :ui modeline nil nil] ophints [11 0 0 :ui ophints nil nil] popup [12 0 0 :ui popup (+defaults) nil] unicode [13 0 0 :ui unicode nil nil] vc-gutter [14 0 0 :ui vc-gutter (+pretty) nil] vi-tilde-fringe [15 0 0 :ui vi-tilde-fringe nil nil] workspaces [16 0 0 :ui workspaces nil nil] zen [17 0 0 :ui zen nil nil]) :editor (evil [18 0 0 :editor evil (+everywhere) nil] fold [19 0 0 :editor fold nil nil] format [20 0 0 :editor format nil nil] multiple-cursors [21 0 0 :editor multiple-cursors nil nil] rotate-text [22 0 0 :editor rotate-text nil nil] snippets [23 0 0 :editor snippets nil nil] word-wrap [24 0 0 :editor word-wrap nil nil]) :emacs (dired [25 0 0 :emacs dired (+icons) nil] electric [26 0 0 :emacs electric nil nil] ibuffer [27 0 0 :emacs ibuffer (+icons) nil] undo [28 0 0 :emacs undo (+tree) nil] vc [29 0 0 :emacs vc nil nil]) :term (eshell [30 0 0 :term eshell nil nil] vterm [31 0 0 :term vterm nil nil]) :checkers (syntax [32 0 0 :checkers syntax nil nil]) :tools (biblio [33 0 0 :tools biblio nil nil] debugger [34 0 0 :tools debugger nil nil] direnv [35 0 0 :tools direnv nil nil] editorconfig [36 0 0 :tools editorconfig nil nil] eval [37 0 0 :tools eval (+overlay) nil] lookup [38 0 0 :tools lookup (+docsets +dictionay) nil] lsp [39 0 0 :tools lsp (+eglot) nil] magit [40 0 0 :tools magit nil nil] pdf [41 0 0 :tools pdf nil nil] rgb [42 0 0 :tools rgb nil nil] tree-sitter [43 0 0 :tools tree-sitter nil nil] upload [44 0 0 :tools upload nil nil]) :os (macos [45 0 0 :os macos nil nil] tty [46 0 0 :os tty nil nil]) :lang (beancount [47 0 0 :lang beancount nil nil] cc [48 0 0 :lang cc (+lsp +tree-sitter) nil] emacs-lisp [49 0 0 :lang emacs-lisp nil nil] fortran [50 0 0 :lang fortran (+lsp) nil] haskell [51 0 0 :lang haskell (+lsp +tree-sitter) nil] json [52 0 0 :lang json nil nil] latex [53 0 0 :lang latex (+lsp +cdlatex +fold +latexmk) nil] markdown [54 0 0 :lang markdown (+grip) nil] org [55 0 0 :lang org (+roam2 +brain +dragndrop +jupyter +noter +gnuplot +journal +jupyter +pandoc +pomodoro +pretty +present) nil] plantuml [56 0 0 :lang plantuml nil nil] python [57 0 0 :lang python (+lsp +conda +pyright +tree-sitter) nil] racket [58 0 0 :lang racket (+lsp +xp) nil] rust [59 0 0 :lang rust (+lsp) nil] sh [60 0 0 :lang sh nil nil] yaml [61 0 0 :lang yaml nil nil]) :app (calendar [62 0 0 :app calendar nil nil] rss [63 0 0 :app rss (+org) nil]) :config (use-package [2 -111 -111 :config use-package nil nil] default [64 0 0 :config default (+bindings +smartparens) nil]) [2 -111 -111 :config use-package nil nil] doom-load "~/.config/emacs/modules/config/use-package/init" [0 -110 -110 :core nil nil nil] "~/.config/emacs/lisp/init" doom-run-hooks doom-before-modules-init-hook [18 0 0 :editor evil (+everywhere) nil] "~/.config/emacs/modules/editor/evil/init" doom-after-modules-init-hook ...] 4)
  load("/Users/wyh/.config/emacs/.local/etc/@/init.29.elc" noerror nomessage nosuffix)
  (progn (load init-file-name 'noerror 'nomessage 'nosuffix))
  (if init-file-name (progn (load init-file-name 'noerror 'nomessage 'nosuffix)))
  (let ((init-file-name (file-name-concat doom-profile-dir (format "init.%d.elc" emacs-major-version)))) (setq user-init-file t) (if init-file-name (progn (load init-file-name 'noerror 'nomessage 'nosuffix))) (if (eq user-init-file t) (progn (signal 'doom-nosync-error (list init-file-name)))) (setq user-init-file (concat (string-remove-suffix ".elc" user-init-file) ".el")))
  (progn (let ((init-file-name (file-name-concat doom-profile-dir (format "init.%d.elc" emacs-major-version)))) (setq user-init-file t) (if init-file-name (progn (load init-file-name 'noerror 'nomessage 'nosuffix))) (if (eq user-init-file t) (progn (signal 'doom-nosync-error (list init-file-name)))) (setq user-init-file (concat (string-remove-suffix ".elc" user-init-file) ".el"))))
  (if init-file-user (progn (let ((init-file-name (file-name-concat doom-profile-dir (format "init.%d.elc" emacs-major-version)))) (setq user-init-file t) (if init-file-name (progn (load init-file-name 'noerror 'nomessage 'nosuffix))) (if (eq user-init-file t) (progn (signal 'doom-nosync-error (list init-file-name)))) (setq user-init-file (concat (string-remove-suffix ".elc" user-init-file) ".el")))))
  (condition-case error (if init-file-user (progn (let ((init-file-name (file-name-concat doom-profile-dir (format "init.%d.elc" emacs-major-version)))) (setq user-init-file t) (if init-file-name (progn (load init-file-name 'noerror 'nomessage 'nosuffix))) (if (eq user-init-file t) (progn (signal 'doom-nosync-error (list init-file-name)))) (setq user-init-file (concat (string-remove-suffix ".elc" user-init-file) ".el"))))) ((debug error) (display-warning 'initialization (format-message "An error occurred while loading `%s':\n\n%s%s%s\n\nTo ..." user-init-file (get (car error) 'error-message) (if (cdr error) ": " "") (mapconcat #'(lambda (s) (prin1-to-string s t)) (cdr error) ", ")) :warning) (setq init-file-had-error t)))
  (let ((debug-on-error debug-on-error-initial)) (condition-case error (if init-file-user (progn (let ((init-file-name (file-name-concat doom-profile-dir ...))) (setq user-init-file t) (if init-file-name (progn (load init-file-name ... ... ...))) (if (eq user-init-file t) (progn (signal ... ...))) (setq user-init-file (concat (string-remove-suffix ".elc" user-init-file) ".el"))))) ((debug error) (display-warning 'initialization (format-message "An error occurred while loading `%s':\n\n%s%s%s\n\nTo ..." user-init-file (get (car error) 'error-message) (if (cdr error) ": " "") (mapconcat #'(lambda ... ...) (cdr error) ", ")) :warning) (setq init-file-had-error t))) (or (eq debug-on-error debug-on-error-initial) (progn (setq debug-on-error-should-be-set t) (setq debug-on-error-from-init-file debug-on-error))))
  (let ((debug-on-error-from-init-file nil) (debug-on-error-should-be-set nil) (debug-on-error-initial (if (eq init-file-debug t) 'startup init-file-debug)) (inhibit-null-byte-detection t)) (let ((debug-on-error debug-on-error-initial)) (condition-case error (if init-file-user (progn (let ((init-file-name ...)) (setq user-init-file t) (if init-file-name (progn ...)) (if (eq user-init-file t) (progn ...)) (setq user-init-file (concat ... ".el"))))) ((debug error) (display-warning 'initialization (format-message "An error occurred while loading `%s':\n\n%s%s%s\n\nTo ..." user-init-file (get (car error) 'error-message) (if (cdr error) ": " "") (mapconcat #'... (cdr error) ", ")) :warning) (setq init-file-had-error t))) (or (eq debug-on-error debug-on-error-initial) (progn (setq debug-on-error-should-be-set t) (setq debug-on-error-from-init-file debug-on-error)))) (if debug-on-error-should-be-set (progn (setq debug-on-error debug-on-error-from-init-file))))
  startup--load-user-init-file@init-doom(#f(compiled-function () #<bytecode -0x187e8ec6f2cf00c4>) #f(compiled-function () #<bytecode 0x4d131ce0e5cb08b>) t)
  apply(startup--load-user-init-file@init-doom (#f(compiled-function () #<bytecode -0x187e8ec6f2cf00c4>) #f(compiled-function () #<bytecode 0x4d131ce0e5cb08b>) t))
  #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100)))(#f(compiled-function () #<bytecode -0x187e8ec6f2cf00c4>) #f(compiled-function () #<bytecode 0x4d131ce0e5cb08b>) t)
  apply(#f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100))) (#f(compiled-function () #<bytecode -0x187e8ec6f2cf00c4>) #f(compiled-function () #<bytecode 0x4d131ce0e5cb08b>) t))
  (progn (if (setq site-run-file (get 'site-run-file 'initial-value)) (progn (let ((inhibit-startup-screen inhibit-startup-screen)) (let ((load-file (symbol-function ...))) (ignore load-file) (let* ((vnew ...) (old ...)) (unwind-protect (progn ... ...) (fset ... old))))))) (apply fn args) (setq init t))
  (unwind-protect (progn (if (setq site-run-file (get 'site-run-file 'initial-value)) (progn (let ((inhibit-startup-screen inhibit-startup-screen)) (let ((load-file ...)) (ignore load-file) (let* (... ...) (unwind-protect ... ...)))))) (apply fn args) (setq init t)) (if (or (not init) init-file-had-error) (progn (doom--reset-inhibited-vars-h))) (advice-remove #'tool-bar-setup #'ignore) (let ((sym 'tool-bar-mode)) (defalias 'doom-transient-hook0 #'(lambda (&rest _) "Transient hook for tool-bar-mode" (tool-bar-setup) (let ((sym ...)) (cond (... ...) (... ...))) (unintern 'doom-transient-hook0 nil))) (cond ((functionp sym) (advice-add 'tool-bar-mode :before #'doom-transient-hook0)) ((symbolp sym) (put 'doom-transient-hook0 'permanent-local-hook t) (add-hook sym #'doom-transient-hook0 nil)))) (if (default-toplevel-value 'mode-line-format) nil (progn (set-default 'mode-line-format (get 'mode-line-format 'initial-value)))))
  (let (init) (unwind-protect (progn (if (setq site-run-file (get 'site-run-file 'initial-value)) (progn (let ((inhibit-startup-screen inhibit-startup-screen)) (let (...) (ignore load-file) (let* ... ...))))) (apply fn args) (setq init t)) (if (or (not init) init-file-had-error) (progn (doom--reset-inhibited-vars-h))) (advice-remove #'tool-bar-setup #'ignore) (let ((sym 'tool-bar-mode)) (defalias 'doom-transient-hook0 #'(lambda (&rest _) "Transient hook for tool-bar-mode" (tool-bar-setup) (let (...) (cond ... ...)) (unintern 'doom-transient-hook0 nil))) (cond ((functionp sym) (advice-add 'tool-bar-mode :before #'doom-transient-hook0)) ((symbolp sym) (put 'doom-transient-hook0 'permanent-local-hook t) (add-hook sym #'doom-transient-hook0 nil)))) (if (default-toplevel-value 'mode-line-format) nil (progn (set-default 'mode-line-format (get 'mode-line-format 'initial-value))))))
  startup--load-user-init-file@undo-hacks(#f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100))) #f(compiled-function () #<bytecode -0x187e8ec6f2cf00c4>) #f(compiled-function () #<bytecode 0x4d131ce0e5cb08b>) t)
  apply(startup--load-user-init-file@undo-hacks #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100))) (#f(compiled-function () #<bytecode -0x187e8ec6f2cf00c4>) #f(compiled-function () #<bytecode 0x4d131ce0e5cb08b>) t))
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x187e8ec6f2cf00c4>) #f(compiled-function () #<bytecode 0x4d131ce0e5cb08b>) t)
  command-line()
  normal-top-level()
```

**Comment by yonghuier** [comment] 2024-06-29 03:42
The current workaround is to modify `(lsp +eglot)` -> only `lsp` in init.el.

**Comment by arun-mani-j** [comment] 2024-06-29 06:19
In my case, after today's update, my Doom config no longer took effect. Like nothing in my init.el or config.el, it felt like a fresh Doom install.

I stopped Emacs server `systemctl --user stop emacs` and then it gave me the variable error we are facing here.

So I `rm -rf`ed `straight` and did `doom install`. After a lot of `git clone` failures (which I think is due to my internet provider), it installed. But running `doom doctor` still gave the issue.

So I removed `+eglot` from `init.el` and now running `doom sync` gives this:
```
...
> Updating pinned packages...
    x The package manager threw an error
    x Last 16 lines of straight's error log:
      [Return code: 0]
      $ cd /home/arun-mani-j/.config/emacs/.local/straight/repos/nodejs-repl.el/
      $ git rev-parse HEAD
      03d0b64768b40b71ae54de1b50eb58719e615746
      [Return code: 0]
      $ cd /home/arun-mani-j/.config/emacs/.local/straight/repos/npm-mode/
      $ git rev-parse HEAD
      3ee7c0bad5b7a041d4739ef3aaa06a3dc764e5eb
      [Return code: 0]
      $ cd /home/arun-mani-j/.config/emacs/.local/straight/repos/js2-refactor.el/
      $ git rev-parse HEAD
      HEAD
      fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
      Use '--' to separate paths from revisions, like this:
      'git <command> [<revision>...] -- [<file>...]'
      [Return code: 128]
    ! Wrote extended straight log to ~/.config/emacs/.local/state/logs/cli.doom.240629114229.22040.error
    ! Script was abruptly aborted, leaving Doom in an incomplete state!
    - Run 'doom sync' to repair it.
```

**Comment by hlissner** [comment] 2024-06-29 06:56
My bad. This was a regression introduced in ae9e1feaa6b8b741a8f1a745e19aebb553f030b3. I've reverted the change in d3d5047, which should fix this issue.

**Closed** 2024-06-29 06:56 UTC
Labels: module:tools/lsp, is:regression
