### ISSUE TITLE
treemacs warning caused by that `hl-line` has no background

### ISSUE THREAD

**Issue by laishulu** [doomemacs/doomemacs#957] opened 2018-10-14 14:08 UTC
### Observed behavior
I am use terminal emacs with `doom-molokai` theme.
when treemacs is invoked, I got the following warning:
```
[Treemacs] Warning: couldn’t find hl-line-mode’s background color for icons, falling back on unspecified-bg.
```
Even if `(set-face-background 'hl-line "#171717")` does not work

### Expected behavior

reasonable default to dissmiss the warning.

<details>
<summary>Click to expand</summary>

```
- OS: darwin (x86_64-apple-darwin14.5.0)
- Emacs: 26.1 (May 31, 2018)
- Doom: 2.0.9 (develop cdf745e72a3e8bf9bef1f0fa4d051b00aab351e3)
- Graphic display: nil (daemon: nil)
- System features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
- Details:
  ```elisp
  elc count: 0
  uname -a:  Darwin machw 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro10,1 Darwin
  modules:   (:feature (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles fci hl-todo nav-flash treemacs (popup +all +defaults) pretty-code unicode vc-gutter vi-tilde-fringe window-select :editor multiple-cursors rotate-text :emacs ediff electric hideshow imenu vc :tools magit :lang emacs-lisp markdown (org +attach +babel +capture +export +present) python rust (sh +fish) :config)
  packages:  (evil-textobj-column (evil-textobj-entire :recipe (evil-textobj-entire :fetcher github :repo supermomonga/evil-textobj-entire)) (evil-textobj-line :recipe (evil-textobj-line :fetcher github :repo syohex/evil-textobj-line)))
  exec-path: (/usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/python/libexec/bin /usr/local/bin /usr/local/sbin /usr/bin /bin /usr/sbin /sbin ~/.cargo/bin ~/bin /usr/local/opt/fzf/bin /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10 /Applications/Emacs.app/Contents/MacOS/libexec /Applications/Emacs.app/Contents/MacOS/bin)
  ```
```
</details>

**Comment by laishulu** [comment] 2018-10-15 05:42
@hlissner 
I don't think its `external` problem.
I think its because that `hl-line` is reset by the doom-theme sytem.
I `(set-face-background 'hl-line "#171717")` at the beginning of `init.el`, 
but `'hl-line` is reset later.

**Comment by hlissner** [comment] 2018-10-15 06:31
I meant that this is a `doom-themes` issue, not a doom-emacs issue. In any case, I know the cause of the issue and am working on a fix.

**Comment by laishulu** [comment] 2018-11-19 05:02
@hlissner Any progress?

**Comment by laishulu** [comment] 2018-12-11 14:31
@hlissner Any progress?

**Comment by laishulu** [comment] 2019-01-19 15:16
@hlissner 
Any progress?

**Comment by hlissner** [comment] 2019-02-14 06:41
Sorry for the super late response. I'll look into this again over the weekend.

Just a quick question: are you seeing this in terminal or GUI Emacs?

**Comment by laishulu** [comment] 2019-02-14 12:13
@hlissner terminal. I only use emacs in terminal

**Comment by hlissner** [comment] 2019-03-04 07:45
Does this resolve this issue?

```elisp
(after! treemacs
  (remove-hook 'treemacs-mode-hook #'+treemacs|improve-hl-line-contrast))
```

**Comment by laishulu** [comment] 2019-03-04 09:13
![default](https://user-images.githubusercontent.com/1224321/53722545-c8704080-3ea0-11e9-993e-a435c73f843e.png)
This message will show for a short period, and then gone.

**Comment by MatthewMSaucedo** [comment] 2020-06-22 18:50
Any progress here? I seem to be running into the same issue.

**Comment by zackteo** [comment] 2020-06-29 08:29
I get this same warning for `doom-material` but I'm getting this from running `doom doctor`. Does not show within GUI Emacs itself.

Was looking at https://github.com/Alexander-Miller/treemacs#faq but doesn't seem to work

**Comment by zackteo** [comment] 2020-06-29 08:39
It won't show up if i throw `  :init (defvar treemacs-no-load-time-warnings t)` into `(use-package! hl-line ....` in `core/core-ui.el` but I don't think that's solving the problem of `treemacs` loading faster than `hl-line` :x

**Comment by Jdogzz** [comment] 2023-09-15 03:56
I'm not able to reproduce this, running emacs in the terminal with doom-molokai enabled, and calling treemacs. No errors from treemacs were shown in the Messages buffer.

https://pastebin.com/VFzJrktH

**Comment by Jdogzz** [comment] 2023-09-15 18:04
@laishulu Are you still able to reproduce this bug on your end?

**Comment by hlissner** [comment] 2023-09-15 18:37
I cannot reproduce this either. I'd wager it was resolved upstream at some point, so I will close this, but feel free to follow up here if that isn't the case. Thanks for bringing it to my attention!

**Closed by hlissner** 2023-09-15 18:37 UTC
Labels: is:bug, re:packages
