### ISSUE TITLE
doom install/refresh crashes useland container under android

### ISSUE THREAD

**Issue by cl4rknova** [doomemacs/doomemacs#1841] opened 2019-10-01 12:37 UTC
Hi, I am a bit lost debugging an issue I have while using doom emacs in several container based environments for android. 
While trying several distros - userland, termux chroot and GNURoot (all with unrooted Phone) I can run doom emacs config until I try to do a "doom install" or "doom refresh". 
This will freeze the container more or less immediately  or in the first 2 seconds.

So far I had no effort to get debugging information. 
Could you maybe give me a hint what could maybe be the cause or how to debug this thing?
Under Termux everything works fine - as long as I run doom in the main termux environment and not in a termux based chroot.

**Comment by cl4rknova** [comment] 2019-10-01 13:08
in debian chroot inside termux I now got this error:
`Loading /etc/emacs/site-start.d/00debian.el (source)...
Building straight...
./path/path.c:547: Comparison compare_paths2(const char *, size_t, const char *, size_t): assertion "length2 > 0" failed
proot warning: signal 6 received from process 1481
`
I think I have to debug this  from the temux view. But after this happens under several different container systems I wonderif there is something which can be done in the doom scripts...

**Comment by cl4rknova** [comment] 2019-10-01 15:39
Ah - ok - this somehow is happending while loading "straight.el". I will look for the reason later...

**Comment by cl4rknova** [comment] 2019-10-02 14:21
Maybe I had been a wrong track.
Seems like the crashes happen while building straight and/or use-package stuff.
But now I see that this is crashing also when I do a "doom help"
This should be happening only in proot environments. So this is more a bug related to proot than to doom and I could understand if this ticket will be rejected. However - if anyone got an idea how to debug the doom bootstrapping process - this would help me allot.

**Comment by codygman** [comment] 2020-01-08 22:10
I can confirm im affected by this and do not use doom.

**Comment by codygman** [comment] 2020-01-17 02:38
This is my configs workaround:

```elisp
(when (file-exists-p "/data/data/com.termux/
  (setq straight-use-symlinks nil))
```

**Comment by codygman** [comment] 2020-01-17 02:50
Looks like this will finish building:

```diff
$ git diff
diff --git a/core/autoload/packages.el b/core/autoload/packages.el
index 35f275a61..c16108fa6 100644
--- a/core/autoload/packages.el
+++ b/core/autoload/packages.el
@@ -1,5 +1,7 @@
 ;;; core/autoload/packages.el -*- lexical-binding: t; -*-

+(setq straight-use-symlinks nil)
+
 ;;
 ;;; Package metadata
```

**Comment by codygman** [comment] 2020-01-26 06:36
Looking at this again, I think your error is like one I encountered trying to install emacs with `Nix on Android` that is more related to proot. Maybe still you can try disabling symlinks and see if it maeks a difference though.

**Comment by codygman** [comment] 2020-05-24 04:52
I now use doom, had to install it on Android again, and came back here for the fix.

What would be necessary to add this into core doom? Maybe my termux detection with folder existence is good enough?

**Comment by lypanov** [comment] 2020-12-16 14:40
> This is my configs workaround:
> 
> ```emacs-lisp
> (when (file-exists-p "/data/data/com.termux/
>   (setq straight-use-symlinks nil))
> ```

Thank you so much! :heart: This makes my day! For 6 months I've been using vim again as a fallback due to spacemacs not working in termux archlinux. Thanks to this workaround I can finally use my preferred editor!

The workaround IMHO doesn't really belong in either doom-emacs nor in spacemacs. The underlying issue seems to be an issue with proot (IMHO this looks the most realistic proper fix https://github.com/zhongweiy/proot/commit/aea25ed87e7dc7e5fdd34617d2954940f5fd066a but I haven't verified / dug deep as my Android tablet is the only laptop/2-in-1 I use).

Thank you doom for failing to install but in the process getting my normal emacs distro working again! :heart: Shall have to look into doom again another day alas.

**Comment by lypanov** [comment] 2020-12-16 21:20
@SDRausty from the TermuxArch project brilliantly managed to find that this is actually already fixed in the latest proot in the termux repo - see https://github.com/termux/proot/issues/123

A termux level pkg upgrade did the trick for me to fix this issue.

**Closed** 2022-08-05 17:24 UTC
Labels: help wanted, is:support, re:mobile, os:termux
