### ISSUE TITLE
        fatal: unable to access 'https://git.savannah.gnu.org/git/emacs/nongnu.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to git.savannah.gnu.org:443          [Return code: 128]

### ISSUE THREAD

**Issue by evbby** [doomemacs/doomemacs#7973] opened 2024-07-30 00:22 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Opening this issue because *git.savannah.gnu.org* being down is not a rare occurrence, it would seem. It may be worth investigating whether dependency on it can be removed.

### Current behavior

1. run `doom sync` which should install new packages
2. get error: 

```
  run!("doom" ("sync"))
  load-with-code-conversion("/Users/evelyn/Documents/code/dotfiles/.config/emacs/bin/doom" "/Users/evelyn/Documents/code/dotfiles/.config/emacs/bin/doom" nil t)
  command-line-1(("--load" "/Users/evelyn/.config/emacs/bin/doom" "--" "sync"))
  command-line()
  normal-top-level()
      x The package manager threw an error
      x Last 16 lines of straight's error log:
        $ cd /Users/evelyn/Documents/code/dotfiles/.config/emacs/.local/straight/repos/melpa/
        $ git rev-parse HEAD
        3e9ed8efcc22219b1d4fb804521a47670b7668d3
        [Return code: 0]
        $ cd /Users/evelyn/Documents/code/dotfiles/.config/emacs/.local/straight/repos/nongnu-elpa/
        $ git rev-parse HEAD
        f031337c6ee125455a98e2de899a563388e5de19
        [Return code: 0]
        $ cd /Users/evelyn/Documents/code/dotfiles/.config/emacs/.local/straight/repos/nongnu-elpa/
        $ git config --get remote.origin.url
        https://git.savannah.gnu.org/git/emacs/nongnu.git
        [Return code: 0]
        $ cd /Users/evelyn/Documents/code/dotfiles/.config/emacs/.local/straight/repos/nongnu-elpa/
        $ git fetch origin
        fatal: unable to access 'https://git.savannah.gnu.org/git/emacs/nongnu.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to git.savannah.gnu.org:443 
        [Return code: 128]
      ! Wrote extended straight log to ~/Documents/code/dotfiles/.config/emacs/.local/state/logs/cli.doom.240730021254.35221.error
      ! Script was abruptly aborted, leaving Doom in an incomplete state!
      - Run 'doom sync' to repair it.
      ✓ Finished in 15.53248s
```

```
❯ curl -v https://git.savannah.gnu.org/git/emacs/nongnu.git/
* Host git.savannah.gnu.org:443 was resolved.
* IPv6: 2001:470:142::168
* IPv4: 209.51.188.168
*   Trying 209.51.188.168:443...
* Connected to git.savannah.gnu.org (209.51.188.168) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to git.savannah.gnu.org:443 
* Closing connection
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to git.savannah.gnu.org:443 
```

### Steps to reproduce

See **Current Behavior**

### System Information

https://pastebin.com/wnapLqS8

**Comment by eviemingming** [comment] 2024-07-30 00:23
Not exactly a bug, obviously. Nevertheless still a valid issue.

**Comment by hlissner** [comment] 2024-07-30 01:14
Closing this as a duplicate of #7171.

**Closed by hlissner** 2024-07-30 01:14 UTC
Labels: duplicate
