### ISSUE TITLE
(void-function warn!)

### ISSUE THREAD

**Issue by bixuanzju** [doomemacs/doomemacs#6885] opened 2022-10-10 02:12 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [x] The issue can be reproduced on the **latest** available commit of Doom.
- [x] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

`doom doctor` should report warnings

### Current behavior

`doom doctor` doesn't report anything, even though the expected executable required in my custom module is missing.

### Steps to reproduce

1. Open Emacs
2. Evaluate `(warn! "warning")`
3. Echo area shows "pp-eval-expression: Symbol’s function definition is void: warn!"

`assert!` is also void.

### System Information

> generated  Oct 10, 2022 10:11:50
system     Red Hat Enterprise Linux 8.6 (Ootpa) Linux 4.18.0-372.26.1.el8_6.x86_64 x86_64
emacs      28.1 ~/.emacs.d/
doom       3.0.0-pre PROFILE=_@0 HEAD -> master 9f22a0a2 2022-10-07 19:48:23 +0200 ~/.doom.d/
shell      /bin/bash
features   CAIRO DBUS FREETYPE GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG
           SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM LUCID ZLIB
traits     batch server-running envvar-file
modules    :config use-package :completion company (vertico +icons) :ui doom doom-dashboard hl-todo ligatures modeline
           nav-flash ophints (popup +all) treemacs (vc-gutter +diff-hl) vi-tilde-fringe window-select workspaces :editor
           (evil +everywhere) file-templates fold format multiple-cursors snippets word-wrap :emacs dired electric undo vc
           :term term :checkers syntax (spell +enchant +flyspell) :tools (eval +overlay) lookup lsp magit make rgb
           tree-sitter :os (tty +osc) :lang (cc +lsp +tree-sitter) data emacs-lisp (haskell +lsp) (&user mu) (json
           +tree-sitter) (org +roam2 +pretty) rest (sh +lsp +tree-sitter) (yaml +lsp) :config (default +bindings
           +smartparens)
packages   (modus-themes)

**Comment by hlissner** [comment] 2022-10-10 18:11
`warn!` and `assert!` are [only for CLI sessions](https://github.com/doomemacs/doomemacs/blob/master/lisp/cli/doctor.el#L12-L37). To be specific, only for doctor.el files. They're not present in interactive sessions and shouldn't be, so it's natural trying to use them will throw an error.

Side-note: in the 3.0 release, doctor.el files and the Doctor API will be largely redesigned, so these macros won't exist for long anyway.

In any case, this is not a bug so I will close this, but feel free to follow up here.

**Closed by hlissner** 2022-10-10 18:11 UTC
Labels: invalid

**Comment by bixuanzju** [comment] 2022-10-11 00:13
@hlissner thanks for the explanation -- my original issue was that `doom doctor` doesn't seem to be working... if it is not `warn!` or `assert!`, what could have caused it?
