### ISSUE TITLE
Zen mode changes zooming while scrolling on Rmarkdown document

### ISSUE THREAD

**Issue by GiulioCentorame** [doomemacs/doomemacs#5414] opened 2021-08-25 10:15 UTC
### What did you expect to happen?

Zoom in Zen mode should be consistent in the document while scrolling with keyboard or mousewheel

### What actually happened?

When I open an Rmarkdown document and activate zen mode, whenever I scroll at the top of the document /click some sections with or without code chunks, Emacs zooms the text in to an unreasonable extent. Here's some screenshots of the before/after. The other buffers are fine.

[Here](https://imgur.com/a/bISid9n)'s some screenshots of the behaviour

### Describe your attempts to resolve the issue

The current workaround I am using is just to avoid using Zen mode. The buffer revert to the original state if I close and reopen the file, but not if I am untoggling the minor mode

### Steps to reproduce

1. Open Emacs
2. Open `filename.Rmd`
3. `SPC t z` (`M-x +zen/toggle`) or `SPC t Z`
4. Scroll to the top of the document 

### System Information

https://pastebin.com/z9jf1rBd

**Comment by KaiAragaki** [comment] 2024-06-30 15:30
I can reproduce this.

This bug appears to be polymode (and not `R`, nor `.Rmd`) related. The following minimal `test.md` file is enough to reproduce the issue:

``````md

```python

```

test

``````

Clicking inside the fenced code block after toggling to `zen-mode` causes text size to increase. If `zen-mode` was toggled when the cursor was inside the block, clicking outside the fenced block causes text size to increase (so long as this triggers the mode to shift. Clicking between fenced code blocks of the same type does not trigger this shift).

To my limited knowledge, it seems like some polymode hooks are causing this behavior. I think the scrolling mentioned above triggered this by dragging the cursor through code blocks.

**Comment by hlissner** [comment] 2024-07-01 01:14
I can reproduce this and similar weirdness with just `polymode` and any non-zero `text-scale` offset, with or without Doom Emacs, so this appears to be a `polymode` issue, rather than Doom one.

Seems polymode works by invisibly switching to a different buffer when the cursor moves into (and out of) regions with different major-modes, but does not bring with it all of the buffer-local state that might've been set in the previous buffer (like the buffer-local face-remapping `text-scale` makes to scale the text). It also appears polymode has a variable for determing what variables to "transfer" between buffers: `polymode-move-these-vars-from-base-buffer` and `polymode-move-these-vars-from-old-buffer`.

To ensure the right state is propagated between the base and inner buffers, try this:

```elisp
(after! polymode
  (pushnew! polymode-move-these-vars-from-base-buffer
            'text-scale-mode-remapping
            'visual-fill-column-width
            'visual-fill-column-fringes-outside-margins
            'visual-fill-column-center-text
            'visual-fill-column-extra-text-width))
```

You may need to tweak the list of variables to find the right combination. In any case, I'll close this since this isn't a Doom issue, and since Doom doesn't use polymode anywhere, there's really no place to put them, but feel free to follow up here.

**Closed by hlissner** 2024-07-01 01:14 UTC
Labels: invalid
