### ISSUE TITLE
company doesn't show lsp code completion unless  `M-x lsp` manually

### ISSUE THREAD

**Issue by csyJoy** [doomemacs/doomemacs#7399] opened 2023-09-09 02:48 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

when I open a cpp file, lsp should auto-start and during the coding, the company plugin should give me  code completion from lsp

### Current behavior

when I open a cpp file, lsp seemes  auto-start but company plugin doesn't give me any code completion from lsp, this is the *Message* info, since I'm new to emacs and doom emacs, I can't find any useful about lsp or company plugin.
<img width="962" alt="image" src="https://github.com/doomemacs/doomemacs/assets/58020450/294e09d7-8ac9-42f9-887f-55e7cbaa68b1">

I really cann't find out which info is more important, so sorry for pasting whole doom/info in pastebin.

EDIT: when I use `M-x lsp` to launch lsp manually, emcas gives me following selection
![image](https://github.com/doomemacs/doomemacs/assets/58020450/e09bb172-a7bf-4781-9f21-91f6eedd5712)
If I choose `i`, company plugin can show the code completion from lsp correctly.

the major and minor modes before  and after `M-x lsp` are as follow:
<img width="1205" alt="image" src="https://github.com/doomemacs/doomemacs/assets/58020450/c894b0ba-9773-4e79-8e9d-377a25c61144">
the lsp-mode seems not included before `M-x lsp`
        
### Steps to reproduce

1. install doom emacs
2. doom install
3. uncomment (cc +lsp) in init.el and do doom sync
4. open a cpp file and do some coding

### System Information

https://pastebin.com/txXzZX1X

**Comment by hlissner** [comment] 2024-09-11 07:38
I can't reproduce this. `lsp-mode` is successfully started in `*.cpp` files, and both `clangd` and `ccls` are performing code completion for me. Either this was resolved at some point, or there was a startup error that went undetected (remember [to check \*Messages\*](https://discourse.doomemacs.org/t/how-to-debug-issues/55) for errors/warnings when things like this happen), so I'll close this, but feel free to follow up here if you're still experiencing this issue. Thanks for bringing it to my attention!

**Closed by hlissner** 2024-09-11 07:38 UTC
Labels: invalid

**Comment by Schievel1** [comment] 2025-07-03 06:13
I had the same problem, with LSP not starting automatically for .c files. 
In such a case it is a good idea imo to bisect the init.el by putting something like this in it
```
(with-current-buffer " *load*"
  (goto-char (point-max)))

```
Which will force emacs to return early from your config. Then restart emacs and if the problem still persists, you know it was caused by something above the point where you put your early return in. If its gone problem is below. 

For me it was 
```
(treesit-auto-install 'prompt)
```
which was causing this. I don't know why, but it does.
