### ISSUE TITLE
Error: (wrong-type-argument stringp (:app . calendar))

### ISSUE THREAD

**Issue by Schweber** [doomemacs/doomemacs#6372] opened 2022-05-05 18:44 UTC
### What did you expect to happen?

When running Doom Sync or Doom Upgrade or reinstalling Doom Emacs i expect it to complete without errors.

### What actually happened?

When running Doom Upgrade oder Doom Sync or reinstalling Doom Emacs it fails with the error message 

`Error: (wrong-type-argument stringp (:app . calendar))`

Please see attached error log

[doom.error.log](https://github.com/doomemacs/doomemacs/files/8633803/doom.error.log)

### Describe your attempts to resolve the issue

I deleted the .emacs.d folder and reinstalled Doom Emacs but the same error occurrs.

I am a completely novice user of Doom and Emacs. It might well be that this is my fault but i don't understand why it fails even when reinstalling Doom Emacs.

### Steps to reproduce

1. Run Doom Sync or Doom Upgrade or reinstall Doom Emacs after deleting the .emacs.d folder

### System Information

https://pastebin.com/yaCBnfDa

**Comment by hlissner** [comment] 2022-05-05 18:56
Duplicate of #6370

**Closed by hlissner** 2022-05-05 18:56 UTC
Labels: duplicate
