### ISSUE TITLE
doom sync Symbol's function definition is void: defcli!

### ISSUE THREAD

**Issue by andreaskundig** [doomemacs/doomemacs#6803] opened 2022-09-17 20:38 UTC
### What did you expect to happen?

running "doom" should return a help message 

### What actually happened?

On the git bash console
```
> doom 
Symbol's function definition is void: defcli!
```
But I run into the same problem with doom.cmd in cmd, or if i run ```emacs --quick --script .\doom -- sync```

### Describe your attempts to resolve the issue

The commit that breaks the issue is c05e6153. The previous commit works 3853dff5e11655e8. 

Yesterday's commit [811c18c](https://github.com/doomemacs/doomemacs/commit/811c18ca680d31b411ce395e0d28ab97816f177a) breaks doom in a different way 

```
> doom sync
Wrong type argument: stringp, nil
```

I traced it back to line 85 of the doom script. The load function isn't happy with these arguments
```
(load init-file nil 'nomessage)
```
The value of init-file is "c:/Users/andre/doom-emacs/early-init.el", which is a file that exists

I'm not sure if this other error should be a different issue

### Steps to reproduce

run doom on the command line

### System Information

https://pastebin.com/2CWYdarC

**Comment by hlissner** [comment] 2022-09-17 23:15
Duplicate of #6620. Please reply there.

Unfortunately, doom.cmd no longer works and will be removed soon. It likely will not be fixed until further down the road when I get around to writing a Windows install wizard or porcelain for the Doom CLI.

I'm open to PRs to port bin/doom's shebang launcher to doom.cmd though. For the time being the workaround is to install [Git Bash](https://www.git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-Bash) or WSL2 and use a unix terminal to interact with it.

**Closed by hlissner** 2022-09-17 23:15 UTC
Labels: duplicate
