### ISSUE TITLE
broken link in `README.md` under install tab

### ISSUE THREAD

**Issue by emadbaqeri** [doomemacs/doomemacs#6748] opened 2022-09-05 09:05 UTC
### What did you expect to happen?

I expected that while I'm clicking the link it will take me to a new page that is not broken

### What actually happened?

I'm redirecting to a page with [this link ](https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org) with the `404` error on the screen

### Steps to reproduce

Click the blue-colored text ([read our Getting Started guide](https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org))  to redirect to the page
<img width="956" alt="Screen Shot 2022-09-05 at 1 31 09 PM" src="https://user-images.githubusercontent.com/50639499/188411750-84eb0e82-1c13-4464-a9df-6f1e78620bf7.png">

### System Information

https://pastebin.com/

**Comment by elken** [comment] 2022-09-05 09:19
Duplicate of https://github.com/doomemacs/doomemacs/issues/6631

**Comment by edgar-vincent** [comment] 2022-09-05 09:23
And https://github.com/doomemacs/doomemacs/issues/6671.

**Closed** 2022-09-06 21:04 UTC
Labels: duplicate, is:docs
