### ISSUE TITLE
lsp install server func for zig need to update

### ISSUE THREAD

**Issue by Easedge** [doomemacs/doomemacs#7970] opened 2024-07-28 18:01 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

when i call func lsp-install-server and type zig language server zls,it should install zls in right way.

### Current behavior

when you install the zls,once it show you
```sh
LSP :: Download zls started.
LSP :: Starting to download https://github.com/zigtools/zls/releases/latest/download/zls-x86_64-linux.tar.gz to /home/junglefish/.config/emacs/.local/etc/lsp/zig/temp.tar.gz...
Contacting host: github.com:443
Wrote /home/junglefish/.config/emacs/.local/etc/lsp/zig/temp.tar.gz
LSP :: Finished downloading /home/junglefish/.config/emacs/.local/etc/lsp/zig/temp.tar.gz...
LSP :: Decompressing /home/junglefish/.config/emacs/.local/etc/lsp/zig/temp.tar.gz...
```
but now, project zls release zls-x86_64-linux.tar.xz for their things,so there is a bug about the download name

### Steps to reproduce

1.open emacs
2.open any .zig file
3.M-x lsp-install-server and type zls
4.C-h e open *Message* buffer
5.open ~/.config/emacs/.local/etc/lsp/zig folder
6.Now you will found that temp.tar.gz file only had 9 bytes

### System Information

https://pastebin.com/F8jc7Hfe

**Comment by hlissner** [comment] 2024-07-28 19:15
Duplicate of #7873.

Already fixed in https://github.com/doomemacs/doomemacs/blob/1e8e98b099607f2f7b253ef05235e042f594c2a1/modules/tools/lsp/+lsp.el#L60-L61.

**Closed** 2024-07-28 19:21 UTC
Labels: is:bug, module:lang/zig

**Comment by hlissner** [comment] 2024-07-28 19:22
My bad. Seems like the fix from 7bb5df4cd4ae3a0916616dd7e50566b3caa9c931 would not take effect until `zig-mode` is loaded (i.e. you've loaded at least one zig file before trying to install ZLS via `M-x lsp-install-server`). If it isn't loaded, the old, broken URL would be used. As of bc5a8ec this should be properly fixed. Thanks for bringing it to my attention!

**Comment by Easedge** [comment] 2024-07-29 16:06
i upgrade doom form old version to 3.0.0-pre PROFILE=_@0 HEAD -> master 0f30e1ec 2024-07-29 02:03:25
and i try open an zig file or not open an zig file, in *Message* buffer i always check this below
```bash
# ../../usr/share/emacs/site-lisp/site-start.d/clang-include-fixer.el: Warning: Unknown type: buffer-live
# Doom loaded 338 packages across 66 modules in 0.908s
# Package cl is deprecated
# Loading /home/junglefish/.config/emacs/.local/straight/build-29.4/evil-pinyin/simplified-quanpin-all...done
LSP :: Download zls started.
LSP :: Starting to download https://github.com/zigtools/zls/releases/latest/download/zls-x86_64-linux.tar.gz to /home/junglefish/.config/emacs/.local/etc/lsp/zig/temp.tar.gz...
Contacting host: github.com:443
Wrote /home/junglefish/.config/emacs/.local/etc/lsp/zig/temp.tar.gz
LSP :: Finished downloading /home/junglefish/.config/emacs/.local/etc/lsp/zig/temp.tar.gz...
LSP :: Decompressing /home/junglefish/.config/emacs/.local/etc/lsp/zig/temp.tar.gz...
tar: It does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
LSP :: Decompressed /home/junglefish/.config/emacs/.local/etc/lsp/zig/temp...
LSP :: Server zls downloaded, auto-starting in 0 buffers.
Beginning of buffer [4 times]
```
ignore the top 4 rows irrelevant error messages,it looks like fix is not work in this checkout

**Comment by hlissner** [comment] 2024-07-30 04:44
See if 93dfb0a fixes your issue. Seems `lsp-zig-download-url-format` needs to be set before `lsp-zig` loads.

**Comment by hlissner** [comment] 2024-07-30 04:52
Alright, 85b7b61 should hopefully fix this, finally. Fingers crossed they resolve this upstream soon.

**Comment by Easedge** [comment] 2024-07-30 15:40
i upgrade again, now it will get the right link,but after installed the zls, it will pop up install-lsp-server minibuffer always.

**Comment by Easedge** [comment] 2024-08-01 09:23
> Alright, 85b7b61 should hopefully fix this, finally. Fingers crossed they resolve this upstream soon.
There is a little problem after this fix. Problem is written above this reply.
