### ISSUE TITLE
xref-find-* takes me to init.29.el not the proper definition

### ISSUE THREAD

**Issue by pcompassion** [doomemacs/doomemacs#7449] opened 2023-09-21 07:51 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

when i do `xref-find-definitions` on `org-agenda`

I expect it to take me to org.el file where it's defined. 
(other symbols have the same problem, but not all )

### Current behavior

when i do `xref-find-definitions` on `org-agenda`

But it's opening up `init.29.el`

### Steps to reproduce

go to any *.el file

type `org-agenda` and do M-. on it (xref-find-definitions)

I commented out my config.el 
and did doom upgrade, to test it.

### System Information

https://gist.github.com/pcompassion/7d3009dc1549800b7df785e25950d8dd

**Comment by jkroes** [comment] 2024-09-01 02:20
Confirming that this is an issue for me as well.

**Comment by hlissner** [comment] 2024-09-01 02:26
@jkroes This should've been fixed in https://github.com/doomemacs/doomemacs/commit/7197ee65c7cd1a8291266a3514583406e1ab1f18.

**Comment by jkroes** [comment] 2024-09-03 02:47
@hlissner It appears to be fixed now.

**Comment by hlissner** [comment] 2024-09-03 03:28
Thanks for letting me know.

I'll close this as a duplicate of #7958.

**Closed by hlissner** 2024-09-03 03:28 UTC
Labels: duplicate
