### ISSUE TITLE
Cannot load or install doom - "Unknown specializer record"

### ISSUE THREAD

**Issue by dpbriggs** [doomemacs/doomemacs#8187] opened 2024-12-01 17:28 UTC
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Install or load doom, it should load without an "Unknown specializer record" error.

### Current behavior

When I load or freshly install doom, it fails to load with the following error message:

```
➜  ~ rm -rf ~/.config/emacs
➜  ~ git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
~/.config/emacs/bin/doom install
Cloning into '/home/david/.config/emacs'...
remote: Enumerating objects: 1160, done.
remote: Counting objects: 100% (1160/1160), done.
remote: Compressing objects: 100% (1061/1061), done.
remote: Total 1160 (delta 81), reused 598 (delta 56), pack-reused 0 (from 0)
Receiving objects: 100% (1160/1160), 1.18 MiB | 10.43 MiB/s, done.
Resolving deltas: 100% (81/81), done.

Error: error ("Unknown specializer record")
  mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode 0x1e2b2f7347ae834a>))
  debug-early-backtrace()
  debug-early(error (error "Unknown specializer record"))
  error("Unknown specializer %S" record)
  #f(compiled-function (specializer) "Support for the catch-all t specializer which always matches." #<bytecode 0x926009d1321714b>)(record)
  apply(#f(compiled-function (specializer) "Support for the catch-all t specializer which always matches." #<bytecode 0x926009d1321714b>) record)
  #f(compiled-function (&rest args) #<bytecode -0x151124525cb4ef05>)()
  #f(compiled-function (cl--cnm specializer) #<bytecode 0x178c9c17caf63729>)(#f(compiled-function (&rest args) #<bytecode -0x151124525cb4ef05>) record)
  apply(#f(compiled-function (cl--cnm specializer) #<bytecode 0x178c9c17caf63729>) #f(compiled-function (&rest args) #<bytecode -0x151124525cb4ef05>) record)
  #f(compiled-function (specializer) "Support for (head VAL) specializers.\nThese match if the argument is a cons cell whose car is `eql' to VAL." #<bytecode -0x1b69c7bc8e477160>)(record)
  apply(#f(compiled-function (specializer) "Support for (head VAL) specializers.\nThese match if the argument is a cons cell whose car is `eql' to VAL." #<bytecode -0x1b69c7bc8e477160>) record)
  #f(compiled-function (&rest args) #<bytecode -0x17e28ff245c4d9e1>)()
  #f(compiled-function (cl--cnm type) #<bytecode -0x1d1e48116637d0d9>)(#f(compiled-function (&rest args) #<bytecode -0x17e28ff245c4d9e1>) record)
  apply(#f(compiled-function (cl--cnm type) #<bytecode -0x1d1e48116637d0d9>) #f(compiled-function (&rest args) #<bytecode -0x17e28ff245c4d9e1>) record)
  #f(compiled-function (type) "Support for dispatch on types defined by `cl-defstruct'." #<bytecode -0x11d25a16263134ea>)(record)
  apply(#f(compiled-function (type) "Support for dispatch on types defined by `cl-defstruct'." #<bytecode -0x11d25a16263134ea>) record)
  #f(compiled-function (&rest args) #<bytecode 0x174e9d7c1386afe3>)()
  #f(compiled-function (cl--cnm type) #<bytecode -0x13a7539f455c5162>)(#f(compiled-function (&rest args) #<bytecode 0x174e9d7c1386afe3>) record)
  apply(#f(compiled-function (cl--cnm type) #<bytecode -0x13a7539f455c5162>) #f(compiled-function (&rest args) #<bytecode 0x174e9d7c1386afe3>) record)
  #f(compiled-function (type) "Support for dispatch on builtin types.\nSee the full list and their hierarchy in `cl--typeof-types'." #<bytecode -0x14ed3acf3d2ae082>)(record)
  apply(#f(compiled-function (type) "Support for dispatch on builtin types.\nSee the full list and their hierarchy in `cl--typeof-types'." #<bytecode -0x14ed3acf3d2ae082>) record)
  #f(compiled-function (&rest args) #<bytecode -0xcd006b2059560d2>)()
  #f(compiled-function (cl--cnm type) #<bytecode -0x3b5c717a5db0666>)(#f(compiled-function (&rest args) #<bytecode -0xcd006b2059560d2>) record)
  apply(#f(compiled-function (cl--cnm type) #<bytecode -0x3b5c717a5db0666>) #f(compiled-function (&rest args) #<bytecode -0xcd006b2059560d2>) record)
  #f(compiled-function (type) "Support for dispatch on types defined by `oclosure-define'." #<bytecode 0x1a773825f7e1f4f0>)(record)
  apply(#f(compiled-function (type) "Support for dispatch on types defined by `oclosure-define'." #<bytecode 0x1a773825f7e1f4f0>) record nil)
  cl-generic-generalizers(record)
  cl-generic-define-method(doom-copy nil ((val record) &optional deep?) nil (closure (t) (val &optional deep?) "Return a (optionally deep) copy of record VAL." (progn (if deep? (let* ((newval (copy-sequence val)) (idx 1) (--cl-var-- (length (cdr (cl-struct-slot-info (type-of val)))))) (while (<= idx --cl-var--) (aset newval idx (doom-copy (aref newval idx) t)) (setq idx (+ idx 1))) newval) (copy-sequence val)))))
  load-with-code-conversion("/home/david/.config/emacs/lisp/doom-lib.el" "/home/david/.config/emacs/lisp/doom-lib.el" nil t)
  require(doom-lib)
  load-with-code-conversion("/home/david/.config/emacs/lisp/doom.el" "/home/david/.config/emacs/lisp/doom.el" nil t)
  load("/home/david/.config/emacs/lisp/doom" nil t nil must-suffix)
  (if (file-exists-p (concat doom ".el")) (load doom nil (not init-file-debug) nil 'must-suffix) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list #'(lambda nil (expand-file-name "init.el" user-emacs-directory)) nil (nth 2 args)))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil)
  (let ((load-suffixes '(".elc" ".el")) (doom (expand-file-name "lisp/doom" user-emacs-directory))) (if (file-exists-p (concat doom ".el")) (load doom nil (not init-file-debug) nil 'must-suffix) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list #'(lambda nil (expand-file-name "init.el" user-emacs-directory)) nil (nth 2 args)))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil))
  (if (let ((load-suffixes '(".elc" ".el")) (doom (expand-file-name "lisp/doom" user-emacs-directory))) (if (file-exists-p (concat doom ".el")) (load doom nil (not init-file-debug) nil 'must-suffix) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list #'(lambda nil (expand-file-name "init.el" user-emacs-directory)) nil (nth 2 args)))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil)) (doom-initialize (not noninteractive)) (load user-init-file 'noerror (not init-file-debug) nil 'must-suffix))
  (let (file-name-handler-alist) (if noninteractive (progn (setq gc-cons-threshold 134217728) (setq gc-cons-percentage 1.0)) (setq gc-cons-threshold most-positive-fixnum)) (setq load-prefer-newer noninteractive) (if (getenv-internal "DEBUG") (progn (progn (setq init-file-debug t) (setq debug-on-error t)))) (let ((command-line-args (if noninteractive nil command-line-args)) (profile (or (car (cdr (member "--profile" command-line-args))) (getenv-internal "DOOMPROFILE")))) (if (null profile) (let ((init-dir (or (car (cdr (member "--init-directory" command-line-args))) (getenv-internal "EMACSDIR")))) (if (null init-dir) (if noninteractive (progn (setq user-emacs-directory (file-name-directory (file-truename load-file-name))))) (setq command-switch-alist (cons (cons "--init-directory" #'(lambda (_) (car-safe (prog1 argv (setq argv (cdr argv)))))) command-switch-alist)) (setq user-emacs-directory (expand-file-name init-dir)))) (setq command-switch-alist (cons (cons "--profile" #'(lambda (_) (car-safe (prog1 argv (setq argv (cdr argv)))))) command-switch-alist)) (setenv "DOOMPROFILE" profile) (or (load (let ((windows? (memq system-type '(ms-dos windows-nt cygwin)))) (expand-file-name (format (or (getenv-internal "DOOMPROFILELOADFILE") (file-name-concat (if windows? "doomemacs/data" "doom") "profiles.%d")) emacs-major-version) (or (if windows? (getenv-internal "LOCALAPPDATA")) (getenv-internal "XDG_DATA_HOME") "~/.local/share"))) 'noerror (not init-file-debug)) (user-error "Profiles not initialized yet; run 'doom sync' first")))) (if (let ((load-suffixes '(".elc" ".el")) (doom (expand-file-name "lisp/doom" user-emacs-directory))) (if (file-exists-p (concat doom ".el")) (load doom nil (not init-file-debug) nil 'must-suffix) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list #'(lambda nil (expand-file-name "init.el" user-emacs-directory)) nil (nth 2 args)))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil)) (doom-initialize (not noninteractive)) (load user-init-file 'noerror (not init-file-debug) nil 'must-suffix)))
  load-with-code-conversion("/home/david/.config/emacs/early-init.el" "/home/david/.config/emacs/early-init.el" nil t)
  load("/home/david/.config/emacs/early-init.el" nil nomessage nosuffix)
  (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom))
  (or (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file))
  (let* ((bin-dir (file-name-directory (file-truename load-file-name))) (init-file (expand-file-name "../early-init.el" bin-dir))) (or (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file)))
  (condition-case e (let* ((bin-dir (file-name-directory (file-truename load-file-name))) (init-file (expand-file-name "../early-init.el" bin-dir))) (or (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file))) (user-error (message "Error: %s" (car (cdr e))) (kill-emacs 2)))
  load-with-code-conversion("/home/david/.config/emacs/bin/doom" "/home/david/.config/emacs/bin/doom" nil t)
  command-line-1(("--load" "/home/david/.config/emacs/bin/doom" "--" "install"))
  command-line()
  normal-top-level()
Unknown specializer record
```

Similarly with `--debug-init`:

```
➜  emacs git:(master) emacs --debug-init
Loading /home/david/.config/emacs/lisp/doom.el (source)...
Debugger entered--Lisp error: (error "Unknown specializer record")
  error("Unknown specializer %S" record)
  #f(compiled-function (specializer) "Support for the catch-all t specializer which always matches." #<bytecode -0xac208a21cde8eb8>)(record)
  apply(#f(compiled-function (specializer) "Support for the catch-all t specializer which always matches." #<bytecode -0xac208a21cde8eb8>) record)
  #f(compiled-function (&rest args) #<bytecode -0x151124525cb4ef05>)()
  #f(compiled-function (cl--cnm specializer) #<bytecode -0x1fa879954854c8e5>)(#f(compiled-function (&rest args) #<bytecode -0x151124525cb4ef05>) record)
  apply(#f(compiled-function (cl--cnm specializer) #<bytecode -0x1fa879954854c8e5>) #f(compiled-function (&rest args) #<bytecode -0x151124525cb4ef05>) record)
  #f(compiled-function (specializer) "Support for (head VAL) specializers.\nThese match if the argument is a cons cell whose car is `eql' to VAL." #<bytecode -0x1ca6b1cf1e477160>)(record)
  apply(#f(compiled-function (specializer) "Support for (head VAL) specializers.\nThese match if the argument is a cons cell whose car is `eql' to VAL." #<bytecode -0x1ca6b1cf1e477160>) record)
  #f(compiled-function (&rest args) #<bytecode -0x17e28ff245c4d9e1>)()
  #f(compiled-function (cl--cnm type) #<bytecode 0x183dc9a895052bae>)(#f(compiled-function (&rest args) #<bytecode -0x17e28ff245c4d9e1>) record)
  apply(#f(compiled-function (cl--cnm type) #<bytecode 0x183dc9a895052bae>) #f(compiled-function (&rest args) #<bytecode -0x17e28ff245c4d9e1>) record)
  #f(compiled-function (type) "Support for dispatch on types defined by `cl-defstruct'." #<bytecode 0x1d28cb37a9cecb15>)(record)
  apply(#f(compiled-function (type) "Support for dispatch on types defined by `cl-defstruct'." #<bytecode 0x1d28cb37a9cecb15>) record)
  #f(compiled-function (&rest args) #<bytecode 0x174e9d7c1386afe3>)()
  #f(compiled-function (cl--cnm type) #<bytecode -0x134a8622ad615162>)(#f(compiled-function (&rest args) #<bytecode 0x174e9d7c1386afe3>) record)
  apply(#f(compiled-function (cl--cnm type) #<bytecode -0x134a8622ad615162>) #f(compiled-function (&rest args) #<bytecode 0x174e9d7c1386afe3>) record)
  #f(compiled-function (type) "Support for dispatch on builtin types.\nSee the full list and their hierarchy in `cl--typeof-types'." #<bytecode 0x173b24de92d51f7d>)(record)
  apply(#f(compiled-function (type) "Support for dispatch on builtin types.\nSee the full list and their hierarchy in `cl--typeof-types'." #<bytecode 0x173b24de92d51f7d>) record)
  #f(compiled-function (&rest args) #<bytecode -0xcd006b2059560d2>)()
  #f(compiled-function (cl--cnm type) #<bytecode 0x1d3d963bfdc5f99a>)(#f(compiled-function (&rest args) #<bytecode -0xcd006b2059560d2>) record)
  apply(#f(compiled-function (cl--cnm type) #<bytecode 0x1d3d963bfdc5f99a>) #f(compiled-function (&rest args) #<bytecode -0xcd006b2059560d2>) record)
  #f(compiled-function (type) "Support for dispatch on types defined by `oclosure-define'." #<bytecode 0x1776a76027e1f4f0>)(record)
  apply(#f(compiled-function (type) "Support for dispatch on types defined by `oclosure-define'." #<bytecode 0x1776a76027e1f4f0>) record nil)
  cl-generic-generalizers(record)
  cl-generic-define-method(doom-copy nil ((val record) &optional deep?) nil (closure (t) (val &optional deep?) "Return a (optionally deep) copy of record VAL." (progn (if deep? (let* ((newval (copy-sequence val)) (idx 1) (--cl-var-- (length ...))) (while (<= idx --cl-var--) (aset newval idx (doom-copy ... t)) (setq idx (+ idx 1))) newval) (copy-sequence val)))))
  load-with-code-conversion("/home/david/.config/emacs/lisp/doom-lib.el" "/home/david/.config/emacs/lisp/doom-lib.el" nil t)
  require(doom-lib)
  load-with-code-conversion("/home/david/.config/emacs/lisp/doom.el" "/home/david/.config/emacs/lisp/doom.el" nil nil)
  load("/home/david/.config/emacs/lisp/doom" nil nil nil must-suffix)
  (if (file-exists-p (concat doom ".el")) (load doom nil (not init-file-debug) nil 'must-suffix) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list #'(lambda nil ...) nil (nth 2 args)))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil)
  (let ((load-suffixes '(".elc" ".el")) (doom (expand-file-name "lisp/doom" user-emacs-directory))) (if (file-exists-p (concat doom ".el")) (load doom nil (not init-file-debug) nil 'must-suffix) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list #'... nil (nth 2 args)))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil))
  (if (let ((load-suffixes '(".elc" ".el")) (doom (expand-file-name "lisp/doom" user-emacs-directory))) (if (file-exists-p (concat doom ".el")) (load doom nil (not init-file-debug) nil 'must-suffix) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list ... nil ...))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil)) (doom-initialize (not noninteractive)) (load user-init-file 'noerror (not init-file-debug) nil 'must-suffix))
  (let (file-name-handler-alist) (if noninteractive (progn (setq gc-cons-threshold 134217728) (setq gc-cons-percentage 1.0)) (setq gc-cons-threshold most-positive-fixnum)) (setq load-prefer-newer noninteractive) (if (getenv-internal "DEBUG") (progn (progn (setq init-file-debug t) (setq debug-on-error t)))) (let ((command-line-args (if noninteractive nil command-line-args)) (profile (or (car (cdr (member "--profile" command-line-args))) (getenv-internal "DOOMPROFILE")))) (if (null profile) (let ((init-dir (or (car ...) (getenv-internal "EMACSDIR")))) (if (null init-dir) (if noninteractive (progn (setq user-emacs-directory ...))) (setq command-switch-alist (cons (cons "--init-directory" ...) command-switch-alist)) (setq user-emacs-directory (expand-file-name init-dir)))) (setq command-switch-alist (cons (cons "--profile" #'(lambda ... ...)) command-switch-alist)) (setenv "DOOMPROFILE" profile) (or (load (let ((windows? ...)) (expand-file-name (format ... emacs-major-version) (or ... ... "~/.local/share"))) 'noerror (not init-file-debug)) (user-error "Profiles not initialized yet; run 'doom sync' firs...")))) (if (let ((load-suffixes '(".elc" ".el")) (doom (expand-file-name "lisp/doom" user-emacs-directory))) (if (file-exists-p (concat doom ".el")) (load doom nil (not init-file-debug) nil 'must-suffix) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda ... ...)) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil)) (doom-initialize (not noninteractive)) (load user-init-file 'noerror (not init-file-debug) nil 'must-suffix)))
  load-with-code-conversion("/home/david/.config/emacs/early-init.el" "/home/david/.config/emacs/early-init.el" t t)
  load("/home/david/.config/emacs/early-init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0xf048adfe35362f5>))
  command-line()
  normal-top-level()
```

All of the provided arch emacs packages (emacs, emacs-nativecomp, etc) demonstrate the same behaviour. It may be an issue on the arch side?

### Steps to reproduce

1. Open emacs or run `doom install` 

### System Information

https://gist.github.com/dpbriggs/2be84f0279a36b15f386cf0ac46994d3

**Comment by hlissner** [comment] 2024-12-01 20:00
Duplicate of #8186

**Closed by hlissner** 2024-12-01 20:00 UTC
Labels: duplicate
