### ISSUE TITLE
Slow js/ts file open

### ISSUE THREAD

**Issue by quolpr** [doomemacs/doomemacs#6879] opened 2022-10-07 16:48 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I expect js/ts files to open instantly

### Current behavior

Right now I wait 0.2s...1s file to open

### Steps to reproduce

Open any .ts file. I used https://github.com/kikko-land/kikko repo. It takes around 200ms to open file. At spacemacs it happens instantly(even with lsp enabled).

On larger repos the open delays is almost the same os slightly bigger.

Here is profiler report:
```
                                                                          6  18% - apply
                                                                          3   9%  - flycheck-call-checker-process
                                                                          3   9%   - flycheck-eslint-config-exists-p
                                                                          3   9%    - #<compiled 0x1f40d6c7ad09>
                                                                          3   9%     - #<compiled -0x1d03eb4ca5fae4bc>
                                                                          3   9%      - #<compiled 0x1f38c0a8d2d36a97>
                                                                          3   9%       - flycheck-may-enable-checker
                                                                          3   9%        - flycheck-may-use-checker
                                                                          3   9%         - flycheck-may-use-next-checker
                                                                          3   9%          - #<compiled -0x747080b9c20755a>
                                                                          3   9%           - mapc
                                                                          3   9%            - seq-do
                                                                          3   9%             - seq-find
                                                                          3   9%              - flycheck-get-next-checker-for-buffer
                                                                          3   9%               - flycheck-finish-current-syntax-check
                                                                          3   9%                  flycheck-report-buffer-checker-status
                                                                          2   6%  - process-file
                                                                          2   6%   - apply
                                                                          2   6%    - vc-git--call
                                                                          2   6%     - apply
                                                                          2   6%      - vc-git--out-ok
                                                                          1   3%       - vc-git-registered
                                                                          1   3%        - apply
                                                                          1   3%         - vc-call-backend
                                                                          1   3%          - #<compiled 0xc985718663aa004>
                                                                          1   3%           - mapc
                                                                          1   3%            - vc-registered
                                                                          1   3%             - vc-backend
                                                                          1   3%              - and
                                                                          1   3%               - not
                                                                          1   3%                  cond
                                                                          1   3%       - vc-git--rev-parse
                                                                          1   3%        - vc-git-working-revision
                                                                          1   3%         - apply
                                                                          1   3%          - vc-call-backend
                                                                          1   3%           - vc-working-revision
                                                                          1   3%            - vc-git-mode-line-string
                                                                          1   3%             - apply
                                                                          1   3%              - vc-call-backend
                                                                          1   3%               - vc-mode-line
                                                                          1   3%                  #<compiled -0x1d29ef434dcc7fc5>
                                                                          1   3%  - make-process--with-editor-process-filter
                                                                          1   3%   - apply
                                                                          1   3%    - make-process
                                                                          1   3%     - apply
                                                                          1   3%      - start-process
                                                                          1   3%       - apply
                                                                          1   3%        - #<compiled -0x18e416da81d10652>
                                                                          1   3%         - apply
                                                                          1   3%          - start-file-process--with-editor-process-filter
                                                                          1   3%           - apply
                                                                          1   3%            - start-file-process
                                                                          1   3%             - apply
                                                                          1   3%              - git-gutter:start-git-diff-process
                                                                          1   3%               - git-gutter:start-diff-process1
                                                                          1   3%                  git-gutter:start-diff-process
                                                                          5  15% - file-truename
                                                                          2   6%  - #<compiled 0x16b4cfff526ec69f>
                                                                          2   6%   - cl-some
                                                                          2   6%    - projectile-project-root
                                                                          1   3%     - projectile-project-p
                                                                          1   3%      - projectile-cache-files-find-file-hook
                                                                          1   3%       - projectile-find-file-hook-function
                                                                          1   3%        - run-hooks
                                                                          1   3%         - #<compiled 0x175ab4d497617b18>
                                                                          1   3%          - apply
                                                                          1   3%           - progn
                                                                          1   3%            - unwind-protect
                                                                          1   3%             - let*
                                                                          1   3%              - doom--shut-up-autosave-a
                                                                          1   3%               - apply
                                                                          1   3%                  #<compiled -0x2b65c46f2ef5edf>
                                                                          1   3%     - doom-modeline--project-root
                                                                          1   3%      - doom-modeline-project-root
                                                                          1   3%       - doom-modeline--buffer-file-name
                                                                          1   3%        - doom-modeline-buffer-file-name
                                                                          1   3%         - doom-modeline-update-buffer-file-name
                                                                          1   3%          - run-hooks
                                                                          1   3%           - #<compiled 0x175ab4d497617b18>
                                                                          1   3%            - apply
                                                                          1   3%             - progn
                                                                          1   3%              - unwind-protect
                                                                          1   3%               - let*
                                                                          1   3%                  doom--shut-up-autosave-a
                                                                          2   6%  - file-truename
                                                                          1   3%   - mapcar
                                                                          1   3%    - projectile-ignored-projects
                                                                          1   3%     - projectile-ignored-project-p
                                                                          1   3%      - projectile-add-known-project
                                                                          1   3%       - projectile-track-known-projects-find-file-hook
                                                                          1   3%        - projectile-find-file-hook-function
                                                                          1   3%         - run-hooks
                                                                          1   3%          - #<compiled 0x175ab4d497617b18>
                                                                          1   3%           - apply
                                                                          1   3%            - progn
                                                                          1   3%             - unwind-protect
                                                                          1   3%              - let*
                                                                          1   3%               - doom--shut-up-autosave-a
                                                                          1   3%                  apply
                                                                          1   3%   - file-truename
                                                                          1   3%    - file-truename
                                                                          1   3%     - file-equal-p
                                                                          1   3%      - tide-flycheck-predicate
                                                                          1   3%       - #<compiled 0x1bb359a18e9263ea>
                                                                          1   3%        - flycheck-may-use-checker
                                                                          1   3%         - #<compiled -0x747080b9c68b55a>
                                                                          1   3%          - mapc
                                                                          1   3%           - seq-do
                                                                          1   3%            - seq-find
                                                                          1   3%             - flycheck-get-checker-for-buffer
                                                                          1   3%              - flycheck-buffer
                                                                          1   3%               - flycheck-buffer-automatically
                                                                          1   3%                  flycheck-perform-deferred-syntax-check
                                                                          1   3%  - find-file-noselect-1
                                                                          1   3%   - find-file-noselect
                                                                          1   3%    - find-file
                                                                          1   3%     - dired--find-file
                                                                          1   3%      - dired--find-possibly-alternative-file
                                                                          1   3%       - dired-find-file
                                                                          1   3%        - funcall-interactively
                                                                          1   3%         - call-interactively
                                                                          1   3%            command-execute
                                                                          2   6% - eval-buffer
                                                                          2   6%  - load-with-code-conversion
                                                                          1   3%   - +snippets-enable-project-modes-h
                                                                          1   3%    - run-hook-with-args
                                                                          1   3%     - if
                                                                          1   3%      - let
                                                                          1   3%       - +javascript-npm-mode
                                                                          1   3%        - and
                                                                          1   3%         - doom--enable-+javascript-npm-mode-in-typescript-mode-h
                                                                          1   3%          - run-hooks
                                                                          1   3%           - apply
                                                                          1   3%            - run-mode-hooks
                                                                          1   3%             - typescript-mode
                                                                          1   3%              - set-auto-mode-0
                                                                          1   3%               - set-auto-mode--apply-alist
                                                                          1   3%                  #<compiled 0xc44c643198ae31f>
                                                                          1   3%   - +emacs-lisp-non-package-mode
                                                                          1   3%    - run-hooks
                                                                          1   3%     - flycheck-mode
                                                                          1   3%      - flycheck-mode-on-safe
                                                                          1   3%       - global-flycheck-mode-enable-in-buffers
                                                                          1   3%        - run-hooks
                                                                          1   3%         - run-mode-hooks
                                                                          1   3%          - typescript-mode
                                                                          1   3%           - set-auto-mode-0
                                                                          1   3%            - set-auto-mode--apply-alist
                                                                          1   3%             - #<compiled 0xc44c643198ae31f>
                                                                          1   3%              - apply
                                                                          1   3%               - so-long--set-auto-mode
                                                                          1   3%                  apply
                                                                          2   6% - font-lock-fontify-keywords-region
                                                                          2   6%  - font-lock-default-fontify-region
                                                                          2   6%   - font-lock-fontify-region
                                                                          2   6%    - #<compiled 0x19d0e75a13febd3d>
                                                                          2   6%     - run-hook-wrapped
                                                                          2   6%      - jit-lock--run-functions
                                                                          2   6%       - jit-lock-fontify-now
                                                                          2   6%        - jit-lock-function
                                                                          2   6%         - vertical-motion
                                                                          2   6%          - beginning-of-visual-line
                                                                          2   6%           - nav-flash-show
                                                                          2   6%            - if
                                                                          2   6%             - +nav-flash-blink-cursor
                                                                          2   6%              - if
                                                                          2   6%               - +nav-flash-blink-cursor-a
                                                                          2   6%                  apply
                                                                          2   6% + profiler-stop
                                                                          1   3% + #<compiled 0x12cd0f470e7c6c0e>
                                                                          1   3% - find-file-noselect
                                                                          1   3%  - find-file
                                                                          1   3%   - dired--find-file
                                                                          1   3%    - dired--find-possibly-alternative-file
                                                                          1   3%     - dired-find-file
                                                                          1   3%      - funcall-interactively
                                                                          1   3%       - call-interactively
                                                                          1   3%          command-execute
                                                                          1   3% - alist-get
                                                                          1   3%  - #<compiled -0x6149d30c6ad39b2>
                                                                          1   3%   - sort
                                                                          1   3%    - add-hook
                                                                          1   3%     - company-mode
                                                                          1   3%      - company-mode-on
                                                                          1   3%       - global-company-mode-enable-in-buffers
                                                                          1   3%        - run-hooks
                                                                          1   3%         - normal-mode
                                                                          1   3%          - #<compiled 0x175ab4d497617b18>
                                                                          1   3%           - apply
                                                                          1   3%            - progn
                                                                          1   3%             - unwind-protect
                                                                          1   3%              - let*
                                                                          1   3%               - doom--shut-up-autosave-a
                                                                          1   3%                  apply
                                                                          1   3% - abbreviate-file-name
                                                                          1   3%  - locate-dominating-file
                                                                          1   3%   - dir-locals-find-file
                                                                          1   3%    - hack-dir-local--get-variables
                                                                          1   3%     - #<compiled 0xc44c643198ae31f>
                                                                          1   3%      - apply
                                                                          1   3%       - so-long--set-auto-mode
                                                                          1   3%        - apply
                                                                          1   3%         - #<compiled 0x1de8154dba8d6760>
                                                                          1   3%          - apply
                                                                          1   3%           - set-auto-mode
                                                                          1   3%            - normal-mode
                                                                          1   3%             - #<compiled 0x175ab4d497617b18>
                                                                          1   3%              - apply
                                                                          1   3%               - progn
                                                                          1   3%                  unwind-protect
                                                                          1   3% - typescript--maybe-join
                                                                          1   3%  - typescript--update-quick-match-re
                                                                          1   3%   - typescript-mode
                                                                          1   3%    - set-auto-mode-0
                                                                          1   3%     - set-auto-mode--apply-alist
                                                                          1   3%      - #<compiled 0xc44c643198ae31f>
                                                                          1   3%       - apply
                                                                          1   3%        - so-long--set-auto-mode
                                                                          1   3%         - apply
                                                                          1   3%          - #<compiled 0x1de8154dba8d6760>
                                                                          1   3%           - apply
                                                                          1   3%            - set-auto-mode
                                                                          1   3%             - normal-mode
                                                                          1   3%              - #<compiled 0x175ab4d497617b18>
                                                                          1   3%               - apply
                                                                          1   3%                  progn
                                                                          1   3% - vi-tilde-fringe-mode
                                                                          1   3%  - run-hooks
                                                                          1   3%   - apply
                                                                          1   3%    - run-mode-hooks
                                                                          1   3%     - typescript-mode
                                                                          1   3%      - set-auto-mode-0
                                                                          1   3%       - set-auto-mode--apply-alist
                                                                          1   3%        - #<compiled 0xc44c643198ae31f>
                                                                          1   3%         - apply
                                                                          1   3%          - so-long--set-auto-mode
                                                                          1   3%           - apply
                                                                          1   3%            - #<compiled 0x1de8154dba8d6760>
                                                                          1   3%             - apply
                                                                          1   3%              - set-auto-mode
                                                                          1   3%               - normal-mode
                                                                          1   3%                  #<compiled 0x175ab4d497617b18>
                                                                          1   3% - macroexpand
                                                                          1   3%  - macroexp-macroexpand
                                                                          1   3%   - macroexp--expand-all
                                                                          1   3%    - macroexp--all-forms
                                                                          1   3%     - #<compiled -0x13dd96da0b56edc7>
                                                                          1   3%      - macroexp--expand-all
                                                                          1   3%       - macroexp--all-forms
                                                                          1   3%        - macroexp--expand-all
                                                                          1   3%         - macroexp--all-forms
                                                                          1   3%          - #<compiled -0x13dd96da0b56edc7>
                                                                          1   3%           - macroexp--expand-all
                                                                          1   3%            - macroexp--all-forms
                                                                          1   3%             - #<compiled -0x13dd96da0b56edc7>
                                                                          1   3%              - macroexp--expand-all
                                                                          1   3%               - macroexp--all-forms
                                                                          1   3%                  macroexp--expand-all
                                                                          1   3% - #<compiled -0x13dd96da0b56edc7>
                                                                          1   3%  - macroexp--expand-all
                                                                          1   3%   - macroexp--all-forms
                                                                          1   3%    - #<compiled -0x13dd96da0b56edc7>
                                                                          1   3%     - macroexp--expand-all
                                                                          1   3%      - macroexp--all-forms
                                                                          1   3%       - macroexp--expand-all
                                                                          1   3%        - macroexp--all-forms
                                                                          1   3%         - macroexp--expand-all
                                                                          1   3%          - macroexp--all-forms
                                                                          1   3%           - #<compiled -0x13dd96da0b56edc7>
                                                                          1   3%            - macroexp--expand-all
                                                                          1   3%             - macroexpand-all
                                                                          1   3%              - internal-macroexpand-for-load
                                                                          1   3%               - eval-buffer
                                                                          1   3%                  load-with-code-conversion
                                                                          1   3% - mapc
                                                                          1   3%  - yas--modes-to-activate
                                                                          1   3%   - yas--load-pending-jits
                                                                          1   3%    - yas-activate-extra-mode
                                                                          1   3%     - if
                                                                          1   3%      - +snippets-enable-project-modes-h
                                                                          1   3%       - run-hook-with-args
                                                                          1   3%        - if
                                                                          1   3%         - let
                                                                          1   3%          - +javascript-npm-mode
                                                                          1   3%           - and
                                                                          1   3%            - doom--enable-+javascript-npm-mode-in-typescript-mode-h
                                                                          1   3%             - run-hooks
                                                                          1   3%              - apply
                                                                          1   3%               - run-mode-hooks
                                                                          1   3%                  typescript-mode
                                                                          1   3% - locate-file
                                                                          1   3%  - executable-find
                                                                          1   3%   - if
                                                                          1   3%    - or
                                                                          1   3%     - if
                                                                          1   3%      - progn
                                                                          1   3%       - if
                                                                          1   3%        - let
                                                                          1   3%         - +javascript-init-lsp-or-tide-maybe-h
                                                                          1   3%          - funcall
                                                                          1   3%           - condition-case
                                                                          1   3%            - doom-run-hook
                                                                          1   3%             - run-hook-wrapped
                                                                          1   3%              - let
                                                                          1   3%               - condition-case
                                                                          1   3%                  let
                                                                          1   3% - mapcar
                                                                          1   3%  - evil-mode-for-keymap
                                                                          1   3%   - evil-state-auxiliary-keymaps
                                                                          1   3%    - evil-state-keymaps
                                                                          1   3%     - apply
                                                                          1   3%      - evil-state-keymaps
                                                                          1   3%       - evil-normalize-keymaps
                                                                          1   3%        - evil-snipe--normalize-keymaps
                                                                          1   3%         + evil-snipe-override-local-mode
                                                                          1   3% - macroexp--all-forms
                                                                          1   3%  - #<compiled -0x13dd96da0b56edc7>
                                                                          1   3%   - macroexp--expand-all
                                                                          1   3%    - macroexp--all-forms
                                                                          1   3%     - #<compiled -0x13dd96da0b56edc7>
                                                                          1   3%      - macroexp--expand-all
                                                                          1   3%       - macroexp--all-forms
                                                                          1   3%        - #<compiled -0x13dd96da0b56edc7>
                                                                          1   3%         - macroexp--expand-all
                                                                          1   3%          - macroexp--all-forms
                                                                          1   3%           - macroexp--expand-all
                                                                          1   3%            - macroexp--all-forms
                                                                          1   3%             - #<compiled -0x13dd96da0b56edc7>
                                                                          1   3%              - macroexp--expand-all
                                                                          1   3%               - macroexp--all-forms
                                                                          1   3%                  #<compiled -0x13dd96da0b56edc7>
                                                                          1   3% - locate-dominating-file
                                                                          1   3%  - vc-find-root
                                                                          1   3%   - if
                                                                          1   3%    - let
                                                                          1   3%     - vc-svn-registered
                                                                          1   3%      - apply
                                                                          1   3%       - vc-call-backend
                                                                          1   3%        - #<compiled 0xc985718663aa004>
                                                                          1   3%         - mapc
                                                                          1   3%          - vc-registered
                                                                          1   3%           - vc-backend
                                                                          1   3%            - #<compiled -0x1d29ef434dcc7fc5>
                                                                          1   3%             - apply
                                                                          1   3%              - #<compiled -0x7601fc4185eab56>
                                                                          1   3%               - apply
                                                                          1   3%                  vc-refresh-state
                                                                          1   3% - #<compiled -0x1dff12cd5232bd7f>
                                                                          1   3%  - vc-git-registered
                                                                          1   3%   - apply
                                                                          1   3%    - vc-call-backend
                                                                          1   3%     - #<compiled 0xc985718663aa004>
                                                                          1   3%      - mapc
                                                                          1   3%       - vc-registered
                                                                          1   3%        - vc-backend
                                                                          1   3%         - #<compiled -0x1d29ef434dcc7fc5>
                                                                          1   3%          - apply
                                                                          1   3%           - #<compiled -0x7601fc4185eab56>
                                                                          1   3%            - apply
                                                                          1   3%             - vc-refresh-state
                                                                          1   3%              - run-hooks
                                                                          1   3%               - #<compiled 0x175ab4d497617b18>
                                                                          1   3%                  apply
                                                                          1   3% - eval
                                                                          1   3%  - format-mode-line
                                                                          1   3%   - doom-modeline-format--main
                                                                          1   3%    - eval
                                                                          1   3%       redisplay_internal (C function)
                                                                          1   3% - #<compiled -0x138789c93ee2c52f>
                                                                          1   3%  - apply
                                                                          1   3%   - progn
                                                                          1   3%    - if
                                                                          1   3%     - +modeline-disable-icon-in-daemon-a
                                                                          1   3%      - apply
                                                                          1   3%       - doom-modeline-propertize-icon
                                                                          1   3%        - doom-modeline-icon
                                                                          1   3%         - doom-modeline--modal-icon
                                                                          1   3%          - doom-modeline-segment--modals
                                                                          1   3%           - eval
                                                                          1   3%              redisplay_internal (C function)
                                                                          0   0%   Automatic GC

```

### System Information

https://gist.github.com/quolpr/0214a69e2a710cee9ae22ee9092e53d4

**Comment by hlissner** [comment] 2022-10-07 16:51
Duplicate of #6878.

Please only one issue at a time.

**Closed by hlissner** 2022-10-07 16:51 UTC
Labels: duplicate
