### ISSUE TITLE
Tex mode producing invalid face error

### ISSUE THREAD

**Issue by sebastjancizel** [doomemacs/doomemacs#3821] opened 2020-08-24 12:39 UTC
**What did you expect to happen?**
When opening a tex file tex mode starts with Reftex mode loaded and functioning fontification. 

**What actually happened?**
Opening a tex file produces an invalid face error and breaks the fontification in auctex.

**Additional details:**
- One of the recent doom updates broke this for me (definitely worked a week ago)
- Turning on Reftex manually when editing tex file works so the issue with font-lock-mode is probably what's causing that.
- The issue persists without my private config
- while editing tex emacs keeps producing:
Error during redisplay: (jit-lock-function 4001) signaled (error "Invalid face" font-lock-function-name-face)
Error during redisplay: (jit-lock-function 6501) signaled (error "Invalid face" font-latex-math-face)
Error during redisplay: (jit-lock-function 14001) signaled (error "Invalid face" font-latex-math-face)

- UPDATE: just reinstalled doom and the problem persists. 

<details><pre>
Debugger entered--Lisp error: (error "Invalid face" font-lock-function-name-face)
  internal-get-lisp-face-attribute((font-lock-function-name-face) :extend nil)
  face-attribute((font-lock-function-name-face) :extend nil t)
  face-extend-p((font-lock-function-name-face) nil t)
  adaptive-wrap--face-extends((font-lock-function-name-face))
  adaptive-wrap--prefix-face("" 4271 4293)
  #f(compiled-function (beg end) #<bytecode -0x6e0dbcc688dde83>)(4271 4293)
  funcall(#f(compiled-function (beg end) #<bytecode -0x6e0dbcc688dde83>) 4271 4293)
  (let ((adaptive-wrap-extra-indent (+word-wrap--calc-extra-indent beg))) (funcall orig-fn beg end))
  +word-wrap--adjust-extra-indent-a(#f(compiled-function (beg end) #<bytecode -0x6e0dbcc688dde83>) 4271 4293)
  apply(+word-wrap--adjust-extra-indent-a #f(compiled-function (beg end) #<bytecode -0x6e0dbcc688dde83>) (4271 4293))
  adaptive-wrap-fill-context-prefix(4271 4293)
  adaptive-wrap-prefix-function(1 69261)
  #f(compiled-function (fun) #<bytecode 0x5872fa119b3bf75>)(adaptive-wrap-prefix-function)
  run-hook-wrapped(#f(compiled-function (fun) #<bytecode 0x5872fa119b3bf75>) adaptive-wrap-prefix-function)
  jit-lock--run-functions(1 69261)
  jit-lock-fontify-now()
  TeX-fold-buffer()
  run-hooks(change-major-mode-after-body-hook text-mode-hook TeX-mode-hook LaTeX-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook TeX-mode-hook LaTeX-mode-hook))
  run-mode-hooks(text-mode-hook TeX-mode-hook LaTeX-mode-hook)
  TeX-latex-mode()
  apply(TeX-latex-mode nil)
  LaTeX-mode()
  set-auto-mode-0(LaTeX-mode nil)
  #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode -0x5bb56716dedd2d4>)()
  apply(#f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode -0x5bb56716dedd2d4>) nil)
  #f(advice-wrapper :after #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode -0x5bb56716dedd2d4>) auto-minor-mode-set)()
  apply(#f(advice-wrapper :after #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode -0x5bb56716dedd2d4>) auto-minor-mode-set) nil)
  so-long--set-auto-mode(#f(advice-wrapper :after #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode -0x5bb56716dedd2d4>) auto-minor-mode-set))
  apply(so-long--set-auto-mode #f(advice-wrapper :after #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode -0x5bb56716dedd2d4>) auto-minor-mode-set) nil)
  set-auto-mode()
  normal-mode(t)
  #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode -0x9ee3581d5330dd8>)(nil t)
  apply(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode -0x9ee3581d5330dd8>) (nil t))
  (if (setq doom-large-file-p (and buffer-file-name (not doom-large-file-p) (file-exists-p buffer-file-name) (condition-case nil (progn (> (nth 7 (file-attributes buffer-file-name)) (* 1024 1024 (assoc-default buffer-file-name doom-large-file-size-alist ...)))) (error nil)))) (prog1 (apply orig-fn args) (if (memq major-mode doom-large-file-excluded-modes) (setq doom-large-file-p nil) (if (fboundp 'so-long-minor-mode) (progn (so-long-minor-mode 1))) (message "Large file detected! Cutting a few corners to impr..."))) (apply orig-fn args))
  doom--optimize-for-large-files-a(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode -0x9ee3581d5330dd8>) nil t)
  apply(doom--optimize-for-large-files-a #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode -0x9ee3581d5330dd8>) (nil t))
  #f(advice-wrapper :around #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode -0x9ee3581d5330dd8>) doom--optimize-for-large-files-a)(nil t)
  apply(#f(advice-wrapper :around #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode -0x9ee3581d5330dd8>) doom--optimize-for-large-files-a) (nil t))
  #f(advice-wrapper :before #f(advice-wrapper :around #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode -0x9ee3581d5330dd8>) doom--optimize-for-large-files-a) doom-first-file-hook-h)(nil t)
  apply(#f(advice-wrapper :before #f(advice-wrapper :around #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode -0x9ee3581d5330dd8>) doom--optimize-for-large-files-a) doom-first-file-hook-h) (nil t))
  after-find-file(nil t)
  find-file-noselect-1(#<buffer NotesOnSUSYGeometries-08-23.tex> "~/Desktop/Shared-NotesOnSUSYGeometries/NotesOnSUSY..." nil nil "~/Desktop/Shared-NotesOnSUSYGeometries/NotesOnSUSY..." (15906983 16777221))
  find-file-noselect("~/Desktop/Shared-NotesOnSUSYGeometries/NotesOnSUSY..." nil nil nil)
  find-file("~/Desktop/Shared-NotesOnSUSYGeometries/NotesOnSUSY...")
</pre></details>

**Steps to reproduce:**
1. Open Doom
2. Open any tex file 

**System information:**
<details><pre>
```
emacs   version    28.0.50
        features   JPEG TIFF PNG RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS JSON PDUMPER LCMS2
        build      Aug 24, 2020
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@28/28.0.50/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@28/28.0.50 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-json --with-modules --with-rsvg --without-pop --with-xwidgets --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop e3750dbf6 2020-08-23 18:48:50 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.6.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
        path       (/usr/local/opt/llvm/bin /usr/local/opt/ruby/bin /usr/local/sbin /usr/local/anaconda3/bin /usr/local/opt/ruby/bin /usr/local/sbin ~/.gem/ruby/2.7.0/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin ~/anaconda/bin /usr/local/opt/fzf/bin /usr/local/Cellar/emacs-plus@28/28.0.50/libexec/emacs/28.0.50/x86_64-apple-darwin19.6.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +childframe) (ivy +icons +fuzzy +prescient) :ui doom doom-dashboard doom-quit hl-todo indent-guides minimap modeline nav-flash ophints (popup +defaults) (ligatures +fira) treemacs unicode vc-gutter vi-tilde-fringe window-select zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets word-wrap :emacs (dired +icons) electric (ibuffer +icons) (undo +tree) vc :term vterm :checkers syntax spell grammar :tools biblio debugger editorconfig ein (eval +overlay) lookup lsp magit make pdf rgb :os macos :lang cc data emacs-lisp ess (haskell +dante) javascript julia (latex +latexmk +fold +lsp) markdown (org +jupyter +gnuplot +pretty) (python +conda) sh web :email (mu4e +gmail) :app calendar :config (default +bindings +smartparens))
        packages   ((org-super-agenda))
        unpin      (n/a)
        elpa       (undo-tree company)
```
</pre></details>

**Comment by A6GibKm** [comment] 2020-09-04 10:28
Do you have nativecomp enabled? I also have this issue.

**Comment by sebastjancizel** [comment] 2020-09-06 20:48
No, I don't. I'm just running emacs plus 28 from the master branch, which I don't think has nativecomp.

**Comment by igoralmeida** [comment] 2020-09-28 02:01
I'm seeing this on 27.1 (with xwidgets) as well. Just upgraded to 1456108d5

**Comment by ymarco** [comment] 2020-09-28 17:26
Was introduced by #3823 I think. Still don't know why though.
For now, does this fix it?
```emacs-lisp
;; put in config.el
(assq-delete-all 'latex-mode +spell-excluded-faces-alist)
```

**Comment by ymarco** [comment] 2020-09-28 17:33
> Was introduced by #3823 I think. Still don't know why though.

Actually I'm not sure this makes sense, this issue was opened on August the 24th while my PR was merged on the 25th.

**Comment by igoralmeida** [comment] 2020-09-28 23:28
> Was introduced by #3823 I think. Still don't know why though.
> For now, does this fix it?
> 
> ```emacs-lisp
> ;; put in config.el
> (assq-delete-all 'latex-mode +spell-excluded-faces-alist)
> ```

I don't even have this variable (seems to be from `:checkers spell`, which I have not enabled).
Here are the errors I see as soon as I open a tex file:
```
Error during redisplay: (jit-lock-function 16929) signaled (error "Invalid face" font-latex-string-face)
Error during redisplay: (jit-lock-function 3229) signaled (error "Invalid face" font-latex-string-face)
Error during redisplay: (jit-lock-function 3729) signaled (error "Invalid face" font-latex-string-face)
Error during redisplay: (jit-lock-function 9062) signaled (error "Invalid face" font-lock-constant-face)
Error during redisplay: (jit-lock-function 16187) signaled (error "Invalid face" font-latex-math-face)
```

Also, `toggle-debug-on-error` does not do anything (I'm guessing because it's deep in the redisplay C code?), so I'm a bit lost on how to produce a backtrace. I have also tried disabling flycheck (`global-flycheck-mode`), but it continues.

Also, I can see these faces in `SPC h F` and they don't look "incorrect" (though I must admit I don't remember their values before upgrading), alongside for example `font-latex-subscript-face`, which is working fine in the buffer.

**Comment by haji-ali** [comment] 2021-02-04 13:48
I am also experiencing this issue.

My doom info for reference
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64
        path       (~/perl5/bin ~/.cargo/bin ~/.local/share/texlive//bin/x86_64-linux ~/.local/bin ~/.local/opt/llvm/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.local/libexec/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/Work/Projects/dotfiles/emacs/.emacs.d/
        version    27.1
        build      Sep 14, 2020
        buildopts  --prefix=/home/abdo/.local/ --with-json --with-modules --with-harfbuzz --with-compress-install --with-threads --with-included-regex --with-zlib --with-sound=alsa --without-gconf --with-mailutils --with-xft --with-xml2 --with-cairo --with-gconf --with-xwidgets --without-toolkit-scroll-bars 'CFLAGS=-O3 -mtune=native -march=native -fomit-frame-pointer -I/usr/lib/gcc/x86_64-linux-gnu/9/include/ -L/usr/lib/gcc/x86_64-linux-gnu/9'
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GCONF GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (gui server-running)
DOOM    dir        ~/Work/Projects/dotfiles/emacs/.config/doom/
        version    2.0.9
        font       #<font-object -DAMA-Ubuntu Mono-normal-normal-normal-*-17-*-*-*-m-0-iso10646-1>
        theme      doom-one
        build      HEAD -> develop, origin/develop, origin/HEAD 2d718cc86 2021-01-27 03:37:55 -0500
        elc-files  75
        modules    (:completion ivy :ui doom hl-todo modeline window-select :emacs dired ibuffer undo :checkers spell :tools magit pdf :os tty :lang emacs-lisp (latex +latexmk) markdown yaml :email mu4e :config literate (default +bindings) :my-apps (&user org) (&user org-agenda) (&user email) (&user dired) (&user latex) (&user shell) (&user magit) :my-completion (&user ivy) :my-emacs (&user wind-mgmt) (&user paren))
        packages   ((hungry-delete) (openwith) (origami) (lsp-origami) (el-patch) (explain-pause-mode :disable t) (selectrum) (focus) (ace-jump-mode) (iedit) (aggressive-indent) (eglot) (flyspell-correct))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by Jdogzz** [comment] 2024-05-02 22:36
@sebastjancizel Are you still able to reproduce this? On a few different machines I routinely work with tex files but that error does not come up so your steps to reproduce do not reproduce the issue on my end. Here's the output of `doom/info`: https://pastebin.com/gF4bhN2c

**Comment by hlissner** [comment] 2024-09-02 05:04
Seems this was a bug in `adapative-wrap` (installed by the `:editor word-wrap` module), but it was fixed [by this patch](https://git.savannah.gnu.org/gitweb/?p=emacs/elpa.git;a=blobdiff;f=adaptive-wrap.el;h=3e891af1c55f7c1c53f8414ccfe00bc99b3bcb48;hp=b075b3b7e3bc0e9afee0892c2e036076ae2e086e;hb=a4c49ef906b0318485ae053c344fc524c2d8be7c;hpb=603648e22a28afd2f1c7a7f9c230751cde2dfeca;ds=sidebyside) deployed on January 10, 2021. So this has been definitively fixed already.

**Closed by hlissner** 2024-09-02 05:04 UTC
Labels: is:bug, module:lang/latex
