### ISSUE TITLE
`Error: void-variable (straight-base-dir)` after this commit 8cafbe440

### ISSUE THREAD

**Issue by maikol-solis** [doomemacs/doomemacs#8141] opened 2024-11-03 13:17 UTC
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Do a normal `doom sync`. 

### Current behavior

After upgrading to 8cafbe4408e7d6c68947a2066e5837379d0983c1, the sync process stop with this backtrace

[cli.doom.241103070848.86616.log](https://github.com/user-attachments/files/17610538/cli.doom.241103070848.86616.log)

### Steps to reproduce

1. `doom sync -u` 
2. Error

### System Information

NA

**Comment by maikol-solis** [comment] 2024-11-03 14:03
After researching a little, disabling `:config literate` in the `init.el` fixs the issue.  Of course, this is just a dirty workaround.

**Comment by punkisdead** [comment] 2024-11-03 15:55
disabling `:config literate` does not fix this for me.

**Comment by vlnn** [comment] 2024-11-03 16:27
This seems to be a duplicate of https://github.com/doomemacs/doomemacs/issues/8140, you may find workaround there.

**Comment by hlissner** [comment] 2024-11-03 16:51
Duplicate of #8140

**Closed by hlissner** 2024-11-03 16:51 UTC
Labels: duplicate
