### ISSUE TITLE
`magit` not showing files in untracked directory

### ISSUE THREAD

**Issue by brorbw** [doomemacs/doomemacs#6293] opened 2022-04-13 09:38 UTC
### What did you expect to happen?

This experience is from using `magit` with spacemacs years ago, so it might have been changed.
Pressing `tab` would usually unfold an untracked directory and list files and folders. This is especially useful when adding git to an existing project. That way you don't have to add the entire folder and then unstage everything you don't want. I'm unsure if this is a bug, or just a matter of configuration.

Not showing files in an untracked directory makes it impossible to add a sub directory within an untracked folder where you only want to add the one folder or file. As a consequence it's hard to split a feature into multiple commits or adding files in separate commits.

The simple solution is to add it manually with git.

### What actually happened?

Only root folder of untracked directories show.

### Describe your attempts to resolve the issue

Manually adding with `git`or adding the entiry folder and unstage the files I don't want.

### Steps to reproduce

Create a git repo

```sh
cd /tmp
mkdir test-magit
git init
mkdir test-untracked
touch test-untracked/leave-untracked-file
mkdir test-untracked/test-dir
touch test-untracked/test-dir/file-to-stage-file
```

Open emacs:
Navigate to `/tmp/test-magit`
`SPC gg`

The output of the buffer should be:
```
In the beginning there was darkness

Untracked files (1)
test-untracked
```

Only the folder `test-untracked`  is shown, with no way of adding individual files for tracking. Only the entire `test-untracked` directory. Adding this will stage all files.

### System Information

https://pastebin.com/AKDzEQmn

**Comment by hlissner** [comment] 2022-04-13 18:40
> Only root folder of untracked directories show.

As far as I know, this has always been magit's behavior. Nothing in Spacemacs' magit config indicates this has been changed on their end, and there are no magit variables that control this.

Ah, correction, it seems magit recognizes the git repo-level setting: `status.showUntrackedFiles` ([mentioned here](https://github.com/magit/magit/issues/1599#issuecomment-62631795)). If set to `all`, it will do as you described.

In any case, it seems this issue already has a solution and/or is Magit's jurisdiction, so I will close this, but feel free to follow up here.

**Closed by hlissner** 2022-04-13 18:40 UTC
Labels: invalid

**Comment by brorbw** [comment] 2022-04-13 18:49
Appreciate the detective work

**Comment by rhstanton** [comment] 2025-02-04 19:11
I've just encountered this issue and the solutions suggested here don't seem to work. I've set `status.showUntrackedFiles` to all in gitconfig, and when I run `git status` at the command line, I see the individual untracked files as desired. But still only the enclosing directory shows up in magit.

To test this:

1) Create a new directory and run `git init` in it
2) `mkdir subdir`
3) `touch newfile.txt`

`git status` in the main directory shows, as desired,
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	subdir/newfile.txt
```
Now open the directory in Emacs and press `C-x g`. Here's what I see:
```
In the beginning there was darkness

Untracked files (1)
subdir/
```
Manually setting `magit-status-show-untracked-files` to `"all"` doesn't help (by the way, by default it's set to t, not all, even though status.showUntrackedFiles is set to "all" in .gitconfig).

**Comment by choroba** [comment] 2025-03-03 14:03
@rhstanton: I can confirm. It has worked for me for several years, but today I noticed pressing <kbd>Tab</kbd> doesn't add untracked files. I've recently upgraded to Emacs 30.1, so it might be related.

**Comment by choroba** [comment] 2025-03-03 14:10
It seems the variable `magit-status-show-untracked-files` has `:type 'boolean` which prevents it from having the value `"all"`.

**Comment by choroba** [comment] 2025-03-03 14:21
But changing it to ```lisp
  :type '(choice
          (boolean :tag "yes/no")
          (const :tag "All" "all"))
```
doesn't seem to help.

**Comment by taquangtrung** [comment] 2025-03-20 04:35
> It seems the variable `magit-status-show-untracked-files` has `:type 'boolean` which prevents it from having the value `"all"`.

This works for me: `(setq magit-status-show-untracked-files 'all)`

**Comment by hlissner** [comment] 2025-03-20 06:35
Seems the `magit-status-show-untracked-files` variable was added in Magit 4.3.0:

```elisp
;;; add to $DOOMDIR/config.el
(after! magit
  (setq magit-status-show-untracked-files 'all))
```

Though, `status.showUntrackedFiles` is still be recognized, and in my testing seems to be true.

> It seems the variable magit-status-show-untracked-files has :type 'boolean which prevents it from having the value "all".

This should be reported upstream. In any case, from [how it's used in `magit-insert-untracked-files`](https://github.com/magit/magit/blob/main/lisp/magit-status.el#L759-L763), it recognizes `t`, `nil` (or `'no`), and `'all`.
