### ISSUE TITLE
doom-font not working with Emacs 29.1 (regular x11 + gtk3 variant)

### ISSUE THREAD

**Issue by rubin55** [doomemacs/doomemacs#7320] opened 2023-07-30 21:36 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Arch linux upgraded Emacs to 29.1, which came out today. This is the regular X11 + gtk3 version (I checked).

Most stuff seems to work fine (at least the things I use, doom install, sync, upgrade, etc). However, `doom-font` seems to not set the font anymore.

Things I've tried:
  * set font using `font-spec` object
  * set font using Freetype2 string (Monospace-12)
  * set font using GTK string (Monospace 12)
  * set font using XLFSD string 
  * set font via emacs directly (menubar-mode, options -> set default font)

Only the last option above sets the font correctly, which leads me to think Emacs can do it, but Doom is not passing the config to emacs correctly or some-such.

Possibly related message in the `messages` buffer:

```
Warning: setting attribute ‘:background’ of face ‘font-lock-comment-face’: nil value is invalid, use ‘unspecified’ instead.
```

### Current behavior

doom-font does not set emacs font.

### Steps to reproduce

1. Update to Emacs 29.1
2. Clear out ~/.emacs.d/.local
3. doom upgrade
4. open emacs
5. observe adobe-courier x11 bitmap font instead of what you specified in doom-font

### System Information

https://bpa.st/UOMQ

**Comment by SoutrikBandyopadhyay** [comment] 2023-08-02 12:49
Any idea if/when Emacs 29.1 would be supported?

**Comment by rustyCircleJones** [comment] 2023-08-19 17:14
Fonts are working for me in Doom Emacs 29.1.  Not sure this is going to be helpful, but this is what I have done:


1.  Went to https://github.com/ryanoasis/nerd-fonts and in the 'Releases' page in the side bar picked out some font tarballs.
2. In Arch Linux I untarred them into ~/.local/share/fonts/
3. Restarted Emacs
4. M-x describe-font 
5. Searched for "Nerd" to find the fonts in the output.  Picked a Mono version and hit enter to bring up the font info.
6. based on the first field in 'full name:' section I made this entry in my config.el:
 ```
(setq doom-font (font-spec :family "Hack Nerd Font Mono" :size 14 :weight 'normal)
      doom-variable-pitch-font (font-spec :family "Hack Nerd Font" :size 14)
      doom-theme 'doom-dracula)
````
7. I highlighted that code block and ran 'SPC m e r'  (eval-region) and then 'SPC h r f'  (doom/reload-font) and it updated the font.

**Comment by hlissner** [comment] 2023-08-20 14:48
I cannot reproduce any issues with font loading for Doom in 28.2, 29.1, or 30+ (HEAD). Also, your doom-info link doesn't work, so there's not much to go on here, but this sounds like a simple case of "Emacs can't find your font", which is a config issue rather than a bug.

1. When setting `doom-font`, make sure the font name is correct (use `$ fc-list | grep FONTNAME` to find out). Some fonts (especially nerd fonts) can have unusual names.
2. Make sure the font is properly installed.
3. Make sure Emacs is built with X support (i.e. not from an emacs-nox package or similar). No GUI support means no font support.

I'll close this for now (or until new evidence comes to light suggesting it isn't a config issue), but feel free to follow up here.

**Closed by hlissner** 2023-08-20 14:48 UTC
Labels: invalid

**Comment by gabriel-viviani** [comment] 2023-10-27 22:07
> Fonts are working for me in Doom Emacs 29.1. Not sure this is going to be helpful, but this is what I have done:
> 
>     1. Went to https://github.com/ryanoasis/nerd-fonts and in the 'Releases' page in the side bar picked out some font tarballs.
> 
>     2. In Arch Linux I untarred them into ~/.local/share/fonts/
> 
>     3. Restarted Emacs
> 
>     4. M-x describe-font
> 
>     5. Searched for "Nerd" to find the fonts in the output.  Picked a Mono version and hit enter to bring up the font info.
> 
>     6. based on the first field in 'full name:' section I made this entry in my config.el:
> 
> 
> ```
> (setq doom-font (font-spec :family "Hack Nerd Font Mono" :size 14 :weight 'normal)
>      doom-variable-pitch-font (font-spec :family "Hack Nerd Font" :size 14)
>      doom-theme 'doom-dracula)
> ```
> 
>     7. I highlighted that code block and ran 'SPC m e r'  (eval-region) and then 'SPC h r f'  (doom/reload-font) and it updated the font.

I'm a bit new to both arch and doom emacs.
Worked like a charm to use `~/.local/share/fonts/`. Thank you!

**Comment by Ethergeist** [comment] 2023-11-25 20:10
So, I had the same issue, I tried the above solution and it did not work. The problem I was having was due to running under plasma desktop in wayland - since I'm on Arch, the solution was to remove the default emacs package and install emacs-wayland instead.
