### ISSUE TITLE
Failed to fetch from upstream

### ISSUE THREAD

**Issue by hasit** [doomemacs/doomemacs#6625] opened 2022-08-02 15:40 UTC
### What did you expect to happen?

When I run `doom upgrade`, it should fetch the upgrade latest doom.

### What actually happened?

$ doom upgrade
> Preparing to upgrade Doom Emacs and its packages...
x There was an unexpected runtime error
  Message: Failed to fetch from upstream
  Backtrace:
    (signal error ("Failed to fetch from upstream"))
    (error "Failed to fetch from upstream")
    (or (= 0 (car (setq result (sh! "git" "fetch" "--force" "--tags" doom-upgrade-remote (format...
    (let (result) (or (= 0 (car (sh! "git" "remote" "add" doom-upgrade-remote doom-upgrade-url))...
    (unwind-protect (let (result) (or (= 0 (car (sh! "git" "remote" "add" doom-upgrade-remote do...
    (let* ((branch (replace-regexp-in-string "^\\(?:[^/]+/[^/]+/\\)?\\(.+\\)\\(?:~[0-9]+\\)?$" "...
    (let ((default-directory doom-emacs-dir) process-file-side-effects) (doom-print (doom-print-...
    (doom-cli-upgrade #s(doom-cli-context (25321 17417 148012 611000) 10145 1 (100 . 47) nil nil...
    (cond (packages\? (let ((recipe (doom-cli-context-get context 'straight-recipe))) (if (and r...
    (let* ((force\? (progn (or (and (memq (type-of context) cl-struct-doom-cli-context-tags) t) ...
    (let ((packages\? (cdr (assq 'packages\? alist))) (jobs (cdr (assq 'jobs alist))) (context (...
    ((closure (t) (cli alist) (let ((packages\? (cdr (assq 'packages\? alist))) (jobs (cdr (assq...
  ! Wrote extended backtrace to ~/.emacs.d/.local/logs/cli.doom.220802083433.10145.error

### Steps to reproduce

1. Run `doom upgrade`

Extended backtrace: https://pastebin.com/kXFf6Hh3

### System Information

https://pastebin.com/we65nxWb

**Comment by hlissner** [comment] 2022-08-02 16:40
Duplicate of #6598

**Closed by hlissner** 2022-08-02 16:40 UTC
Labels: duplicate
