### ISSUE TITLE
Org-mode not fully initialized after consult-org-agenda

### ISSUE THREAD

**Issue by 45mg** [doomemacs/doomemacs#7737] opened 2024-03-20 14:27 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

After running `consult-org-agenda` and selecting a heading (and thereby its buffer), org-mode should be fully initialized in the selected buffer.

### Current behavior

If the buffer is visiting an org file that was not previously loaded, org-mode is not fully initialized. In particular, `org-indent-mode` is not on.

In addition, the following error keeps firing for as long as point is in the org buffer -
```
Invalid face reference: org-indent [129 times]
```

I have a feeling that this is a font-lock error. In particular, `doom-themes-enable-org-fontification` defines a rule that applies the `org-indent` face, so the error could be from there. I have no idea how to confirm this, though - any guidance on how to debug font-lock errors would be appreciated. It's probably a symptom of the issue rather than the root cause, though.

Finally - it's entirely possible that this is an issue with Consult itself, but one would assume that someone would have reported it by now if that was the case, as it's something that would affect a lot of users. I _can_ confirm, however, that this isn't down to my config - I could reproduce it on a fresh install with only `org-directory` and `org-agenda-files` set in config.el.

I was able to circumvent the issue by advising `consult--jump` to restart org-mode -
``` elisp
(defadvice! consult--restart-org-mode-after-jump-h (&rest _)
  :after #'consult--jump
  (when (derived-mode-p #'org-mode)
    (save-excursion (org-mode-restart))))
```
but we should probably try to determine the root cause.

### Steps to reproduce

1. Restart Emacs
2. `M-x consult-org-agenda` and select a heading
3. `C-h v org-indent-mode`, and observe that its value is nil

### System Information

https://0x0.st/XrVx.txt

**Comment by real-or-random** [comment] 2024-05-21 11:29
I suspect this is due to some of doom's optimizations to speed up org-agenda. Org-mode should be automatically restarted when you open an org buffer, but perhaps that doesn't work with `consult-org-agenda` or it doesn't work in this case for some other reason. See https://github.com/real-or-random/doomemacs/blob/master/modules/lang/org/config.el#L840 for starters.

**Comment by imkaihao** [comment] 2024-06-16 14:38
I have the same problem.

**Comment by real-or-random** [comment] 2024-06-17 08:22
By the way, I *cannot* reproduce this on 517daa4ed9168855c202ba2fd28920f6ee17249f on my config. When selecting headings in the minibuffer during `consult-org-agenda`, I still see the incomplete buffers in the preview. But as soon as I press RET to do finalize the selection and switch to the buffer, org-mode is reloaded automatically.

**Comment by hlissner** [comment] 2024-07-03 01:18
> By the way, I _cannot_ reproduce this on [517daa4](https://github.com/doomemacs/doomemacs/commit/517daa4ed9168855c202ba2fd28920f6ee17249f) on my config. When selecting headings in the minibuffer during `consult-org-agenda`, I still see the incomplete buffers in the preview. But as soon as I press RET to do finalize the selection and switch to the buffer, org-mode is reloaded automatically.

Can others confirm this is the case? If so, I can close this as resolved.

**Comment by 45mg** [comment] 2024-07-03 04:38
> Can others confirm this is the case? If so, I can close this as resolved.

I can still reproduce on vanilla Doom (only enabled :completion vertico and set org-directory & org-agenda-files)

**Comment by hlissner** [comment] 2024-07-05 21:07
Could you see if [one of these snippest](https://github.com/doomemacs/doomemacs/issues/5411#issuecomment-2201994306) fix the issue for you?

**Comment by 45mg** [comment] 2024-07-09 11:32
> Could you see if [one of these snippest](https://github.com/doomemacs/doomemacs/issues/5411#issuecomment-2201994306) fix the issue for you?

Nope, they don't. Not surprising, since both of those concern org-capture, and this issue has nothing to do with it.

**Comment by real-or-random** [comment] 2024-07-09 12:47
After some digging:
 * `consult-org-agenda` will call `org-get-agenda-file-buffer`, which we have advised to turn off various stuff for performance reasons.
 * But since `consult-org-agenda` won't call `org-agenda-finalize-hook`, the restart hook is not added to the affected buffers.

And yes, I can reproduce this on 944eef90ec7962c3b17cf3e6df65bbac5f03dfdc, but only if I haven't called org-agenda in the session.  This is consistent with my findings.

I'll open a PR.

**Closed** 2024-07-10 05:46 UTC
Labels: is:bug, module:lang/org
