### ISSUE TITLE
Missing `site-start.el` file causes `doom sync` to crash

### ISSUE THREAD

**Issue by thiagokokada** [doomemacs/doomemacs#7940] opened 2024-07-12 00:00 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

In Nix, you have the option to wrap Emacs by adding extra packages on it, e.g.:

```nix
programs.emacs = {
  enable = true;
  package = pkgs.emacs.pkgs.emacsWithPackages
    (epkgs: with epkgs; [ treesit-grammars.with-all-grammars vterm ]);
};
```

I expect that this works with doom-emacs, the same way that the unwrapped package works, e.g.:

```nix
programs.emacs = {
  enable = true;
  package = pkgs.emacs; # this is ok
};
```

### Current behavior

Using the wrapped Emacs package causes `doom sync` to fail with the following error:

```
Error: doom-core-error ("/home/thiagoko/.config/emacs/lisp/doom-cli.el" (file-missing "Cannot open load file" "No such file or directory" "/nix/store/lv94418mrqbmw7p1460dz634vk64asr4-emacs-pgtk-with-packages-29.4/share/emacs/site-lisp/site-start"))
  mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode 0x186e7d6af3aef268>))
  debug-early-backtrace()
  debug-early(error (doom-core-error "/home/thiagoko/.config/emacs/lisp/doom-cli.el" (file-missing "Cannot open load file" "No such file or directory" "/nix/store/lv94418mrqbmw7p1460dz634vk64asr4-emacs-pgtk-with-packages-29.4/share/emacs/site-lisp/site-start")))
  signal(doom-core-error ("/home/thiagoko/.config/emacs/lisp/doom-cli.el" (file-missing "Cannot open load file" "No such file or directory" "/nix/store/lv94418mrqbmw7p1460dz634vk64asr4-emacs-pgtk-with-packages-29.4/share/emacs/site-lisp/site-start")))
  (condition-case e (load path noerror 'nomessage) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (setq path (locate-file path load-path (get-load-suffixes))) (signal (cond ((not (and path (featurep 'doom))) 'error) ((file-in-directory-p path (expand-file-name "cli" doom-core-dir)) 'doom-cli-error) ((file-in-directory-p path doom-core-dir) 'doom-core-error) ((file-in-directory-p path doom-user-dir) 'doom-user-error) ((file-in-directory-p path doom-profile-dir) 'doom-profile-error) ((file-in-directory-p path doom-modules-dir) 'doom-module-error) ('doom-error)) (list path e))))
  doom-load("doom-cli" nil)
  (or (featurep feature subfeature) (doom-load (if subfeature (file-name-concat doom-core-dir (string-remove-prefix "doom-" (symbol-name feature)) (symbol-name filename)) (symbol-name feature)) noerror))
  (let ((subfeature (if (symbolp filename) filename))) (or (featurep feature subfeature) (doom-load (if subfeature (file-name-concat doom-core-dir (string-remove-prefix "doom-" (symbol-name feature)) (symbol-name filename)) (symbol-name feature)) noerror)))
  doom-require(doom-cli)
  (if (let ((load-suffixes '(".elc" ".el"))) (condition-case _ (load (expand-file-name "lisp/doom" user-emacs-directory) nil (not init-file-debug) nil 'must-suffix) ((debug file-missing) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list #'(lambda nil (expand-file-name "init.el" user-emacs-directory)) nil (nth 2 args)))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil))) (doom-require (if noninteractive 'doom-cli 'doom-start)))
  (let (file-name-handler-alist) (let ((command-line-args (if noninteractive nil command-line-args)) (profile (or (car (cdr (member "--profile" command-line-args))) (getenv-internal "DOOMPROFILE")))) (if (null profile) (let ((init-dir (or (car (cdr (member "--init-directory" command-line-args))) (getenv-internal "EMACSDIR")))) (if (null init-dir) (if noninteractive (progn (setq user-emacs-directory (file-name-directory (file-truename load-file-name))))) (setq command-switch-alist (cons (cons "--init-directory" #'(lambda (_) (car-safe (prog1 argv (setq argv (cdr argv)))))) command-switch-alist)) (setq user-emacs-directory (expand-file-name init-dir)))) (setq command-switch-alist (cons (cons "--profile" #'(lambda (_) (car-safe (prog1 argv (setq argv (cdr argv)))))) command-switch-alist)) (setenv "DOOMPROFILE" profile) (or (load (expand-file-name (format (let ((lfile (getenv-internal "DOOMPROFILELOADFILE"))) (if lfile (concat (let ((suffix ".el")) (if (string-suffix-p suffix lfile) (substring lfile 0 (- (length lfile) (length suffix))) lfile)) ".%d.elc") "profiles/load.%d.elc")) emacs-major-version) user-emacs-directory) 'noerror (not init-file-debug) 'nosuffix) (user-error "Profiles not initialized yet; run 'doom sync' first")))) (if (let ((load-suffixes '(".elc" ".el"))) (condition-case _ (load (expand-file-name "lisp/doom" user-emacs-directory) nil (not init-file-debug) nil 'must-suffix) ((debug file-missing) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list #'(lambda nil (expand-file-name "init.el" user-emacs-directory)) nil (nth 2 args)))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil))) (doom-require (if noninteractive 'doom-cli 'doom-start))))
  (or (let (file-name-handler-alist) (let ((command-line-args (if noninteractive nil command-line-args)) (profile (or (car (cdr (member "--profile" command-line-args))) (getenv-internal "DOOMPROFILE")))) (if (null profile) (let ((init-dir (or (car (cdr (member "--init-directory" command-line-args))) (getenv-internal "EMACSDIR")))) (if (null init-dir) (if noninteractive (progn (setq user-emacs-directory (file-name-directory (file-truename load-file-name))))) (setq command-switch-alist (cons (cons "--init-directory" #'(lambda (_) (car-safe (prog1 argv (setq argv (cdr argv)))))) command-switch-alist)) (setq user-emacs-directory (expand-file-name init-dir)))) (setq command-switch-alist (cons (cons "--profile" #'(lambda (_) (car-safe (prog1 argv (setq argv (cdr argv)))))) command-switch-alist)) (setenv "DOOMPROFILE" profile) (or (load (expand-file-name (format (let ((lfile (getenv-internal "DOOMPROFILELOADFILE"))) (if lfile (concat (let ((suffix ".el")) (if (string-suffix-p suffix lfile) (substring lfile 0 (- (length lfile) (length suffix))) lfile)) ".%d.elc") "profiles/load.%d.elc")) emacs-major-version) user-emacs-directory) 'noerror (not init-file-debug) 'nosuffix) (user-error "Profiles not initialized yet; run 'doom sync' first")))) (if (let ((load-suffixes '(".elc" ".el"))) (condition-case _ (load (expand-file-name "lisp/doom" user-emacs-directory) nil (not init-file-debug) nil 'must-suffix) ((debug file-missing) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list #'(lambda nil (expand-file-name "init.el" user-emacs-directory)) nil (nth 2 args)))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil))) (doom-require (if noninteractive 'doom-cli 'doom-start)))) (load user-init-file 'noerror (not init-file-debug) nil 'must-suffix))
  load-with-code-conversion("/home/thiagoko/.config/emacs/early-init.el" "/home/thiagoko/.config/emacs/early-init.el" nil t)
  load("/home/thiagoko/.config/emacs/early-init.el" nil nomessage nosuffix)
  (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom))
  (or (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file))
  (let* ((bin-dir (file-name-directory (file-truename load-file-name))) (init-file (expand-file-name "../early-init.el" bin-dir))) (or (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file)))
  (condition-case e (let* ((bin-dir (file-name-directory (file-truename load-file-name))) (init-file (expand-file-name "../early-init.el" bin-dir))) (or (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file))) (user-error (message "Error: %s" (car (cdr e))) (kill-emacs 2)))
  load-with-code-conversion("/home/thiagoko/.config/emacs/bin/doom" "/home/thiagoko/.config/emacs/bin/doom" nil t)
  command-line-1(("--load" "/home/thiagoko/.config/emacs/bin/doom" "--" "sync"))
  command-line()
  normal-top-level()
Unexpected error in Doom’s core: "/home/thiagoko/.config/emacs/lisp/doom-cli.el", (file-missing "Cannot open load file" "No such file or directory" "/nix/store/lv94418mrqbmw7p1460dz634vk64asr4-emacs-pgtk-with-packages-29.4/share/emacs/site-lisp/site-start")
```

The reason is because the wrapped Emacs package doesn't have a `$out/share/emacs` directory:

```
$ ls -lah /nix/store/lv94418mrqbmw7p1460dz634vk64asr4-emacs-pgtk-with-packages-29.4/share/                                                                             
total 16K
dr-xr-xr-x  1 root root 48 Jan  1  1970 .
dr-xr-xr-x  1 root root 16 Jan  1  1970 ..
lrwxrwxrwx 12 root root 78 Jan  1  1970 applications -> /nix/store/w3b5czhp5ayrpqp2lqlmpwgkiyhjij1k-emacs-pgtk-29.4/share/applications
lrwxrwxrwx 12 root root 71 Jan  1  1970 icons -> /nix/store/w3b5czhp5ayrpqp2lqlmpwgkiyhjij1k-emacs-pgtk-29.4/share/icons
lrwxrwxrwx 12 root root 70 Jan  1  1970 info -> /nix/store/w3b5czhp5ayrpqp2lqlmpwgkiyhjij1k-emacs-pgtk-29.4/share/info
lrwxrwxrwx 12 root root 69 Jan  1  1970 man -> /nix/store/w3b5czhp5ayrpqp2lqlmpwgkiyhjij1k-emacs-pgtk-29.4/share/man
```

If I remove the following lines from `doom-cli.el` I can run `doom sync` again without issues: https://github.com/doomemacs/doomemacs/blob/master/lisp/doom-cli.el#L30-L43. Or as an alternative, I can do something similar to this in my Nix config:

```nix
programs.emacs = {
  enable = true;
  package =
    (emacs'.pkgs.withPackages (
      epkgs: with epkgs; [
        treesit-grammars.with-all-grammars
        vterm
      ]
    )).overrideAttrs
      (oldAttrs: {
        buildCommand =
          (oldAttrs.buildCommand or (throw "emacs.pkgs.withPackages is not using runCommand anymore?"))
          # doom-emacs expects site-start.el in the correct place,
          # otherwise it will fail to start
          # bash
          + ''
            mkdir -p $out/share/emacs/site-lisp
            touch $out/share/emacs/site-lisp/site-start.el
          '';
      });
};
```

But this is very complicated, and I think it can be fixed in doom-emacs itself by adjusting the `site-lisp` load in `doom-cli.el` to not fail if the file doesn't exist. 

### Steps to reproduce

1. Using home-manager and Nix, add to your config:
```nix
programs.emacs = {
  enable = true;
  package = pkgs.emacs.pkgs.emacsWithPackages
    (epkgs: with epkgs; [ treesit-grammars.with-all-grammars vterm ]);
};
``` 
2. Run `doom sync`

### System Information

https://pastebin.com/gYBagNQd

**Comment by thiagokokada** [comment] 2024-07-12 00:02
Probably the same issue: https://github.com/doomemacs/doomemacs/issues/7681.

**Comment by hlissner** [comment] 2024-07-12 00:40
This doesn't make sense. Every `load` calls in those highlighted lines have been passed `t` for their `NOERROR` argument, which means they'll do nothing if the files don't exist.

Please produce a more complete backtrace by running `doom sync --debug`.

**Comment by hlissner** [comment] 2024-07-12 01:12
Could you show me the wrapper? (i.e. show me the contents of `cat $(which emacs)`)

I installed this (without home-manager) and there were no issues:

```nix
(emacsPackagesFor emacs-pgtk).emacsWithPackages (epkgs; with epkgs; [
  treesit-grammars.with-all-grammars
  vterm
])
```

Also tried with `nixpkgs.emacs29-pgtk` and still no issue, so home-manager's wrapper is suspect.

**Comment by hlissner** [comment] 2024-07-12 01:45
See https://github.com/doomemacs/doomemacs/issues/7681#issuecomment-2224266784.

I'll close this as a duplicate of #7681.

**Closed by hlissner** 2024-07-12 01:45 UTC
Labels: duplicate
