### ISSUE TITLE
doom/restart-and-restore wrong type argument: listp

### ISSUE THREAD

**Issue by guangxu-li** [doomemacs/doomemacs#6371] opened 2022-05-05 18:43 UTC
### What did you expect to happen?

1. Evaluate <SPC> q r   (doom/restart-and-restore)
2. Emacs close and reopen with a hook to restore the session saved in autosave

### What actually happened?

doom/restart-and-restore or `<SPC>-q-r`, then the wrong-type-argument error is triggered. It's always reproducible.

`wrong-type-argument: listp "--eval \"(add-hook 'window-setup-hook #'doom-load-session 100)\""`

```elisp
Debugger entered--Lisp error: (wrong-type-argument listp "--eval \"(add-hook 'window-setup-hook #'doom-load-s...")
  restart-emacs("--eval \"(add-hook 'window-setup-hook #'doom-load-s...")
  (unwind-protect (restart-emacs (combine-and-quote-strings (append (if debug (list "--debug-init")) (if (boundp 'chemacs-current-emacs-profile) (progn (list "--with-profile" chemacs-current-emacs-profile))) (list "--eval" "(add-hook 'window-setup-hook #'doom-load-session 1...")))))
  (let* ((confirm-kill-emacs confirm-kill-emacs)) (unwind-protect (restart-emacs (combine-and-quote-strings (append (if debug (list "--debug-init")) (if (boundp 'chemacs-current-emacs-profile) (progn (list "--with-profile" chemacs-current-emacs-profile))) (list "--eval" "(add-hook 'window-setup-hook #'doom-load-session 1..."))))))
  (progn (fset #'save-buffers-kill-emacs #'kill-emacs) (let* ((confirm-kill-emacs confirm-kill-emacs)) (unwind-protect (restart-emacs (combine-and-quote-strings (append (if debug (list "--debug-init")) (if (boundp ...) (progn ...)) (list "--eval" "(add-hook 'window-setup-hook #'doom-load-session 1...")))))))
  (unwind-protect (progn (fset #'save-buffers-kill-emacs #'kill-emacs) (let* ((confirm-kill-emacs confirm-kill-emacs)) (unwind-protect (restart-emacs (combine-and-quote-strings (append (if debug ...) (if ... ...) (list "--eval" "(add-hook 'window-setup-hook #'doom-load-session 1..."))))))) (fset #'save-buffers-kill-emacs old))
  (let* ((old (symbol-function #'save-buffers-kill-emacs))) (unwind-protect (progn (fset #'save-buffers-kill-emacs #'kill-emacs) (let* ((confirm-kill-emacs confirm-kill-emacs)) (unwind-protect (restart-emacs (combine-and-quote-strings (append ... ... ...)))))) (fset #'save-buffers-kill-emacs old)))
  doom/restart-and-restore(nil)
  #<subr funcall-interactively>(doom/restart-and-restore nil)
  apply(#<subr funcall-interactively> (doom/restart-and-restore nil))
  funcall-interactively(doom/restart-and-restore nil)
  #<subr call-interactively>(doom/restart-and-restore nil nil)
  apply(#<subr call-interactively> (doom/restart-and-restore nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> doom/restart-and-restore nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (doom/restart-and-restore nil nil))
  call-interactively(doom/restart-and-restore nil nil)
  command-execute(doom/restart-and-restore)

```

### Describe your attempts to resolve the issue

Based on the trace, restart-emacs expect list type, so I tried to manually modify the `.emacs.d/core/autoload/sessions.el:131`.

After removing the `(combine-and-quote-strings ...)` function but keeping the args generation related functions, the issue is resolved.

**Original**
```elisp
;;;###autoload
(defun doom/restart-and-restore (&optional debug)
  "Restart Emacs (and the daemon, if active).

If DEBUG (the prefix arg) is given, start the new instance with the --debug
switch."
  (interactive "P")
  (setq doom-autosave-session nil)
  (doom/quicksave-session)
  (save-some-buffers nil t)
  (letf! ((#'save-buffers-kill-emacs #'kill-emacs)
          (confirm-kill-emacs))
    (restart-emacs
     (combine-and-quote-strings
      (append (if debug (list "--debug-init"))
              (when (boundp 'chemacs-current-emacs-profile)
                (list "--with-profile" chemacs-current-emacs-profile))
              (list "--eval" "(add-hook 'window-setup-hook #'doom-load-session 100)"))))))

```

**After the modification**
```elisp
;;;###autoload
(defun doom/restart-and-restore (&optional debug)
  "Restart Emacs (and the daemon, if active).

If DEBUG (the prefix arg) is given, start the new instance with the --debug
switch."
  (interactive "P")
  (setq doom-autosave-session nil)
  (doom/quicksave-session)
  (save-some-buffers nil t)
  (letf! ((#'save-buffers-kill-emacs #'kill-emacs)
          (confirm-kill-emacs))
    (restart-emacs
      (append (if debug (list "--debug-init"))
              (when (boundp 'chemacs-current-emacs-profile)
                (list "--with-profile" chemacs-current-emacs-profile))
              (list "--eval" "(add-hook 'window-setup-hook #'doom-load-session 100)")))))

```

### Steps to reproduce

1. Install emacs 28.1 + default doom setup
3. Enter emacs and <SPC> q r

### System Information

https://pastebin.com/NfNtsGUq

**Comment by hlissner** [comment] 2022-05-05 19:02
Duplicate of #6219

**Closed by hlissner** 2022-05-05 19:02 UTC
Labels: duplicate
