### ISSUE TITLE
All the snippets, all the time?

### ISSUE THREAD

**Issue by gatlace** [doomemacs/doomemacs#6463] opened 2022-06-17 21:35 UTC
### What did you expect to happen?

Whenever I uncomment `:lang web`, it shouldn't impede copilot.el from working. Pressing tab should autocomplete, not create an html tag.

### What actually happened?

When I see a suggestion, if I haven't typed anything for the current word, it won't do anything. If I have typed in a word, it'll make it a tag. for example `async f` goes to `async < f >< /f >` and `async ...` just blinks. It's not a copilot.el issue because it works when it's allowed to.

### Describe your attempts to resolve the issue

I tried using different LSP's, and that's about as much as I could do. I've got it isolated so it's when I enable :lang web, not even +lsp

### Steps to reproduce

enable lsp, javascript +lsp and web +lsp, and install copilot.el

### System Information

https://pastebin.com/is0KMnZ7

**Comment by hlissner** [comment] 2022-06-17 22:15
This is due to [configuration for emmet-mode](https://github.com/doomemacs/doomemacs/blob/master/modules/lang/web/config.el#L16-L17). Either disable emmet-mode:

```elisp
;;; in $DOOMDIR/packages.el
(package! emmet-mode :disable t)
;; Don't forget to run `doom sync`
```

Or unbind the key:

```elisp
;;; in $DOOMDIR/config.el
(map! :after emmet-mode [tab] nil)
```

As this is not a bug I will close this, but feel free to follow up here.

**Closed by hlissner** 2022-06-17 22:15 UTC
Labels: invalid
