### ISSUE TITLE
Doom Emacs themes fail to detect truecolor support

### ISSUE THREAD

**Issue by tidux** [doomemacs/doomemacs#7037] opened 2023-01-09 07:24 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I started Emacs 27 in a terminal with Doom Emacs as the config.  I expected my theme (doom-old-hope) to load correctly.

### Current behavior

The theme started up in 256 color mode, with a deep blue background.

### Steps to reproduce

Open Emacs 27 on Debian stable in a TTY.  Look at the theme.  I confirmed that Emacs itself can generate truecolor codes by replacing .emacs.d with a known working Spacemacs configuration, which displayed truecolor support as expected.  This means it's not my terminal emulator, it's not my SSH connection, it's not my terminfo, and it's not the Emacs binary.  I even have the os/tty layer installed.  It therefore must be an issue with how Doom Emacs is detecting/loading color engine support at runtime.

### System Information

http://paste.debian.net/1266585/

**Comment by tidux** [comment] 2023-01-09 07:27
I should note that this limited color palette behavior is exhibited with both the stock doom-one and doom-old-hope themes, although the doom-one theme at least has a black background instead of bright blue.

**Comment by tidux** [comment] 2023-01-09 15:28
The behavior appeared initially with an Ubuntu 20.04 / Emacs 28 environment on a different machine, but exporting `COLORTERM=truecolor` and running `doom env` corrected it there, so this may be an Emacs 27 bug.

**Comment by hlissner** [comment] 2023-03-12 01:19
Enabling truecolor support is Emacs' jurisdiction, not Doom's. So long as Emacs is launched with the correct `TERM`, it should launch in truecolor mode. Unfortunately, as I cannot reproduce the issue (on st, urxvt, Termite, or Konsole), I'm not sure how else to diagnose this further. I will close this for now, since this is likely not a Doom issue, but feel free to follow up here if you unearth more leads.

**Closed by hlissner** 2023-03-12 01:19 UTC
Labels: invalid
