### ISSUE TITLE
Using some UTF-8 chars in a .py file freezes DoomEmacs

### ISSUE THREAD

**Issue by liar666** [doomemacs/doomemacs#7287] opened 2023-07-04 18:00 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I should be able to write any suite of UTF-8 chars in a Python file without (Doom)Emacs crashing

### Current behavior

NOTE: I upgraded DoomEmacs + lsp servers a few minutes ago.

*When typing "π₁" (UTF-8 "GREEK SMALL LETTER PI" & "SUBSCRIPT ONE") in a Python (.py) file, DoomEmacs freezes.*
Control can be regained for a few µsec by smashing C-g, but then it's lost again.

I've tried to create a backtrace by following:
https://discourse.doomemacs.org/t/what-is-a-backtrace-how-to-produce-them/85
Here is what I get:
```
 Debugger entered--entering a function:                                                                                                                                                                            
 * #f(compiled-function () #<bytecode 0x88325ed312a666e>)()                                                                                                                                                        
   font-lock-default-fontify-region(24 26 nil)                                                                                                                                                                     
   font-lock-fontify-region(24 26)                                                                                                                                                                                 
   #f(compiled-function (fun) #<bytecode 0x19a2bd4fff99403d>)(font-lock-fontify-region)                                                                                                                            
   run-hook-wrapped(#f(compiled-function (fun) #<bytecode 0x19a2bd4fff99403d>) font-lock-fontify-region)                                                                                                           
   jit-lock--run-functions(24 26)                                                                                                                                                                                  
   jit-lock-fontify-now(24 1524)                                                                                                                                                                                   
   jit-lock-function(24)                                                                                                                                                                                           
   redisplay_internal\ \(C\ function\)()
```
Hope that helps...

### Steps to reproduce

- Open a .py file
- Enter C-x 8 Return + GREEK SMALL LETTER PI
- Enter C-x 8 Return + SUBSCRIPT ONE

### System Information

https://gist.github.com/liar666/c64d9fa4a2fb742ee101fc3e84a59647

**Comment by freddez** [comment] 2024-07-12 06:56
I cannot reproduce the problem with emacs 29.3, ubuntu 24.04
https://gist.github.com/freddez/8e94edb6d8ccf738e33d6804664a7d47

**Comment by hlissner** [comment] 2024-07-12 07:04
Pauses/freezes/crashes when displaying unicode glyphs usually happen because the fallback font (`Symbola`) is not installed on the system. Make sure it is. It's included on some systems (Ubuntu being one of them, iirc), but not all.

In any case, I have no reason to suspect this is Doom issue, so I'll close this, but feel free to follow up here. With more leads or proof otherwise, I'd be happy to reopen this.

**Closed by hlissner** 2024-07-12 07:04 UTC
Labels: invalid
