### ISSUE TITLE
None workspace is created which can't be deleted

### ISSUE THREAD

**Issue by amrit3128** [doomemacs/doomemacs#7987] opened 2024-08-09 05:20 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I press `SPC TAB x` all work-spaces should be deleted

### Current behavior

A `none` workspace is created which can't be deleted 

### Steps to reproduce

Can be reproduced in the latest commit of doom emacs

### System Information

https://pastebin.com/dLVXDKjF

**Comment by hlissner** [comment] 2024-08-09 05:27
Duplicate of #7986

**Closed by hlissner** 2024-08-09 05:27 UTC
Labels: duplicate
