### ISSUE TITLE
Doom CLI error: Unknown specializer record

### ISSUE THREAD

**Issue by DiogoDoreto** [doomemacs/doomemacs#8188] opened 2024-12-01 17:28 UTC
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Doom CLI commands to not throw error

### Current behavior

After applying commit 169540ad3b19e611a125297cdfb87618f1418746, running any doom command on the CLI throws the error below. Reverting to just 1 commit before fixes the problem.

```
Error: error ("Unknown specializer record")
  mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode -0x1df2a0a1d2510ebe>))
  debug-early-backtrace()
  debug-early(error (error "Unknown specializer record"))
  error("Unknown specializer %S" record)
  #f(compiled-function (specializer) "Support for the catch-all t specializer which always matches." #<bytecode -0x1072e8257c728eb7>)(record)
  apply(#f(compiled-function (specializer) "Support for the catch-all t specializer which always matches." #<bytecode -0x1072e8257c728eb7>) record)
  #f(compiled-function (&rest args) #<bytecode -0x1511245255c5e6c5>)()
  #f(compiled-function (cl--cnm specializer) #<bytecode -0x1de2b772ab8e8dff>)(#f(compiled-function (&rest args) #<bytecode -0x1511245255c5e6c5>) record)
  apply(#f(compiled-function (cl--cnm specializer) #<bytecode -0x1de2b772ab8e8dff>) #f(compiled-function (&rest args) #<bytecode -0x1511245255c5e6c5>) record)
  #f(compiled-function (specializer) "Support for (head VAL) specializers.\nThese match if the argument is a cons cell whose car is `eql' to VAL." #<bytecode 0xde4adb57bb09aac>)(record)
  apply(#f(compiled-function (specializer) "Support for (head VAL) specializers.\nThese match if the argument is a cons cell whose car is `eql' to VAL." #<bytecode 0xde4adb57bb09aac>) record)
  #f(compiled-function (&rest args) #<bytecode -0x17e28ff256107e21>)()
  #f(compiled-function (cl--cnm type) #<bytecode -0x50b51dac55d1f94>)(#f(compiled-function (&rest args) #<bytecode -0x17e28ff256107e21>) record)
  apply(#f(compiled-function (cl--cnm type) #<bytecode -0x50b51dac55d1f94>) #f(compiled-function (&rest args) #<bytecode -0x17e28ff256107e21>) record)
  #f(compiled-function (type) "Support for dispatch on types defined by `cl-defstruct'." #<bytecode 0x89c2617c0351717>)(record)
  apply(#f(compiled-function (type) "Support for dispatch on types defined by `cl-defstruct'." #<bytecode 0x89c2617c0351717>) record)
  #f(compiled-function (&rest args) #<bytecode 0x174e9d7c1a7f5c23>)()
  #f(compiled-function (cl--cnm type) #<bytecode -0x11124d53687b83a2>)(#f(compiled-function (&rest args) #<bytecode 0x174e9d7c1a7f5c23>) record)
  apply(#f(compiled-function (cl--cnm type) #<bytecode -0x11124d53687b83a2>) #f(compiled-function (&rest args) #<bytecode 0x174e9d7c1a7f5c23>) record)
  #f(compiled-function (type) "Support for dispatch on builtin types.\nSee the full list and their hierarchy in `cl--typeof-types'." #<bytecode 0x19aec504889b8b7d>)(record)
  apply(#f(compiled-function (type) "Support for dispatch on builtin types.\nSee the full list and their hierarchy in `cl--typeof-types'." #<bytecode 0x19aec504889b8b7d>) record)
  #f(compiled-function (&rest args) #<bytecode -0xcd006b208e76112>)()
  #f(compiled-function (cl--cnm type) #<bytecode -0xab040bb62a2c523>)(#f(compiled-function (&rest args) #<bytecode -0xcd006b208e76112>) record)
  apply(#f(compiled-function (cl--cnm type) #<bytecode -0xab040bb62a2c523>) #f(compiled-function (&rest args) #<bytecode -0xcd006b208e76112>) record)
  #f(compiled-function (type) "Support for dispatch on types defined by `oclosure-define'." #<bytecode 0xc2a47f3818b98f3>)(record)
  apply(#f(compiled-function (type) "Support for dispatch on types defined by `oclosure-define'." #<bytecode 0xc2a47f3818b98f3>) record nil)
  cl-generic-generalizers(record)
  cl-generic-define-method(doom-copy nil ((val record) &optional deep?) nil (closure (t) (val &optional deep?) "Return a (optionally deep) copy of record VAL." (progn (if deep? (let* ((newval (copy-sequence val)) (idx 1) (--cl-var-- (length (cdr (cl-struct-slot-info (type-of val)))))) (while (<= idx --cl-var--) (aset newval idx (doom-copy (aref newval idx) t)) (setq idx (+ idx 1))) newval) (copy-sequence val)))))
  load-with-code-conversion("/nix/store/m1a7qx7l9qfn49wfq5c79ivx5y0fd7m7-source/lisp/doom-lib.el" "/nix/store/m1a7qx7l9qfn49wfq5c79ivx5y0fd7m7-source/lisp/doom-lib.el" nil t)
  require(doom-lib)
  load-with-code-conversion("/nix/store/m1a7qx7l9qfn49wfq5c79ivx5y0fd7m7-source/lisp/doom.el" "/nix/store/m1a7qx7l9qfn49wfq5c79ivx5y0fd7m7-source/lisp/doom.el" nil t)
  load("/nix/store/m1a7qx7l9qfn49wfq5c79ivx5y0fd7m7-source/lisp/doom" nil t nil must-suffix)
  (if (file-exists-p (concat doom ".el")) (load doom nil (not init-file-debug) nil 'must-suffix) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list #'(lambda nil (expand-file-name "init.el" user-emacs-directory)) nil (nth 2 args)))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil)
  (let ((load-suffixes '(".elc" ".el")) (doom (expand-file-name "lisp/doom" user-emacs-directory))) (if (file-exists-p (concat doom ".el")) (load doom nil (not init-file-debug) nil 'must-suffix) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list #'(lambda nil (expand-file-name "init.el" user-emacs-directory)) nil (nth 2 args)))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil))
  (if (let ((load-suffixes '(".elc" ".el")) (doom (expand-file-name "lisp/doom" user-emacs-directory))) (if (file-exists-p (concat doom ".el")) (load doom nil (not init-file-debug) nil 'must-suffix) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list #'(lambda nil (expand-file-name "init.el" user-emacs-directory)) nil (nth 2 args)))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil)) (doom-initialize (not noninteractive)) (load user-init-file 'noerror (not init-file-debug) nil 'must-suffix))
  (let (file-name-handler-alist) (if noninteractive (progn (setq gc-cons-threshold 134217728) (setq gc-cons-percentage 1.0)) (setq gc-cons-threshold most-positive-fixnum)) (setq load-prefer-newer noninteractive) (if (getenv-internal "DEBUG") (progn (progn (setq init-file-debug t) (setq debug-on-error t)))) (let ((command-line-args (if noninteractive nil command-line-args)) (profile (or (car (cdr (member "--profile" command-line-args))) (getenv-internal "DOOMPROFILE")))) (if (null profile) (let ((init-dir (or (car (cdr (member "--init-directory" command-line-args))) (getenv-internal "EMACSDIR")))) (if (null init-dir) (if noninteractive (progn (setq user-emacs-directory (file-name-directory (file-truename load-file-name))))) (setq command-switch-alist (cons (cons "--init-directory" #'(lambda (_) (car-safe (prog1 argv (setq argv (cdr argv)))))) command-switch-alist)) (setq user-emacs-directory (expand-file-name init-dir)))) (setq command-switch-alist (cons (cons "--profile" #'(lambda (_) (car-safe (prog1 argv (setq argv (cdr argv)))))) command-switch-alist)) (setenv "DOOMPROFILE" profile) (or (load (let ((windows? (memq system-type '(ms-dos windows-nt cygwin)))) (expand-file-name (format (or (getenv-internal "DOOMPROFILELOADFILE") (file-name-concat (if windows? "doomemacs/data" "doom") "profiles.%d.elc")) emacs-major-version) (or (if windows? (getenv-internal "LOCALAPPDATA")) (getenv-internal "XDG_DATA_HOME") "~/.local/share"))) 'noerror (not init-file-debug) 'nosuffix) (user-error "Profiles not initialized yet; run 'doom sync' first")))) (if (let ((load-suffixes '(".elc" ".el")) (doom (expand-file-name "lisp/doom" user-emacs-directory))) (if (file-exists-p (concat doom ".el")) (load doom nil (not init-file-debug) nil 'must-suffix) (prog1 (defalias 'startup--load-user-init-file@reroute-to-profile #'(lambda (args) (list #'(lambda nil (expand-file-name "init.el" user-emacs-directory)) nil (nth 2 args)))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@reroute-to-profile)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t) (setq gc-cons-threshold (* 16 1024 1024)) nil)) (doom-initialize (not noninteractive)) (load user-init-file 'noerror (not init-file-debug) nil 'must-suffix)))
  load-with-code-conversion("/nix/store/m1a7qx7l9qfn49wfq5c79ivx5y0fd7m7-source/early-init.el" "/nix/store/m1a7qx7l9qfn49wfq5c79ivx5y0fd7m7-source/early-init.el" nil t)
  load("/nix/store/m1a7qx7l9qfn49wfq5c79ivx5y0fd7m7-source/early-init.el" nil nomessage nosuffix)
  (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom))
  (or (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file))
  (let* ((bin-dir (file-name-directory (file-truename load-file-name))) (init-file (expand-file-name "../early-init.el" bin-dir))) (or (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file)))
  (condition-case e (let* ((bin-dir (file-name-directory (file-truename load-file-name))) (init-file (expand-file-name "../early-init.el" bin-dir))) (or (and (load init-file nil 'nomessage 'nosuffix) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file))) (user-error (message "Error: %s" (car (cdr e))) (kill-emacs 2)))
  load-with-code-conversion("/nix/store/m1a7qx7l9qfn49wfq5c79ivx5y0fd7m7-source/bin/doom" "/nix/store/m1a7qx7l9qfn49wfq5c79ivx5y0fd7m7-source/bin/doom" nil t)
  command-line-1(("--load" "/home/dog/.config/emacs/bin/doom" "--" "sync"))
  command-line()
  normal-top-level()
Unknown specializer record
```

### Steps to reproduce

Upgrade doomemacs to commit 169540ad3b19e611a125297cdfb87618f1418746 or later and then try to run `doom sync` on the terminal.

Please let me know if  there's anything more I could provide to help the investigation.

### System Information

https://pastebin.com/VZyKUzbA

**Comment by gpetrini** [comment] 2024-12-01 17:47
The same happened to me. I even tried to re-install emacs and install doom from scratch.

I am using the snap version of emacs.

**Comment by TJSoler** [comment] 2024-12-01 18:04
Using this commit 9c8cfaadde1ccc96a780d713d2a096f0440b9483
restores functionality for me.

I don't know enough lisp to fix it, but if I remove this chunk of code (lines 336-343), the CLI works for me again:

https://github.com/doomemacs/doomemacs/commit/169540ad3b19e611a125297cdfb87618f1418746#diff-347022e99c0e1168eb93f6296af8ce138a8f4a2d4897627288f841dd3fb82312R336-R343

**Comment by hlissner** [comment] 2024-12-01 20:01
Duplicate of #8186

**Closed by hlissner** 2024-12-01 20:00 UTC
Labels: is:bug, needs-triage
