### ISSUE TITLE
Cannot install flycheck-grammalecte / flymake-grammarly / flymake-languagetool

### ISSUE THREAD

**Issue by liar666** [doomemacs/doomemacs#7316] opened 2023-07-28 23:23 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

- I have a working config
- I open `~/.doom/packages.el`
- I insert `(package! flymake-grammarly)` or `(package! flymake-languagetool)` or `(package! flymake-languagetool)`

As they are in MELPA, I should be able to configure (in `config.org`) and use these packages

### Current behavior

Instead I get errors:
- In emacs: `cannot find <package_name>` (or something similar) when loading the `(usepackage! <package_name> ...)` from `config.org/el`
- With `doom sync/upgrade` 
```
$ doom sync
> Tangling your literate config...
  ✓ Done tangling 1 file(s)!
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.emacs.d/.local/env
  > Installing packages...
    > Building flymake-languagetool...
    x There was an unexpected runtime error
      Message: Error with packages
      Details: ("flymake-languagetool" (error "flymake-languagetool.el:0:0: error: cl-assertion-failed: ((> (point) output-start))"))
      Backtrace:
        (signal doom-package-error ("flymake-languagetool" (error "flymake-languagetool.el:0:0: error: cl-assertion-failed: ((> (point) output-start))")))
        (condition-case e (let ((straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (let* ((commit (and t (cdr (assoc pkg pinned))))) (if commit (doom-print (doom-print--format (doom-prin...
        (progn (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-packages--cli-recipes-update)) (condition-case e (let ((straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _)...
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (cdr (plist-member --cl-rest-- ':recipe)))) (package (car (cdr (plist-member --cl-rest-- ':package)))) (type (car (cdr (plist-m...
        (cl-destructuring-bind (&key recipe package type local-repo &allow-other-keys) (append (list :recipe recipe) recipe) (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-packages--cli-re...
        (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-packages--cli-recipes-update)) (conditio...
        (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-pa...
        (while --dolist-tail-- (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-directory-p (straight--repos-dir lo...
        (let ((--dolist-tail-- recipes)) (while --dolist-tail-- (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-di...
        (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg built)))) straight-u...
        (and t (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg built)))) str...
        (let* ((built (and t (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg...
      ! Wrote extended backtrace to ~/.emacs.d/.local/state/logs/cli.doom.230729011147.3674486.error
    ! Script was abruptly aborted, leaving Doom in an incomplete state!
    - Run 'doom sync' to repair it.
```
(NOTE the funy reference to solve the problem running `doom sync` when it is the exact command I was running :) )

I also tried adding `:recipe/:host/:repo` pointing to the respective code of the packages on `github` in `packages.el. But result is the same. 

### Steps to reproduce

- Start from a working config
- Open `~/.doom/packages.el`
- Insert `(package! flymake-grammarly)` or `(package! flymake-languagetool)` or `(package! flymake-languagetool)` or the equivalent commands pointing to github repos.

### System Information

https://pastebin.com/J73k8jrW

**Comment by liar666** [comment] 2023-07-31 12:50
I get a similar error with `tabnine`:
```
> Tangling your literate config...
  ✓ Done tangling 1 file(s)!
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.emacs.d/.local/env
  > Installing packages...
    > Updating recipe repos...
    > Cloning tabnine... for emacsmirror-mirror...
    > Building tabnine...
    > Building tabnine > Cloning editorconfig-emacs (for editorconfig)...
    > Building tabnine > Building editorconfig...
    x There was an unexpected runtime error
      Message: Error with packages
      Details: ("tabnine" (error "editorconfig-conf-mode.el:0:0: error: cl-assertion-failed: ((> (point) output-start))"))
      Backtrace:
        (signal doom-package-error ("tabnine" (error "editorconfig-conf-mode.el:0:0: error: cl-assertion-failed: ((> (point) output-start))")))
        (condition-case e (let ((straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (let* ((commit (and t (cdr (assoc pkg pinned))))) (if commit (doom-print (doom-print--format (doom-prin...
        (progn (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-packages--cli-recipes-update)) (condition-case e (let ((straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _)...
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (cdr (plist-member --cl-rest-- ':recipe)))) (package (car (cdr (plist-member --cl-rest-- ':package)))) (type (car (cdr (plist-m...
        (cl-destructuring-bind (&key recipe package type local-repo &allow-other-keys) (append (list :recipe recipe) recipe) (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-packages--cli-re...
        (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-packages--cli-recipes-update)) (conditio...
        (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-pa...
        (while --dolist-tail-- (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-directory-p (straight--repos-dir lo...
        (let ((--dolist-tail-- recipes)) (while --dolist-tail-- (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-di...
        (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg built)))) straight-u...
        (and t (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg built)))) str...
        (let* ((built (and t (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg...
      ! Wrote extended backtrace to ~/.emacs.d/.local/state/logs/cli.doom.230731144925.850107.error
    ! Script was abruptly aborted, leaving Doom in an incomplete state!
    - Run 'doom sync' to repair it.
    ✓ Finished in 7.43022s
```

**Comment by Jdogzz** [comment] 2023-09-17 23:15
@liar666 Are you still able to reproduce this? I was able to install all those packages without issue.

https://pastebin.com/bpuradKh

**Comment by hlissner** [comment] 2023-11-29 19:31
Keep in mind that `(error "....el:0:0: error: cl-assertion-failed: ((> (point) output-start))"))` errors almost always mean either:

1. The package wasn't downloaded properly (file corruption, network connection failures, etc),
2. Or the package's "primary" file (e.g. for flymake-languagetool, it's flymake-languagetool.el) does not have a valid [library header](https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers) -- the most common reason for that is a syntax error in the `Package-Requires` header.

However, the majority of the time this error is reported, it's due to network connectivity issues (especially where non-github sources are involved). For example, flymake-grammalecte is hosted on git.umaneti.net, whose uptime I can't trust as much as I can github.com's. I intend to set up mirrors at https://github.com/doomelpa eventually to get around that in the future.

In any case, I'll close this for now, since it's not something Doom can do anything about (besides improving the error message and setting up those mirrors). In v3.0, I plan to switch Doom to a new package manager ([Elpaca](https://github.com/progfolio/elpaca)), which will make it easier for me to handle (and translate) arbitrary errors better.

**Closed by hlissner** 2023-11-29 19:31 UTC
Labels: invalid
