### ISSUE TITLE
When opened a agenda view, capture will not work correctly

### ISSUE THREAD

**Issue by mrdylanyin** [doomemacs/doomemacs#7270] opened 2023-06-10 13:19 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I use "SPC n a a" to open the agenda view, using "SPC n n t" to capture a note will work correctly as below:
![image](https://github.com/doomemacs/doomemacs/assets/72154328/16372343-953e-41a8-9dab-3858c596f164)

### Current behavior

When I use "SPC n a a" to open the agenda view, using "SPC n n t" to capture a note here's happened:
![image](https://github.com/doomemacs/doomemacs/assets/72154328/5ed6afd1-03f3-4b8a-b3e3-cf1bc129bf32)

Here is the *Message* buffer:
```
Press key for agenda command:
Clipboard pasted as level 2 subtree
Not enabling jit-lock: it does not work in indirect buffer
org-mode restarted
```

### Steps to reproduce

1. "SPC n a a" open the agenda view
2. "SPC n n t" capture a note

### System Information

https://pastebin.com/0s5hbwjA

**Comment by Jdogzz** [comment] 2023-09-25 01:33
It looks like this is a duplicate of #5714?

**Closed** 2023-10-07 15:29 UTC
Labels: duplicate
