### ISSUE TITLE
Can't install flymake-languagetool

### ISSUE THREAD

**Issue by liar666** [doomemacs/doomemacs#7353] opened 2023-08-17 18:18 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I should be able to install/use `flymake-languagetool` by just adding it to `packages.el` since it's in MELPA.

### Current behavior

If I add
```
(package! flymake-languagetool) 
```
in `packages.el`, then run `doom sync`, I get:

```
> Tangling your literate config...
  ✓ Done tangling 1 file(s)!
> Synchronizing "default" profile...
  > Installing packages...
    > Building flymake-languagetool...
    x There was an unexpected runtime error
      Message: Error with packages
      Details: ("flymake-languagetool" (error "flymake-languagetool.el:0:0: error: cl-assertion-failed: ((> (point) output-start))"))
      Backtrace:
        (signal doom-package-error ("flymake-languagetool" (error "flymake-languagetool.el:0:0: error: cl-assertion-failed: ((> (point) output-start))")))
        (condition-case e (let ((straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (let* ((commit (and t (cdr (assoc pkg pinned))))) (if commit (doom-print (doom-print--format (doom-prin...
        (progn (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-packages--cli-recipes-update)) (condition-case e (let ((straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _)...
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (cdr (plist-member --cl-rest-- ':recipe)))) (package (car (cdr (plist-member --cl-rest-- ':package)))) (type (car (cdr (plist-m...
        (cl-destructuring-bind (&key recipe package type local-repo &allow-other-keys) (append (list :recipe recipe) recipe) (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-packages--cli-re...
        (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-packages--cli-recipes-update)) (conditio...
        (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-pa...
        (while --dolist-tail-- (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-directory-p (straight--repos-dir lo...
        (let ((--dolist-tail-- recipes)) (while --dolist-tail-- (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-di...
        (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg built)))) straight-u...
        (and t (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg built)))) str...
        (let* ((built (and t (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg...
      ! Wrote extended backtrace to ~/.emacs.d/.local/state/logs/cli.doom.230817201412.2347424.error
    ! Script was abruptly aborted, leaving Doom in an incomplete state!
    - Run 'doom sync' to repair it.
    ✓ Finished in 1.43741s
```

### Steps to reproduce

- add `(package! flymake-languagetool)` in `packages.el`
- run `doom sync`

### System Information

https://pastebin.com/0Hn9G1ay

**Comment by liar666** [comment] 2023-08-17 18:59
Same thing happens with `keycast` which is also in MELPA.

```
$ doom sync
> Tangling your literate config...
  ✓ Done tangling 1 file(s)!
> Synchronizing "default" profile...
  > Installing packages...
    > Updating recipe repos...
    > Cloning keycast... for emacsmirror-mirror...
    > Building keycast...
    x There was an unexpected runtime error
      Message: Error with packages
      Details: ("keycast" (error "keycast.el:0:0: error: cl-assertion-failed: ((> (point) output-start))"))
      Backtrace:
        (signal doom-package-error ("keycast" (error "keycast.el:0:0: error: cl-assertion-failed: ((> (point) output-start))")))
        (condition-case e (let ((straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (let* ((commit (and t (cdr (assoc pkg pinned))))) (if commit (doom-print (doom-print--format (doom-prin...
        (progn (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-packages--cli-recipes-update)) (condition-case e (let ((straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _)...
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (cdr (plist-member --cl-rest-- ':recipe)))) (package (car (cdr (plist-member --cl-rest-- ':package)))) (type (car (cdr (plist-m...
        (cl-destructuring-bind (&key recipe package type local-repo &allow-other-keys) (append (list :recipe recipe) recipe) (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-packages--cli-re...
        (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-packages--cli-recipes-update)) (conditio...
        (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-pa...
        (while --dolist-tail-- (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-directory-p (straight--repos-dir lo...
        (let ((--dolist-tail-- recipes)) (while --dolist-tail-- (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-di...
        (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg built)))) straight-u...
        (and t (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg built)))) str...
        (let* ((built (and t (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg...
      ! Wrote extended backtrace to ~/.emacs.d/.local/state/logs/cli.doom.230817205759.2359983.error
    ! Script was abruptly aborted, leaving Doom in an incomplete state!
    - Run 'doom sync' to repair it.
    ✓ Finished in 5.35589s
```

**Comment by liar666** [comment] 2023-08-17 19:01
Similar as issue #7316

But this time I reconfigured my whole `config.org` from scrtach

**Comment by Jdogzz** [comment] 2023-09-17 23:17
@liar666 (I see you commented about a similar set of packages from #7316 that I just replied to, but just for posterity) Are you still able to reproduce this? I was able to install all these packages without issue.

https://pastebin.com/bpuradKh

**Comment by GMTSE** [comment] 2023-11-28 09:43
I still had problems with the following packages:
```
keycast
shift-number
flymake-languagetool
yatemplate
gscholar-bibtex
academic-phrases
julia-mode
aichat
```
I tried to switch back to using `packages.el` for these and only `yatemplate` seems to remain broken (does not load my templates when I open some particular file types, whereas the config is there...)

**Comment by hlissner** [comment] 2023-11-29 19:22
Duplicate of #7316.

**Closed by hlissner** 2023-11-29 19:22 UTC
Labels: duplicate
