### ISSUE TITLE
`doom upgrade` fails with "file is missing: packages.el"

### ISSUE THREAD

**Issue by monkey-w1n5t0n** [doomemacs/doomemacs#6700] opened 2022-08-19 07:41 UTC
### What did you expect to happen?

`doom upgrade` to complete successfully.

### What actually happened?

On `master` branch, up-to-date with `origin/master`
```
➜  ~ doom upgrade
> Preparing to upgrade Doom Emacs and its packages...
- A new version of Doom Emacs is available!

    Old revision: c2f8476c86 (7 weeks ago)
    New revision: 4c9df9bfc6 (16 hours ago)

Link to diff: https://github.com/doomemacs/doomemacs/compare/c2f8476c8641fcc9a1371d873ed3b5924952a059...4c9df9bfc63d2c3a9e20e20deaa854072e379f47
View the comparison diff in your browser? (y or n) n
Proceed with upgrade? (y or n) y
> Upgrading Doom Emacs...
  > Cleaning .elc files
    - No elc files to clean
  x There was an unexpected runtime error
    Message: File is missing
    Details: ("Opening input file" "No such file or directory" "/home/w1n5t0n/.emacs.d/core/packages.el")
    Backtrace:
      (insert-file-contents "/home/w1n5t0n/.emacs.d/core/packag...
      (progn (insert-file-contents (doom-path doom-core-dir "pa...
      (unwind-protect (progn (insert-file-contents (doom-path d...
      (save-current-buffer (set-buffer temp-buffer) (unwind-pro...
      (let ((temp-buffer (generate-new-buffer " *temp*" t))) (s...
      (doom-upgrade--get-straight-recipe)
      (equal straight-recipe (doom-upgrade--get-straight-recipe))
      (if (equal straight-recipe (doom-upgrade--get-straight-re...
      (let ((straight-recipe (doom-upgrade--get-straight-recipe...
      (let ((doom-print-indent (+ (if t doom-print-indent-incre...
      (if (not (or auto-accept-p (y-or-n-p "Proceed with upgrad...
      (cond ((and (null this-rev) (null new-rev)) (error "Faile...
    ! Wrote extended backtrace to ~/.emacs.d/.local/logs/cli.doom.220819080242.69766.error
  ✓ Finished in 19.84964s
```

It seems to come from this line:
https://github.com/doomemacs/doomemacs/blob/master/lisp/cli/upgrade.el#L157

In my already-running Emacs instance, the value of `doom-core-dir` was `$HOME/.emacs.d/core`, which does not exist.

### Describe your attempts to resolve the issue

Did a fresh `git clone`, ran `doom sync` and then `doom upgrade` and it worked, but not really a fix per se.

### Steps to reproduce

Run `doom upgrade` when on the version at `c2f8476c86`.

### System Information

https://pastebin.com/6eFdTq20 (after successful upgrade as mentioned above)

**Comment by hlissner** [comment] 2022-08-19 09:09
Duplicate of #6598.

See https://github.com/doomemacs/doomemacs/issues/6598#issuecomment-1200309436.

**Closed by hlissner** 2022-08-19 09:09 UTC
Labels: duplicate
