### ISSUE TITLE
doom install hangs compiling final file

### ISSUE THREAD

**Issue by jeffkowalski** [doomemacs/doomemacs#6653] opened 2022-08-09 03:06 UTC
### What did you expect to happen?

`doom install` on a fresh install should proceed without issue

### What actually happened?

When I issue `doom install` after a fresh git-get from the main repo, I see
```
...
  > Building org-super-agenda > Building ts...
  > Building org-super-agenda...
  > Cloning org-capture-pop-frame...
  > Building org-capture-pop-frame...
  > Cloning org-cua-dwim...
  > Building org-cua-dwim...
  > Building web-server...
  > Cloning org-ehtml...
  > Building org-ehtml...
  > Cloning atomic-chrome...
  > Building atomic-chrome...
  > Building atomic-chrome > Cloning emacs-websocket...
  > Building atomic-chrome > Building websocket...
  > Building atomic-chrome...
  > Cloning zop-to-char...
  > Building zop-to-char...
  > Cloning solarized-emacs (for solarized-theme)...
  > Building solarized-theme...
  > Natively compiling 1 files...
```
And here at that last line it hangs forever

### Describe your attempts to resolve the issue

If I `C-c`  at the terminal, the process aborts, and when I subsequently invoke `emacs` all appears well. 
I suspect whatever that last package was, it wasn't compiled, but I may be interpreting it at runtime instead.

### Steps to reproduce

1. Download/clone emacs per instructions on this site
2. Issue `doom install`

### System Information

https://pastebin.com/1Bqnp16u

**Comment by pratikvn** [comment] 2022-08-09 06:38
I think this is a known issue due to vterm or some other package needing input when compiling natively. [See workaround here](https://github.com/doomemacs/doomemacs/issues/5592#issuecomment-945919856)

**Comment by hlissner** [comment] 2022-08-09 12:30
Duplicate of #5592.

**Closed by hlissner** 2022-08-09 12:30 UTC
Labels: duplicate
