### ISSUE TITLE
Getting "Doom hasn't been initialized yet" after a recent doom upgrade

### ISSUE THREAD

**Issue by jamesperez2005** [doomemacs/doomemacs#7338] opened 2023-08-06 05:51 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I expected Emacs to load as usual

### Current behavior

Opening Emacs after a recent doom upgrade gets the:
```
Doom hasn't been initialized yet; did you remember to run 'doom sync' in the shell?: /Users/rotemy/.emacs.d/.local/etc/@/init.28.elc
```
message

### Steps to reproduce

1. Doom upgrade
2. Open emacs

I also verified with a clean installation (deleting my private config + ~/.emacs.d and re-cloning and installing as per the docs)

### System Information

https://pastebin.com/bPAWHyQV

**Comment by jamesperez2005** [comment] 2023-08-06 06:55
Ok, found the isssue. My emacs-plus installation jumped to v29 which is not yet supported

**Comment by jamesperez2005** [comment] 2023-08-06 07:12
Leaving the issue open since this is a real problem - people installing emacs-plus like the guide suggests now are automatically upgraded to 29.1 whenever brew upgrade is run. This means doom emacs gets broken without any action being taken.

When do we expect to see 29.1 being officially supported?

**Comment by yanboyang713** [comment] 2023-08-06 11:29
I faced the same issue, emacs 29.1 does not support hydra-ivy, when I load ivy.
```
error eager macro-expansion failure void-variable hydra-ivy/params
```

**Comment by harabat** [comment] 2023-08-07 17:18
After updating Emacs to 29.1 (on purpose), I faced this issue but was able to solve it by deleting `~/.emacs.d/.local/` and running `doom upgrade `, haven't run into any issues yet. 

It's not supposed to be supported, so something will break sooner or later, but hopefully this informal testing will help contribute some issues/fixes when Doom officially starts supporting Emacs 29.

**Comment by ineu** [comment] 2023-08-08 07:07
JFYI: The note on Emacs 29 not being supported was added 1.5 years ago: https://github.com/doomemacs/doomemacs/commit/16fe83ef0e4a4f543bf2ca9204c96d0e67e314e8


Now Emacs 29.1 is out and has replaced Emacs 28 in the Arch repos, so it should be stable enough.

**Comment by bittopaz** [comment] 2023-08-10 04:31
I had exact the same error, and got it resolved via uninstall and the install Emacs.

**Comment by vvzen** [comment] 2023-08-12 14:12
I had a similar issue since I am on arch and I didn't realize that my emacs installation got bumped to 29.1 - it was enough to just `doom build && doom sync`, as it says here: https://discourse.doomemacs.org/t/how-to-upgrade-emacs-properly/2559 .

I have been on 29.1 for a week or so now and I didn't see any major issue running doom (both on macOS and gnu/linux).
To get more context, the commit message posted by @ineu says it clearly:
>  docs: don't claim to support 29 (HEAD)
I'm pulling support for Emacs 29+ (HEAD). It's too volatile and becomes
unusuable from week to week. Use Emacs 28!

So more than anything in particular in 29.1, it was a generic comment given Emacs 29 was moving too fast? I'll update here if I run into inconsistencies, but if you want to live on the edge, 29.1 seems fine (no major blockers) so far.

**Comment by rallyemax** [comment] 2023-08-15 16:17
It looks like 29.1 might be running OK, but if some things remain broken after reinstalling packages (or the slightly cleaner package reinstallation method of deleting `~/.config/emacs/.local` and running `doom sync`, see [docs](https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#updowngrading-emacs)), there shouldn't be any need to revert all the way back to v28. According to [this Doom Discourse thread](https://discourse.doomemacs.org/t/emacs-head-30-0-50-support/3241/6), v29.0.60 has been officially supported since March, and at least one person reported on that thread that they've been running v29.0.90 without any problems.

For what it's worth, I had been running v29.0.60 since April-ish and more recently I've been on v29.0.92 without any noticeable problems caused by emacs itself.

**Comment by ineu** [comment] 2023-08-16 15:11
For me 29 is somewhat tricky to use because some key bindings are missing: a half of the `space` commands and almost all of the `space b` commands, feels like they are not properly initialized. May be related to my configuration though.

**Comment by hlissner** [comment] 2024-09-11 07:16
There are a lot of mixed issues reported here.

> For me 29 is somewhat tricky to use because some key bindings are missing: a half of the space commands and almost all of the space b commands, feels like they are not properly initialized. May be related to my configuration though.

When keybinds go missing, it means an error has occurred *OR* the `:config default` module *isn't* at the end of your `doom!` block (load order matters).

> So more than anything in particular in 29.1, it was a generic comment given Emacs 29 was moving too fast? I'll update here if I run into inconsistencies, but if you want to live on the edge, 29.1 seems fine (no major blockers) so far.

What that commit message was referring to was the fact that 29.x was the "bleeding edge" of Emacs, and was introducing breaking changes very rapidly, which was getting hard for me to support, so I dropped official support for it, at the time.

Today, Doom officially supports Emacs 27-30 (though, I'll be dropping 27.x support soon), and *unofficially* supports 31 (which I use). So long as you run `doom sync` after up/downgrading Emacs itself, you shouldn't run into this issue. As this is no longer relevant, I will close this, but feel free to follow up here. Thanks for bringing it to my attention, in any case!

**Closed by hlissner** 2024-09-11 07:16 UTC
Labels: invalid
