### ISSUE TITLE
Recipe for company-tabnine is broken

### ISSUE THREAD

**Issue by liar666** [doomemacs/doomemacs#7774] opened 2024-03-29 16:25 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Adding `(package! company-tabnine)` in `init.el` should work straight away.

### Current behavior

Instead I get:
``` 
   > Cloning company-tabnine...csmirror-mirror...
      - Checked out nil
    > Building company-tabnine...
    x There was an unexpected runtime error
      Message: Error with packages
      Details: ("company-tabnine" (error "company-tabnine.el:0:0: error: cl-assertion-failed: ((> (point) output-start))"))
      Backtrace:
        (signal doom-package-error ("company-tabnine" (error "company-tabnine.el:0:0: error: cl-assertion-failed: ((> (point) output-start))")))
        (condition-case e (let ((straight-vc-git-post-clone-hook (cons #'(lambda (&rest --cl-rest--) "\n\n(fn &key REPO-DIR COMMIT &allow-other-keys)" (let* ((repo-dir (car (cdr (plist-member --cl-rest-- ':r...
        (let ((repo-dir (straight--repos-dir (or local-repo package))) (build-dir (straight--build-dir package))) (if force-p nil (let* ((build (if (plist-member recipe :build) (plist-get recipe :build) t)) ...
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (package (car (cdr (plist-member --cl-rest-- ':package)))) (local-repo (car (cdr (plist-member --cl-rest-- ':local-repo)))) (recipe (car (cd...
        (cl-destructuring-bind (&key package local-repo recipe &allow-other-keys) (append (list :recipe recipe) recipe) (let ((repo-dir (straight--repos-dir (or local-repo package))) (build-dir (straight--bu...
        (straight--with-plist (append (list :recipe recipe) recipe) (package local-repo recipe) (let ((repo-dir (straight--repos-dir (or local-repo package))) (build-dir (straight--build-dir package))) (if f...
        (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (package local-repo recipe) (let ((repo-dir (straight--repos-dir (or local-repo package))) (build-dir...
        (while --dolist-tail-- (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (package local-repo recipe) (let ((repo-dir (straight--repos-dir (or local-rep...
        (let ((--dolist-tail-- recipes)) (while --dolist-tail-- (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (package local-repo recipe) (let ((repo-dir (...
        (let* ((recipes recipes) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg built)))) straight-use-package-pre-buil...
        (and t (let* ((recipes recipes) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg built)))) straight-use-package-p...
        (let* ((built (and t (let* ((recipes recipes) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg built)))) straight...
```

Even using `(package! company-tabnine :recipe (:host github :repo "TommyX12/company-tabnine"))` (as per documentation found on the web) fails

### Steps to reproduce

1. Have a working DoomEmacs
2. Add `(package! company-tabnine)` in `init.el`
3. Run `doom sync`
4. Get error `cl-assertion-failed: ((> (point) output-start))"))`

### System Information

https://pastebin.com/4nHpaCqy

**Comment by hlissner** [comment] 2024-03-29 16:34
I can't reproduce this. This may simply be a connection issue. Try deleting the local repo before trying again. I.e.

```sh
rm -rf ~/.emacs.d/.local/straight/{repos,build-*}/company-tabnine
doom sync
```

**Comment by hlissner** [comment] 2024-03-29 18:17
Closing because duplicate of #7530.

**Closed by hlissner** 2024-03-29 18:17 UTC
Labels: duplicate
