### ISSUE TITLE
doom/restart-and-restore not working with Emacs 28.1.50

### ISSUE THREAD

**Issue by darrenkenny** [doomemacs/doomemacs#6376] opened 2022-05-06 10:03 UTC
### What did you expect to happen?

I should be able to restart emacs with 'SPC q r' - that doesn't work any more.

### What actually happened?

Got an error:

```
unwind-protect: Wrong type argument: listp, "--eval \"(add-hook 'window-setup-hook #'doom-load-session 100)\""
```

This appears to have happened with the change:

- 56686f677a5d fix(lib): improper quoting in restart-emacs command

### Describe your attempts to resolve the issue

Backing out that change fixes the issue, or alternatively, just quitting and then reloading the session manually on restart.

### Steps to reproduce

1. Open Emacs
2. Type: SPC q r

Simple as that.

### System Information

https://pastebin.com/czswAA1R

**Comment by TK-WF** [comment] 2022-05-06 14:39
This is happening for me as well, but I am not sure exactly at which Emacs version.

Actually all issues I am having with Doom started when I upgraded to 28.1 (of course).

**Comment by shelper** [comment] 2022-05-06 18:47
same issue here.

**Comment by teeann** [comment] 2022-05-07 07:36
same

**Comment by maikol-solis** [comment] 2022-05-08 17:46
Duplicated of #6219

**Comment by hlissner** [comment] 2022-05-09 13:25
Duplicate of #6219

**Closed by hlissner** 2022-05-09 13:25 UTC
Labels: duplicate
