### ISSUE TITLE
Weird ligature issue in javascript (rjsx) mode where they shrink in size or get replaced

### ISSUE THREAD

**Issue by GuessWhatBBQ** [doomemacs/doomemacs#6907] opened 2022-10-22 14:32 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Same as issue #3837

### Current behavior

Same as issue #3837

### Steps to reproduce

1. Open a javascript file.
2. Write an arrow function and move the mouse away from `=>`

### System Information

https://pastebin.com/8sT7vDzx

**Comment by GuessWhatBBQ** [comment] 2022-10-22 14:35
This solved the issue for me. I just wanted somewhere official to document this for anyone else facing the issue and coming across the aforementioned issue

```lisp
(after! js
  (setq-default js--prettify-symbols-alist '()))

```

**Comment by hlissner** [comment] 2022-10-22 15:15
Duplicate of #3837

**Closed by hlissner** 2022-10-22 15:15 UTC
Labels: duplicate
