### ISSUE TITLE
Doom doesn't respect buffers stored in server, but deletes buffer with kill-frame

### ISSUE THREAD

**Issue by ReneFroger** [doomemacs/doomemacs#8150] opened 2024-11-05 22:56 UTC
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [ ] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*. I believe this is not related to the stable release of unstable release of Emacs.

### Expected behavior

I start Emacs daemon with the command: 

`emacs --daemon -Q `

then creating Emacs client with the command:

`emacsclient -a "" --create-frame`

Then I open in emacsclient a file with <kbd>C-x C-f</kbd> `foo.txt`, then close the frame with <kbd>M-x</kbd> `delete-frame`.

Then I call new emacsclient `emacsclient -a "" --create-frame` and call buffer list with <kbd>M-x</kbd> `list-buffers`. I see the buffer `foo.txt` is listed there, as it's still active in the server. 

When I redo it again with an clean Doom clone from repository, I should be supposed to see the `foo.txt` in the buffer list in the last step in Doom Emacs. But it is not there.

### Current behavior

In Doom Emacs, I create Emacs client with the command:

`emacsclient -a "" --create-frame`

Then I open in emacsclient a file with <kbd>C-x C-f</kbd> `bar.txt`, then close the frame with <kbd>M-x</kbd> `delete-frame`.

Then I call new emacsclient `emacsclient -a "" --create-frame` and call buffer list with <kbd>M-x</kbd> `list-buffers`. I see the buffer `bar.txt` is is not listed in the buffer list. I couldn't find any Doom settings that might be related to this.

### Steps to reproduce

1. Remove any Emacs configuration on the system.
2. Start with cloning brand new Doom configuration from the repository. 
3. `git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs`
4. `~/.config/emacs/bin/doom install`
5. Standard install
6. `pkill emacs`
7. `emacs --daemon`
8. Then call `emacsclient -a "" --create-frame` and <kbd>C-x C-f</kbd> a file `bar.txt`.
9. Delete the frame with the open buffer with  <kbd>M-x</kbd> `delete-frame`.
10.  Then call `emacsclient -a "" --create-frame` again, and open a buffer list with <kbd>M-x</kbd> `list-buffers`.

See that the `bar.txt` is not listed in the buffers list, while this is not the case with Emacs daemon without configuration (`emacs --daemon -Q`).

### System Information

https://pastebin.com/b5Ve87DU

**Comment by hlissner** [comment] 2024-11-06 05:11
If you don't want buffer lifecycles tied to your frames, then disable the `:ui workspaces` module. Each frame is automatically given its own workspace by `persp-mode`, which is deleted when the frame is closed.

Look up and tweak these variables to change this behavior: 

- `persp-emacsclient-init-frame-behaviour-override` (when opening frames from the daemon)
- `persp-interactive-init-frame-behaviour-override` (when opening frames from `M-x make-frame` or other interactive commands)

Setting them to `nil` will likely achieve what you're asking for.

Anyhow, I will close this as this is not a bug, but feel free to follow up here.

**Closed by hlissner** 2024-11-06 05:11 UTC
Labels: invalid

**Comment by ReneFroger** [comment] 2024-11-06 14:32
It works now as intented, thanks for the clarification.
