### ISSUE TITLE
Innacurate MacOS installation steps

### ISSUE THREAD

**Issue by nickheyer** [doomemacs/doomemacs#7297] opened 2023-07-17 18:00 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

For `Emacs.app` to be at `/usr/local/opt/emacs-mac/Emacs.app` after running:
```
brew tap railwaycat/emacsmacport
brew install emacs-mac --with-modules
```

Allowing me to create an Application/Shortcut with `ln -s /usr/local/opt/emacs-mac/Emacs.app /Applications/Emacs.app`

### Current behavior

`brew install emacs-mac --with-modules` did not, or possibly only now does not install Emacs.app to `/usr/local/opt...`

In fact, there is no `/usr/local/opt` dir. Instead it was installed to: `/opt/homebrew/opt/emacs-mac/Emacs.app`

Therefore the correct cmd is: `ln -s /opt/homebrew/opt/emacs-mac/Emacs.app /Applications/Emacs.app`

### Steps to reproduce

Install emacs on mac os with homebrew using the following commands:

brew tap railwaycat/emacsmacport
brew install emacs-mac --with-modules
ln -s /usr/local/opt/emacs-mac/Emacs.app /Applications/Emacs.app

### System Information

Pastebin not relevant

**Comment by nickheyer** [comment] 2023-07-17 18:13
Also, it doesn't seem like the alias created with that command is detected by Spotlight. I had to manually right click Emacs.app in the original location -> Create Alias -> Move to /Applications -> Delete " alias" from the file name

**Comment by siddharthshekar** [comment] 2023-07-18 06:52
@nickheyer , you're probably seeing this behavior because you're running this on a Mac with Apple Silicon. See [this page](https://docs.brew.sh/Installation) for more info. The docs probably do need to be updated to account for AS Macs.

**Comment by elken** [comment] 2023-07-19 09:35
Duplicate of #7252

**Closed by elken** 2023-07-19 09:35 UTC
Labels: duplicate
