### ISSUE TITLE
Doom Install hangs on building org-autoloads.el after upgrading to 28.1

### ISSUE THREAD

**Issue by zacaytion** [doomemacs/doomemacs#6283] opened 2022-04-12 01:15 UTC
### What did you expect to happen?

I expected the install to complete. I've been running doom on `28.05` for months without any issues.

### What actually happened?

Doom install starts normally, but when it reaches the `Building org...` step it hangs after `INFO     Scraping files for org-autoloads.el...done`.

See the pastebin link for the full logs from `doom -yd install`

### Describe your attempts to resolve the issue

* Removed and Installed `emacs-plus`
* Reinstalled `gcc` `libgccjit` 
* Deleted `~/.emacs.d` and cloned a fresh clone of `doom`
* Verified issue occurs on vanilla doom install

### Steps to reproduce

Prerequisites:
- `MacOS 11.6.5 Darwin 20.6.0 x86_64`
- `brew install gcc libgccjitq`
- `brew install emacs-plus@28  --with-native-comp`

Steps to Reproduce:
1. `git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d`
2. `~/.emacs.d/bin/doom -yd install`
3. Wait for install to get stuck building org

Output of `doom info` below:
```
> Executing 'doom info' with Emacs 28.1 at 2022-04-11 20:01:41
    generated    Apr 11, 2022 20:01:41
      system       MacOS 11.6.5 Darwin 20.6.0 x86_64
      emacs        28.1 ~/.emacs.d/ -> ~/.emacs.d/
      doom         3.0.0-dev grafted, HEAD -> master, origin/master, origin/HEAD 7121e99 2022-04-08 02:52:54 +0200 ~/.config/doom.d/ -> ~/.config/doom.d/
      shell        /bin/zsh
      features     ACL DBUS GIF GLIB GMP GNUTLS IMAGEMAGICK JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS XIM XWIDGETS ZLIB
      traits       batch envvar-file
      modules      :completion company vertico :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :os macos :lang emacs-lisp markdown org sh :config (default +bindings +smartparens)
```

### System Information

https://pastebin.com/0D5A7y9t

**Comment by mastersilvapt** [comment] 2022-04-12 10:20
See #6284 I think is the same issue.
Need to go back to emacs 27.2

**Comment by hlissner** [comment] 2022-04-13 03:14
Likely a duplicate of https://github.com/hlissner/doom-emacs/issues/5592. Doesn't have anything to do with #6284.

**Closed** 2024-08-23 06:50 UTC
Labels: is:bug, status:unconfirmed, re:install

**Comment by hlissner** [comment] 2024-08-23 06:51
As of c901f58 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
