### ISSUE TITLE
Documentation for the `custom-theme-set-faces!` function?

### ISSUE THREAD

**Issue by danielkrajnik** [doomemacs/doomemacs#7524] opened 2023-10-28 01:19 UTC
Is there any documentation for the `custom-theme-set-faces!`  function? It is causing errors (everything goes white when `'(default :foreground "#ffffff")`  is set) on wayland. Right now there is no information in doom docs how the user should change colors of fonts/faces.

It's a bit silly for such a simple thing as changing font colors to be so complicated/obscure for the user.

**Comment by danielkrajnik** [comment] 2023-10-28 11:06
UPDATE - these lines cause huge issues on Wayland:

```
(custom-theme-set-faces! 'doom-city-lights
  ;; '(default :background "#10151a")
  ;; This makes everything "go white" on wayland.
  ;; '(default :foreground "#ffffff")
```

This really should be documented! Changing default foreground/background?

**Comment by hlissner** [comment] 2024-02-20 09:56
Closing because this is not a bug or issue. You'll find documentation on it and Emacs faces in general through any of the following:

- `C-h f custom-theme-set-faces!` (also available via `M-x helpful-function RET custom-theme-set-faces!`).
- `C-h f custom-theme-set-faces` (the function that Doom's macro wraps around)
- Emacs' documentation on the subject: https://emacsdocs.org/docs/elisp/Applying-Customizations#function-custom-set-faces-rest-args

**Closed by hlissner** 2024-02-20 09:56 UTC
Labels: invalid
