### ISSUE TITLE
Doom sync GNU Emacs 28.1

### ISSUE THREAD

**Issue by jslmorrison** [doomemacs/doomemacs#6584] opened 2022-07-21 16:47 UTC
### What did you expect to happen?

Recently updated to Emacs 28.1. On starting for the first time after upgrade was presented with the default vanilla emacs.
Ran doom sync to fix

### What actually happened?

Tried to run doom sync but never completes and hangs on 'Natively compling 1 files...' 

### Steps to reproduce

Run doom sync after upgrading to Emacs 28.1

### System Information

https://pastebin.com/mSraMzQ8

**Comment by hlissner** [comment] 2022-07-21 22:52
Duplicate of https://github.com/doomemacs/doomemacs/issues/5592

**Closed by hlissner** 2022-07-21 22:52 UTC
Labels: duplicate
