### ISSUE TITLE
Symbol's function definition is void while upgrading

### ISSUE THREAD

**Issue by melspectrum** [doomemacs/doomemacs#7777] opened 2024-03-30 03:11 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

doom upgrade reports error

### Current behavior

when I do doom upgrade, it shows
View the comparison diff in your browser? (y or n) n```

Proceed with upgrade? (y or n) y
> Upgrading Doom Emacs...
  x There was an unexpected runtime error
    Message: Symbol's function definition is void
    Details: (doom-compile-clean)
    Backtrace:
      (doom-compile-clean)
      (let ((doom-print-level (or nil doom-print-level)) (doom-print-indent ...
      (progn (let ((doom-print-level (or nil doom-print-level)) (doom-print-...
      (if (not (or auto-accept-p (y-or-n-p "Proceed with upgrade?"))) (ignor...
      (cond ((and (null this-rev) (null new-rev)) (error "Failed to get revi...
      (let ((this-rev (cdr (sh! "git" "rev-parse" "HEAD"))) (new-rev (cdr (s...
      (let (result) (or (= 0 (car (sh! "git" "remote" "add" doom-upgrade-rem...
      (unwind-protect (let (result) (or (= 0 (car (sh! "git" "remote" "add" ...
      (let* ((branch (replace-regexp-in-string "^\\(?:[^/]+/[^/]+/\\)?\\(.+\...
      (let ((default-directory doom-emacs-dir) process-file-side-effects) (d...
      (doom-cli-upgrade #s(doom-cli-context (26119 33061 360247 0) 29629 0 (...
      (cond (packages? (let ((recipe (doom-cli-context-get context 'straight..
```

### Steps to reproduce

run doom upgrade

### System Information

https://pastebin.com/jqMsJnTr

**Comment by hlissner** [comment] 2024-03-30 03:13
Duplicate of https://github.com/doomemacs/doomemacs/issues/7769.

**Closed by hlissner** 2024-03-30 03:13 UTC
Labels: duplicate
