### ISSUE TITLE
doom upgrade failed on vertico

### ISSUE THREAD

**Issue by melspectrum** [doomemacs/doomemacs#6452] opened 2022-06-13 16:26 UTC
### What did you expect to happen?

doom upgrade failed

### What actually happened?

try to do 

`doom upgrade`

It failed on

    > Updating packages (this may take a while)...
      > In repository "vertico", failed to get status:

        Failed to get unambiguous name for "main"
        fatal: Needed a single revision

           1) Abort

        How to proceed? (1) 1

### Steps to reproduce

1. doom upgrade

### System Information

https://pastebin.com/m39f4CMg

**Comment by hlissner** [comment] 2022-06-13 19:22
Duplicate of #4984

**Closed by hlissner** 2022-06-13 19:22 UTC
Labels: duplicate
