### ISSUE TITLE
Cannot install external packages

### ISSUE THREAD

**Issue by hrqmonteiro** [doomemacs/doomemacs#7403] opened 2023-09-11 09:33 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

To install properly

### Current behavior

![Screenshot_20230911_063139](https://github.com/doomemacs/doomemacs/assets/17055027/94150851-6c1d-4611-b557-bc1500c5a72a)
![Screenshot_20230911_063152](https://github.com/doomemacs/doomemacs/assets/17055027/eccda1f6-b8cf-4d7b-9eb4-6627f6af8f2b)

### Steps to reproduce

Just wrote the package in `packages.el`

### System Information

https://pastebin.com/4yNpnPuu

**Comment by hlissner** [comment] 2023-09-12 14:00
The problem is that ~theorytoe/everforest-theme's has an everforest.el file where its `(provide ...)` line is commented out, which chokes package managers (like straight) that try to load/byte-compile it. This file should either be deleted (since it's all commented out anyway) or that one line should be uncommented.

As a Doom-specific workaround, you can install the package with everforest.el omitted:

```elisp
;; add to $DOOMDIR/packages.el
(package! everforest
  :recipe (:host nil
           :repo "https://git.sr.ht/~theorytoe/everforest-theme"
           :files ("everforest-*-theme.el")))
```

If `doom sync` doesn't show that it's installing anything, run `doom sync -u` instead.

As this is not a Doom issue I will close this.

**Closed by hlissner** 2023-09-12 14:00 UTC
Labels: invalid, is:upstream
