### ISSUE TITLE
How can I use my system global git config?

### ISSUE THREAD

**Issue by lukebest** [doomemacs/doomemacs#6759] opened 2022-09-08 13:50 UTC
### What did you expect to happen?

There is a proxy config in my system global git config (which path is '~/.gitconfig')
but now when i update to latest master commit 0172b180a901cb515e8a6d2d0272535a870853dd i hope 'doom sync' works well.

### What actually happened?

but i can't use doom sync to update repo
error log shows below :

```
x The package manager threw an error
x Last 16 lines of straight's error log:
$ cd /home/myname/.emacs.d/.local/straight/repos/
  $ git clone --origin origin --no-checkout https\://github.com/melpa/melpa.git /home/myname/.emacs.d/.local/straight/repos/melpa/ --depth 1 --single-branch --no-tags
  Cloning into '/home/myname/.emacs.d/.local/straight/repos/melpa'...
  fatal: unable to access 'https://github.com/melpa/melpa.git/': Peer's certificate issuer has been marked as not trusted by the user.
```

### Describe your attempts to resolve the issue

I tried to run git directly 

```
git clone --origin origin --no-checkout https\://github.com/melpa/melpa.git /home/myname/.emacs.d/.local/straight/repos/melpa/ --depth 1 --single-branch --no-tags
```

it works.

### Steps to reproduce

1. git can only access github by proxy, and the proxy config in ~/.gitconfig
2. run doom sync

### System Information

https://pastebin.com/DmvsepUX

**Comment by hlissner** [comment] 2022-09-08 13:54
Set `DOOMGITCONFIG` to the path of your git config file:

```sh
DOOMGITCONFIG=~/.config/git/config doom sync
```

Or in your dotfiles

```sh
export DOOMGITCONFIG=~/.config/git/config
```

As this is not a bug, I will close this. Please direct any user support questions to our [Discourse](https://discourse.doomemacs.org) or [Discord](https://doomemacs.org/discord) in the future, as our issue tracker is only for bug reports.

**Closed by hlissner** 2022-09-08 13:54 UTC
Labels: invalid
