### ISSUE TITLE
.emacs.d/modules/completion/vertico/config.el, (invalid-function ((bytecomp Symbol’s function definition is void: gv-setter :error *Compile-Log*)))

### ISSUE THREAD

**Issue by kmalkenneth** [doomemacs/doomemacs#6862] opened 2022-09-29 22:25 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

to start correctly.
When running doom run, it starts correctly.

### Current behavior

```
Error (use-package): Failed to parse package which-key: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package hl-line: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package winner: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package paren: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package all-the-icons: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package highlight-numbers: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package projectile: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package autorevert: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package recentf: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package savehist: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package saveplace: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package better-jumper: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package dtrt-indent: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package helpful: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package smartparens: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package so-long: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package ws-butler: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package company: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package company-box: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package vertico: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
Error (use-package): Failed to parse package orderless: Invalid function: ((bytecomp "Symbol’s function definition is void: gv-setter" :error "*Compile-Log*")) Disable showing Disable logging
```

```
Warning (initialization): An error occurred while loading ‘/home/kenet/.emacs.d/.local/etc/@/init.28.elc’:

Error in a Doom module: /home/kenet/.emacs.d/modules/completion/vertico/config.el, (invalid-function ((bytecomp Symbol’s function definition is void: gv-setter :error *Compile-Log*)))

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace. Disable showing Disable logging
```

### Steps to reproduce

Only install doom.
open doom
close
open doom

### System Information

https://pastebin.com/RmW5hP7x

**Comment by hlissner** [comment] 2022-09-29 22:26
Does `doom build && doom sync -u` fix it?

**Comment by hlissner** [comment] 2022-09-29 22:28
> When running doom run, it starts correctly.

This sounds like you could be launching different versions of Emacs. Make extra sure that `M-x emacs-version` shows the same information when Emacs is launched with `doom run` or directly.

**Comment by dillydogg** [comment] 2022-10-01 15:32
Duplicate of #6787 also see error on Discourse https://discourse.doomemacs.org/t/doom-emacs-on-wsl2-unable-to-load-after-async-native-complation-after-latest-doom-upgrade/3172

**Comment by hlissner** [comment] 2022-10-01 17:49
@dillydogg Looks like you're correct. Thanks for letting me know! 

I'll mark this a duplicate of #6787 and move the discussion there.

**Closed by hlissner** 2022-10-01 17:49 UTC
Labels: duplicate
