### ISSUE TITLE
`consult-recent-file` displayed differently sorted list from `recentf-open-files`

### ISSUE THREAD

**Issue by mangkoran** [doomemacs/doomemacs#6572] opened 2022-07-19 05:57 UTC
### What did you expect to happen?

Recent file list displayed by `consult-recent-file` should be displayed the same as `recentf-open-file` as the configuration of `consult-recent-file` use `:sort nil`.
```elisp
;; unmodified at all
(defun consult-recent-file ()
  "Find recent file using `completing-read'."
  (interactive)
  (find-file
   (consult--read
    (or (mapcar #'abbreviate-file-name recentf-list)
        (user-error "No recent files, `recentf-mode' is %s"
                    (if recentf-mode "on" "off")))
    :prompt "Find recent file: "
    :sort nil
    :require-match t
    :category 'file
    :state (consult--file-preview)
    :history 'file-name-history)))
```

### What actually happened?

`consult-recent-file` displayed differently sorted list from `recentf-open-files`.

`consult-recent-file`
![image](https://user-images.githubusercontent.com/57625126/179675527-d1bdde5a-0539-4fb8-bec5-9925699b5d61.png)
`recentf-open-files`
![image](https://user-images.githubusercontent.com/57625126/179675516-1b218a51-1ce9-4c95-88f7-05d2f8a277c0.png)
`recentf` file
![image](https://user-images.githubusercontent.com/57625126/179675545-2ac1cefe-4213-44d8-b609-7c96dd82aa1b.png)

### Describe your attempts to resolve the issue

I am not really sure but I have tried to set `:sort t` in `consult-recent-file` and it displayed similarly "sorted" list with `:sort nil`. So it might be upstream issue? I am not sure.

### Steps to reproduce

1. Open Emacs
2. `SPC f r` or `M-x consult-recent-file`
3. Compare that result to `M-x recentf-open-files`

### System Information

https://pastebin.com/DxVsGAqs

**Comment by mangkoran** [comment] 2022-07-21 02:01
I found that `consult-recent-file` call `consult--read` with `:history 'file-name-history`. I wonder if it's the case as the list is looked the same as what `consult-recent-file` displayed
![image](https://user-images.githubusercontent.com/57625126/180113580-9a0fce18-4279-4130-be5b-e62e400e7c0e.png)

**Comment by minad** [comment] 2022-08-02 08:19
@mangkoran The problem is that you have enabled both Ivy and Vertico in your configuration (https://pastebin.com/DxVsGAqs). You should enable only one of them, since they are mutually exclusive.

@hlissner Why does Doom allow turning on both the Vertico and Ivy modules (and maybe even the Helm module) at the same time? Shouldn't there be a check which prevents this? (There is no problem to have vertico-mode enabled and Ivy or Helm installed for specific commands.)

**Comment by hlissner** [comment] 2022-08-02 10:17
> Why does Doom allow turning on both the Vertico and Ivy modules (and maybe even the Helm module) at the same time? Shouldn't there be a check which prevents this? (There is no problem to have vertico-mode enabled and Ivy or Helm installed for specific commands.)

@minad It's simply a relic of the time when Doom was my private Emacs config. I intend to add sanity checks like those as part of #4273.

**Comment by hlissner** [comment] 2022-08-02 10:19
I'll close this, as this is a personal config issue. I'll reopen it if it turns out not to be the case. Feel free to follow up here, in any case.

**Closed by hlissner** 2022-08-02 10:19 UTC
Labels: invalid

**Comment by mangkoran** [comment] 2022-08-02 13:44
Dang. I did not realize I left `ivy` turned on after I "switched" to `vertico`. Thank you for pointing this out!
