### ISSUE TITLE
The link to the documentation in the README is broken

### ISSUE THREAD

**Issue by eckertliam** [doomemacs/doomemacs#6723] opened 2022-08-25 02:05 UTC
### What did you expect to happen?

I expected the web page for the documentation to load.

### What actually happened?

I got a 404 error.

### Steps to reproduce

Scroll down to configuration documentation
Click link
Get 404 error

### System Information

https://pastebin.com/68wzsxui

**Comment by gui-salome** [comment] 2022-08-25 17:15
Likely a duplicate of https://github.com/doomemacs/doomemacs/issues/6631
For now, check this page for docs: https://github.com/doomemacs/doomemacs/tree/develop/docs

**Closed** 2022-09-06 21:04 UTC
Labels: is:bug, duplicate, is:docs
