### ISSUE TITLE
`(arrayp nil)` error while installing packages from codeberg.org (like undo-fu and git-timemachine)

### ISSUE THREAD

**Issue by NicholasNagy** [doomemacs/doomemacs#6541] opened 2022-07-07 02:10 UTC
### What did you expect to happen?

I expected to follow the installation instructions for doom and for it to install properly.

### What actually happened?

The actual resulting output:
![tmp](https://user-images.githubusercontent.com/40705372/177671560-86ddb8cb-ef96-4997-a7b7-366c666a5059.PNG)

Here is the backtrace that the error points to.
[backtrace.zip](https://github.com/doomemacs/doomemacs/files/9059650/backtrace.zip)

If you would like the backtrace to the other packages that failed to install, I can include those as well.

### Describe your attempts to resolve the issue

As a bit of background, I am running all this in WSL. I wanted to get Emacs and doom running on my PC, so the first thing I did was compile Emacs 28.1 in WSL Ubuntu-20.04. I followed the instructions for Emacs 28.1, and got that installed and running, now my next endeavor was running Doom.
However, during the doom install process, I would get this error for the installation of the emacs-undo-fu (if I would re-run and emacs-undo-fu-session, and then git-timemachine, if I re-ran again). Not knowing better, I re-ran the command over and over until doom seemed to have no errors, but it is clear that these packages weren't installed correctly:

![image](https://user-images.githubusercontent.com/40705372/177673835-8174f5d9-e6f1-4fbc-beac-b45481606344.png)

So I keep getting those errors, since I believe these packages weren't installed properly.

Next, I found this document: https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#with-wsl--ubuntu-1804-lts
 in the doom documentation, so I followed that to install Emacs 27.1 in WSL Ubuntu-18.04, and then I followed the guide once more, and I still run into the same issues when running doom install.

### Steps to reproduce

1. Install Emacs version 27.1 or 28.1 on either WSL Ubuntu-18.04 or WSL Ubuntu-20.04
2. follow instructions to install doom emacs (git clone to ~/.emacs.d && ~/.emacs.d/doom install)
3. Should be reproduced.

I am curious to see if this behavior is also seen when installed on native linux. If it is not reproducible on Linux, then it may be a WSL + Windows only bug, unfortunately.

### System Information

https://pastebin.com/e2u0Fhdv

**Comment by oacar** [comment] 2022-07-08 03:18
I had same issue and this could be duplicate of #5207 . 

https://github.com/doomemacs/doomemacs/issues/5207#issuecomment-1159040527 resolved it for me.

**Comment by worzeel** [comment] 2022-07-10 22:07
yep, i am also seeing the above behaviour with WSL2.

I did the https://github.com/doomemacs/doomemacs/issues/5207#issuecomment-1159040527 to it it installed... however, I also get those errors showing when running emacs ("Error running hook "undo-fu-mode" etc etc)

**Comment by NicholasNagy** [comment] 2022-07-11 14:05
Yeah, exactly, that's my main issue, because I can get it installed as well, but it seems like certain packages aren't installed properly, which is why we are getting that error.

I'm curious to know if it's a WSL2-only issue.

**Comment by aniiefsh** [comment] 2022-08-09 22:11
I have the same issue on WSL1 (error installing and then Error running hook). Current workaround is to disable the undo module in init.el.

**Comment by llllbarcodellllllllll** [comment] 2022-08-16 11:39
Same issue with installer on macOS.

**Comment by hlissner** [comment] 2022-08-16 18:19
This seems to be a reoccurring issue with packages that have moved away from Github to [codeberg.org](https://codeberg.org/ideasman42/emacs-undo-fu), as undo-fu has.

You can replace the recipe by adding this to `$DOOMDIR/packages.el` (normally `~/.config/doom/packages.el`):

```elisp
(package! undo-fu
  :recipe (:host github :repo "emacsmirror/undo-fu")
  :pin "913cbb4ff3659d8537c764e56953dbb1b85e73c9")
```

Then run `doom sync -u`

**Comment by wbwqq** [comment] 2022-08-17 15:37
> This seems to be a reoccurring issue with packages that have moved away from Github to [codeberg.org](https://codeberg.org/ideasman42/emacs-undo-fu), as undo-fu has.
> 
> You can replace the recipe by adding this to `$DOOMDIR/packages.el` (normally `~/.config/doom/packages.el`):
> 
> ```emacs-lisp
> (package! undo-fu
>   :recipe (:host github :repo "emacsmirror/undo-fu")
>   :pin "913cbb4ff3659d8537c764e56953dbb1b85e73c9")
> ```
> 
> Then run `doom sync -u`

I had the same issue. This solved the installation issue, but I still have the [error message as in the screenshot above](https://user-images.githubusercontent.com/40705372/177673835-8174f5d9-e6f1-4fbc-beac-b45481606344.png), when emacs launches.

**Closed** 2022-09-06 21:04 UTC
Labels: re:packages, is:upstream, module:emacs/undo

**Comment by hlissner** [comment] 2022-09-06 22:14
As of 2b07fd1 (and thanks to https://github.com/radian-software/straight.el/issues/991) this should be fixed for all codeberg/sourcehut packages. I intend to create mirrors for these packages later down the road, but for the time being I'll consider this resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by zeorin** [comment] 2022-09-10 07:58
I got a different error related to `undo-fu`:

```
❯ doom sync -u
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.local/share/doom/env
  > Installing packages...
    - Checked out undo-fu: ab8bc10e424bccc847800c31ab41888db789d55d
    > Building undo-fu...
    x There was an unexpected runtime error
      Message: Invalid sub-list head in :files directive: :not
      Backtrace:
        (error "Invalid sub-list head in :files directive: %S" :not)
        (if (stringp (car spec)) nil (error "Invalid sub-list head in :files directive: %S" (car spec)))
        (cond ((eq spec :defaults) (setq files (append straight-default-files-directive files))) ((stringp spec) (setq files (nconc (mapcar #'(lambda (file) (let ((filename (file-name-nondirectory file))) (if (eq flavor 'melpa) (progn (setq filename (replace-regexp-in-string "\\.el\\.in\\'" ".el" filena...
        (let ((spec (car files))) (setq files (cdr files)) (cond ((eq spec :defaults) (setq files (append straight-default-files-directive files))) ((stringp spec) (setq files (nconc (mapcar #'(lambda (file) (let ((filename (file-name-nondirectory file))) (if (eq flavor 'melpa) (progn (setq filename (re...
        (while files (let ((spec (car files))) (setq files (cdr files)) (cond ((eq spec :defaults) (setq files (append straight-default-files-directive files))) ((stringp spec) (setq files (nconc (mapcar #'(lambda (file) (let ((filename (file-name-nondirectory file))) (if (eq flavor 'melpa) (progn (setq...
        (let ((mappings nil) (exclusions nil)) (while files (let ((spec (car files))) (setq files (cdr files)) (cond ((eq spec :defaults) (setq files (append straight-default-files-directive files))) ((stringp spec) (setq files (nconc (mapcar #'(lambda (file) (let ((filename (file-name-nondirectory file...
        (straight--expand-files-directive-internal (:defaults (:not ".elisp-autofmt" "LICENSE")) "/home/zeorin/.local/share/doom/straight/repos/undo-fu/" "" nil)
        (let* ((default-directory src-dir) (result (straight--expand-files-directive-internal (or files straight-default-files-directive) src-dir "" flavor)) (mappings (car result))) (let ((copy nil) (absolutes (mapcar #'(lambda (mapping) (let* ((dest mapping) (src (if dest (car-safe (prog1 dest (setq d...
        (straight-expand-files-directive (:defaults (:not ".elisp-autofmt" "LICENSE")) "/home/zeorin/.local/share/doom/straight/repos/undo-fu/" "/home/zeorin/.local/share/doom/straight/build-28.1/undo-fu/" nil)
        (let ((--dolist-tail-- (straight-expand-files-directive files (straight--repos-dir local-repo) (straight--build-dir package) flavor))) (while --dolist-tail-- (let ((spec (car --dolist-tail--))) (let* ((build-file spec) (repo-file (if build-file (car-safe (prog1 build-file (setq build-file (cdr b...
        (progn (let ((dir (straight--build-dir package))) (if (file-exists-p dir) (progn (delete-directory dir 'recursive)))) (make-directory (straight--build-dir package) 'parents) (let ((--dolist-tail-- (straight-expand-files-directive files (straight--repos-dir local-repo) (straight--build-dir packag...
        (let* ((--cl-rest-- recipe) (package (car (cdr (plist-member --cl-rest-- ':package)))) (local-repo (car (cdr (plist-member --cl-rest-- ':local-repo)))) (files (car (cdr (plist-member --cl-rest-- ':files)))) (flavor (car (cdr (plist-member --cl-rest-- ':flavor))))) (progn (let ((dir (straight--bu...
      ! Wrote extended backtrace to ~/.local/share/doom/logs/cli.doom.220910094351.2076171.error
    ! Script was abruptly aborted, leaving Doom in an incomplete state!
    - Run 'doom sync' to repair it.
```

Running https://github.com/doomemacs/doomemacs/issues/5207#issuecomment-1159040527 also resolved it for me.

**Comment by saltsucker** [comment] 2022-12-22 18:12
Hi all, so after trying all the suggestions throughout this repo for this issue, I end up with:
`Error (doom-first-buffer-hook): Error running hook "undo-fu-mode" because: (file-missing Cannot open load file No such file or directory undo-fu-session)`

My issue originally occurs when I am just trying to install doom for first time. I don't know what else to do to fix this.
 Packages are: `emacs-undo-fu-session` , 
Installing for first time I get: 
```
  > Cloning emacs-undo-fu...
  x There was an unexpected runtime error
    Message: Wrong type argument
    Details: (arrayp nil)
    Backtrace:
      (replace-regexp-in-string "[^-0-9a-zA-Z_./\n]" "\\\\\\&" nil)
      (shell-quote-argument nil)
      (mapconcat shell-quote-argument ("git" "branch" "-m" nil) " ")
```
So then I try all the random suggestions scattered throughout this repo, 
**I did this to my `packages.el`**
```
(package! undo-fu
   :recipe (:host github :repo "emacsmirror/undo-fu")
     :pin "913cbb4ff3659d8537c764e56953dbb1b85e73c9")
```
**Run these commands**
```
[.emacs.d]$ vim ~/.doom.d/packages.el
[.emacs.d]$ rm -rf .local/straight/repos/straight.el
[.emacs.d]$ rm -f .local/straight/build-*-cache.el
[.emacs.d]$ ./bin/doom sync
```
And it seems undo-fu gets installed:
```
    > Cloning undo-fu... for emacsmirror-mirror...
    - Checked out undo-fu: 913cbb4ff3659d8537c764e56953dbb1b85e73c9
    > Building undo-fu...
```
But when I open emacs, I get the first error I posted above.

What am I missing here?

**Comment by saltsucker** [comment] 2022-12-22 18:14
Looking at my install log again, seems like `emacs-undo-fu-session` gets built... So idk.
```
    > Building fd-dired...
    > Building undo-fu-session...
    > Cloning browse-at-remote...
    - Checked out browse-at-remote: cef26f2c063f2473af42d0e126c8613fe2f709e4
    > Building browse-at-remote...
```

**Comment by saltsucker** [comment] 2022-12-22 18:30
Since I am a bit of a noob, I didn't realize I could do this:
```
  (package! undo-fu-session
      :recipe (:host github :repo "emacsmirror/undo-fu-session")
      :pin "<whatever commit hash you want>")  
```
and that worked.

So, it seems maybe the doomemacs' mirror "backup" doesn't work for undo-fu? Interestingly, doom install works on a different remote work system that uses SLES 12, but this fails on ubuntu 20.04. /shrug

**Comment by zaidmsh** [comment] 2023-10-26 09:23
> Since I am a bit of a noob, I didn't realize I could do this:
> 
> ```
>   (package! undo-fu-session
>       :recipe (:host github :repo "emacsmirror/undo-fu-session")
>       :pin "<whatever commit hash you want>")  
> ```
> 
> and that worked.
> 
> So, it seems maybe the doomemacs' mirror "backup" doesn't work for undo-fu? Interestingly, doom install works on a different remote work system that uses SLES 12, but this fails on ubuntu 20.04. /shrug

I'm having the same issue on MacOS
