### ISSUE TITLE
Dired +icons misaligns on redisplay

### ISSUE THREAD

**Issue by MithicSpirit** [doomemacs/doomemacs#5579] opened 2021-10-05 01:52 UTC
### What did you expect to happen?

Pressing `r` in dired (`dired-do-redisplay`) should "refresh" the current file(s) but not move around icons.

### What actually happened?

Pressing `r` in dired refreshes the current file(s) (as expected) but shifts their icons to the left edge. 

Before:
![image](https://user-images.githubusercontent.com/24192522/135947532-77103add-c9a6-46d0-8372-6059bc0549d5.png)
After:
![image](https://user-images.githubusercontent.com/24192522/135947549-406358a9-ec47-42ff-bf28-36a2a1ad4249.png)

### Steps to reproduce

0. Make sure `(dired +icons)` is enabled
1. Open Doom Emacs
2. Open a folder with `dired`
3. Put the cursor on an item (with an icon) and press `r`/run `dired-do-redisplay`

### System Information

https://pastebin.com/513FSq2y

**Comment by hlissner** [comment] 2021-10-05 02:01
I can reproduce this in vanilla Emacs, indicating that this is an upstream issue and should be reported to [all-the-icons-dired](https://github.com/jtbm37/all-the-icons-dired/issues).

In fact, I think it's been reported already. That is, if I'm deciphering [this terribly vague issue](https://github.com/jtbm37/all-the-icons-dired/issues/43) correctly.

In any case, I will keep this open until it is resolved upstream.

**Comment by Jdogzz** [comment] 2023-09-16 21:58
@hlissner I seem to be able to reproduce this even with the new nerd-icons switch, and it appears to be due to the code bases being very similar in the past and hence sharing similar bugs (all-the-icons-dired appears to have since diverged somewhat significantly from the nerd-icons-dired code base since then, but all-the-icons-dired had a fix submitted prior to that significant change). The new upstream of nerd-icons-dired now has a PR submitted to fix this current issue by adapting that old fix:

https://github.com/rainstormstudio/nerd-icons-dired/pull/14

**Comment by Jdogzz** [comment] 2023-09-17 02:17
The fix is now merged: https://github.com/rainstormstudio/nerd-icons-dired/commit/4a068884bf86647d242c3adc8320cd603e15dac3

**Closed** 2023-09-17 03:07 UTC
Labels: module:emacs/dired, is:upstream
