### ISSUE TITLE
Enable nongnu-elpa will break undo-fu

### ISSUE THREAD

**Issue by ncihnegn** [doomemacs/doomemacs#6808] opened 2022-09-18 09:21 UTC
### What did you expect to happen?

> Installing packages...
    - Checked out undo-fu: ab8bc10e424bccc847800c31ab41888db789d55d
    > Building undo-fu...
    ✓ Installed 1 packages

### What actually happened?

> Installing packages...
    - Checked out undo-fu: ab8bc10e424bccc847800c31ab41888db789d55d
    > Building undo-fu...
    x There was an unexpected runtime error
      Message: Invalid sub-list head in :files directive: :not
      Backtrace:
        (signal error ("Invalid sub-list head in :files directive: :not"))
        (error "Invalid sub-list head in :files directive: %S" :not)
        (if (stringp (car spec)) nil (error "Invalid sub-list head in :files...
        (cond ((eq spec :defaults) (setq files (append straight-default-file...
        (let ((spec (car files))) (setq files (cdr files)) (cond ((eq spec :...
        (while files (let ((spec (car files))) (setq files (cdr files)) (con...
        (let ((mappings nil) (exclusions nil)) (while files (let ((spec (car...
        (straight--expand-files-directive-internal (:defaults (:not ".elisp-...
        (let* ((default-directory src-dir) (result (straight--expand-files-d...
        (straight-expand-files-directive (:defaults (:not ".elisp-autofmt" "...
        (let ((--dolist-tail-- (straight-expand-files-directive files (strai...
        (progn (let ((dir (straight--build-dir package))) (if (file-exists-p...

### Describe your attempts to resolve the issue

I have to remove nongnu-elpa to install undo-fu correctly.

### Steps to reproduce

1. rm -rf .local/straight/build-28.1/undo-fu
2. git checkout 71469d8
3. doom sync

### System Information

https://pastebin.com/spJTXFhV

**Comment by hlissner** [comment] 2022-09-18 09:59
Duplicate of #6541.

See https://github.com/doomemacs/doomemacs/issues/6541#issuecomment-1238705240

**Closed by hlissner** 2022-09-18 09:59 UTC
Labels: duplicate
