### ISSUE TITLE
Neotree on MacOS uses wrong/nonsensical icon theme.

### ISSUE THREAD

**Issue by tidux** [doomemacs/doomemacs#7854] opened 2024-04-30 23:10 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Doom Emacs's Neotree config should use the `'arrow` icon theme as it does on terminals and X11.

### Current behavior

<img width="206" alt="Screenshot 2024-04-30 at 4 09 41 PM" src="https://github.com/doomemacs/doomemacs/assets/1330562/d4970639-5101-4c2c-a050-481af05a51c4">

### Steps to reproduce

1. install Doom
2. enable neotree
3. restart Emacs
4. `SPC o p`

### System Information

https://pastebin.com/raw/0dC9gsR9

**Comment by hlissner** [comment] 2024-06-28 22:40
It is currently using `nerd` (as in `nerd-icons`), which has terminal support, but the fonts must be installed on your system. Detecting the fonts is non-trivial across platforms, and `nerd-icons` is a core dependency of Doom, so I leave it to users to disable if they don't want it. For neotree, this can be done by changing `neo-theme`:

```elisp
(after! neotree
  (setq neo-theme 'arrow))
```

Since this is not a bug, I will close this, but feel free to follow up here. Thanks for bringing it to my attention in any case.

**Closed by hlissner** 2024-06-28 22:40 UTC
Labels: invalid

**Comment by tidux** [comment] 2024-07-30 14:43
Doom Emacs commit 9116ec2ec729bc30732dfd15a3fcac9ae4988025 on Emacs 29.4 on MacOS no longer exhibits this bug.
