### ISSUE TITLE
Default keybindings missing/not working

### ISSUE THREAD

**Issue by hrqmonteiro** [doomemacs/doomemacs#7840] opened 2024-04-21 00:25 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

To work

### Current behavior

Sometimes a lot of default keybindings simply start missing

In the video i try `SPC h r` `C-+` `C--` (to zoom in/out) `SPC gg` (for magit), and as you can see, it simply went missing

[Screencast_20240420_212249.webm](https://github.com/doomemacs/doomemacs/assets/17055027/dbcd1970-0720-4757-ac57-c8db4175dd5f)

### Steps to reproduce

Just try to use the default keybindings

### System Information

https://pastebin.com/KViUHhSD

**Comment by hlissner** [comment] 2024-04-21 00:34
Please read the [How to debug](https://doomemacs.org/d/how2debug) guide and investigate the \*Messages\* buffer for errors and warnings.

**Comment by alexambarch** [comment] 2024-04-24 15:19
+1 as I just installed Doom, nothing in doom doctor or *Messages*, I am missing a lot of default keybindings (SPC b is undefined, SPC g is undefined, SPC SPC...)

**Comment by alexambarch** [comment] 2024-04-24 19:58
As an update to my previous +1, it looks like my emacs distribution was surreptitiously upgraded which meant I needed to rerun `doom upgrade`. I didn't realize this was the case due to the upgrade but just wanted to leave this note here for anyone else in case it happens to them as well.

**Comment by skunkfox** [comment] 2024-06-24 17:22
FYI I am still missing a bunch of keybindings even after using Doom Upgrade / Doctor / a complete reinstallation. Likely due to Emacs being upgraded recently in Arch Linux?

**Comment by hlissner** [comment] 2024-06-25 16:44
I am unable to reproduce this on 28, 29, or as of commit `9e8c0ec9918af12aafa1063ad3bc3f9f1d180e6f` or 30.0.50. Considering how inconsistent reports of it is, I'll assume this is a local issue and close this until a more reliable connection with Doom can be established. Feel free to follow up here if you find a stable list of steps to reproduce it on a stable version of Emacs (i.e. *not* 30.0.50 -- this is too much of a moving target). Thanks for bringing it to my attention, in any case!

**Closed by hlissner** 2024-06-25 16:44 UTC
Labels: invalid
