### ISSUE TITLE
gnu.org is down and it breaks doom upgrade

### ISSUE THREAD

**Issue by DiogoDoreto** [doomemacs/doomemacs#8102] opened 2024-10-01 14:18 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Running `doom upgrade` / `doom sync` to leave the system in a usable state.

### Current behavior

Since `gnu.org` is down, doom cannot fetch recipes for nongnu-elpa. This caused the `upgrade` command to fail and emacs now starts with plugins in an inconsistent state.

```
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.config/emacs/.local/env
  > Ensuring packages are installed and built...
    > Building magit...
    > Updating recipe repos...
      ✓ melpa updated (403d06d -> 6ef0492)
        - $ cd ~/.config/emacs/.local/straight/repos/melpa/
          $ git config --get remote.origin.url

          https://github.com/melpa/melpa.git

          [Return code: 0]

          $ cd ~/.config/emacs/.local/straight/repos/melpa/
          $ git fetch origin

          From https://github.com/melpa/melpa
             403d06d3..6ef04928  master     -> origin/master
      > Updating recipes for nongnu-elpa...
Error: error ("Failed to run \"git\"; see buffer *straight-process*")
  error("Failed to run %S; see buffer %s" "git" "*straight-process*")

// [...] huge amount of elisp code [...]

        $ git fetch origin
        fatal: unable to access 'https://git.savannah.gnu.org/git/emacs/nongnu.git/': Failed to connect to git.savannah.gnu.org port 443 after 75016 ms: Couldn't connect to server
        [Return code: 128]
```

### Steps to reproduce

Run `doom upgrade` while `https://git.savannah.gnu.org/git/emacs/nongnu.git/` is not reachable.

### System Information

https://pastebin.com/GigmtYMU

**Comment by VandeeFeng** [comment] 2024-10-01 14:35
me too ! Just today

**Comment by ldangelo** [comment] 2024-10-01 14:38
Yup, started late last night...

**Comment by ldangelo** [comment] 2024-10-01 15:36
Seems like it's back up...

**Comment by hlissner** [comment] 2024-10-01 15:38
Duplicate of #7171

**Closed by hlissner** 2024-10-01 15:38 UTC
Labels: duplicate
