### ISSUE TITLE
can't format bash code correctly

### ISSUE THREAD

**Issue by laishulu** [doomemacs/doomemacs#995] opened 2018-11-01 16:20 UTC
### Observed behavior

a bash file called `a.sh`
```bash
#!/usr/bin/env bash

root_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)
```
when `<spc>cf`, got error:
```
Failed to format buffer due to errors
Formatter error output:
<standard input>:3:40: arrays are a bash feature
```
But it seems the bug is not from upstream, see

https://github.com/lassik/emacs-format-all-the-code/issues/18

### System information

<details>
<summary>Click to expand</summary>

```
- OS: darwin (x86_64-apple-darwin14.5.0)
- Emacs: 26.1 (May 31, 2018)
- Doom: 2.0.9 (develop 876660c28f7b51a26e7982e44b4cefff66b8bd3b)
- Graphic display: nil (daemon: t)
- System features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
- Details:
  ```elisp
  elc count: 0
  uname -a:  Darwin mao 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion company (helm +fuzzy) :ui deft doom doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) pretty-code unicode vc-gutter vi-tilde-fringe window-select :editor format multiple-cursors rotate-text :emacs dired ediff electric eshell hideshow imenu term vc :tools editorconfig magit :lang data emacs-lisp markdown (org +attach +babel +capture +export +present) python rust (sh +fish) :config default)
  packages:  ((column-marker :recipe (column-marker :fetcher github :repo emacsmirror/column-marker)) evil-textobj-column (evil-textobj-entire :recipe (evil-textobj-entire :fetcher github :repo supermomonga/evil-textobj-entire)) (evil-textobj-line :recipe (evil-textobj-line :fetcher github :repo syohex/evil-textobj-line)) (evil-textobj-syntax :recipe (evil-textobj-syntax :fetcher github :repo laishulu/evil-textobj-syntax)) s)
  exec-path: (/usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /Applications/VMware Fusion.app/Contents/Public/ /Library/TeX/texbin/ /usr/local/MacGPG2/bin/ /opt/X11/bin/ ~/bin/ ~/.cargo/bin/ /usr/local/opt/python/libexec/bin/ /usr/local/opt/coreutils/libexec/gnubin/ /usr/local/sbin/ /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10/ /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10/ /Applications/Emacs.app/Contents/MacOS/libexec/)
  ```
```
</details>

**Comment by Jdogzz** [comment] 2023-09-15 03:40
I'm not able to reproduce this, it does a check without any errors on my end, although after <spc>cf I selected shfmt from the presented list. Maybe this has been resolved in the meantime?

https://pastebin.com/3dJhjbv8

**Comment by Jdogzz** [comment] 2023-09-15 18:04
@laishulu Are you still able to reproduce this bug on your end?

**Comment by hlissner** [comment] 2023-09-15 18:33
With the recent rewrite of the `:editor format` module (#6369), many of our issues with formatters have been resolved. New issues may arise, but the original issue here is likely resolved or, at worst, no longer applicable, so I will close it. Please open a new issue if the new formatter gives similar issues. Thanks for letting me know, in any case!

**Closed by hlissner** 2023-09-15 18:33 UTC
Labels: is:bug, module:editor/format
