### ISSUE TITLE
 Links displayed in literal form in org-roam buffers

### ISSUE THREAD

**Issue by alienbogart** [doomemacs/doomemacs#6542] opened 2022-07-07 10:41 UTC
### What did you expect to happen?

Links in the org-roam buffer should not be literal.

### What actually happened?

Links in the org-roam buffer are displaying literal (not truncated).

### Describe your attempts to resolve the issue

No, but see other issues: 

- https://github.com/org-roam/org-roam/issues/2198
- https://github.com/org-roam/org-roam/issues/944

### Steps to reproduce

1. Run `org-roam-node-find`
2. Run `org-roam-buffer-toggle`

### System Information

https://pastebin.com/2531kQz2

**Comment by idhx** [comment] 2022-07-14 11:03
I have the same issue. As a temporary fix, I have pinned org to the commit mentioned [here](https://github.com/org-roam/org-roam/issues/2198#issuecomment-1141274021).

In packages.el:

`(package! org :pin "69c588947d1bbca1eb8c773f2a8ff117d264ba")`

then run `doom sync -u`

**Comment by alienbogart** [comment] 2022-07-16 17:55
> I have the same issue. As a temporary fix, I have pinned org to the commit mentioned [here](https://github.com/org-roam/org-roam/issues/2198#issuecomment-1141274021).
> 
> In packages.el:
> 
> `(package! org :pin "69c588947d1bbca1eb8c773f2a8ff117d264ba")`
> 
> then run `doom sync -u`

Thanks! Unfortunately, I got the following error when trying to follow your tip:

```
 ERROR: Couldn't collect commit list because: fatal: ambiguous argument '69c588947d1bbca1eb8c773f2a8ff117d264ba': unknown revision or path not in the working tree.
        Use '--' to separate paths from revisions, like this:
        'git <command> [<revision>...] -- [<file>...]'
```

Any idea what might be the problem? 

Thanks again!

**Comment by idhx** [comment] 2022-07-26 11:15
This issue has been fixed in org-roam: [2236](https://github.com/org-roam/org-roam/pull/2236)

I no longer pin org in my packages.el. Instead I have unpinned org-roam: `(unpin! org-roam)`. This works, and it should also be fine to pin org-roam to the commit linked above.

Is it customary to make PR just to update the version to which a package is pinned in doom emacs? Or is it better to just wait?

**Comment by alienbogart** [comment] 2022-07-26 14:06
> This issue has been fixed in org-roam: [2236](https://github.com/org-roam/org-roam/pull/2236)
> 
> I no longer pin org in my packages.el. Instead I have unpinned org-roam: `(unpin! org-roam)`. This works, and it should also be fine to pin org-roam to [917a325](https://github.com/org-roam/org-roam/commit/917a325dd9778cd06a35e12f262963f75909d646)

Adding either `(unpin! org-roam)` or `(package! org-roam :pin "917a325")` to `packages.el` seems to have no effect whatsoever after `$ doom sync`. Do I need to do anything else for it to work? Thanks!

**Comment by idhx** [comment] 2022-07-26 14:10
Have you tried `doom upgrade` or maybe `doom sync -u`?

**Comment by listx** [comment] 2022-08-15 06:46
`(setq org-fold-core-style “overlays”)` fixed it for me, as per the comment [here](https://github.com/org-roam/org-roam/issues/2198#issuecomment-1208072780).

**Comment by alienbogart** [comment] 2022-08-26 04:05
> `(setq org-fold-core-style “overlays”)` fixed it for me, as per the comment [here](https://github.com/org-roam/org-roam/issues/2198#issuecomment-1208072780).

This worked for me as well!

**Comment by hwiorn** [comment] 2023-03-09 14:18
I think this issue was already resolved by [org-roam#2236](https://github.com/org-roam/org-roam/pull/2236)
But if you have still a same issue, [org-roam#2325](https://github.com/org-roam/org-roam/pull/2325) could help you.

Use latest org-roam. Do `(unpin! org-roam)` and `doom sync -u`

**Comment by Jdogzz** [comment] 2023-09-16 22:13
@alienbogart Are you still able to reproduce this error without the extra org-fold-core-style line? I am not able to reproduce this error.

https://pastebin.com/FLYtFeKZ

**Comment by hlissner** [comment] 2023-10-07 15:31
org-roam has been bumped a number of times since, so I'll consider this resolved. Thanks for bringing it to my attention!

**Closed by hlissner** 2023-10-07 15:31 UTC
Labels: invalid
