### ISSUE TITLE
clocktable mode not working

### ISSUE THREAD

**Issue by dustinfarris** [doomemacs/doomemacs#6491] opened 2022-06-21 19:58 UTC
### What did you expect to happen?

look at the clock table in agenda

### What actually happened?

agenda closed

### Steps to reproduce

1. open agenda
2. run `org-agenda-clockreport-mode`

### System Information

https://pastebin.com/W4JgcSae

**Comment by ineu** [comment] 2022-06-27 08:04
An addition: the agenda view disappears if any action is performed with the clocktable turned on. I encounter it on:
1. Turn clocktable on by pressing `R` (turning it off is fine, it doesn't hide the agenda)
2. Switch to an additional view (`zd`, `zw` etc)
3. Enable clockcheck (`zc`)
4. Walk back/forward in the history (`[`, `]`)

So it looks like it happens in a hook or other code which redraws the agenda when the clocktable is on

**Comment by HuntTheSun** [comment] 2022-07-12 08:10
Can confirm, I have the same issue, I think the issue appeared after upgrading doom.
Emacs 28.1
Doom 3.0.0-dev

**Comment by tobiaskn** [comment] 2022-08-04 17:58
I'm seeing the same issue and I think that it's related to a recent change in org mode, but doom is involved, too, as it doesn't occur with vanilla emacs.

I tried to track it down and only got so far:

1. when entering clock table-mode a temp buffer (let's call it b1) is created for building the clocktable in (in the background, agenda buffer is still visible)
2. while doing so, another temporary buffer is created on top of that (b2) in org-string-width for measuring text size, needed for proper alignment in the table
3. b2 is linked to the current window with set-window-buffer to make it visible. Seems to be necessary for measuring the size
4. when leaving the body of the with-temp-buffer statement (of b2), the buffer b2 gets killed and since it's currently linked to the active window, emacs now chooses another buffer for that window. And for some reason this is not the previous agenda buffer but the one that was open before that.

I think the problem started with this commit in org mode which changed org-string-width to this set-window-buffer approach: https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/lisp/org-macs.el?id=d048c153dd67a118eaa21f04a7faef2800bba03a 

However, doom must be involved, too. Because with vanilla emacs step 4. just makes the agenda buffer again visible in the current window.

**Comment by hlissner** [comment] 2022-08-04 18:42
Doom has emacs-straight/org-mode@5a49cc5f4f09910fd03d5db590ae2b80f5981a66 pinned, while vanilla Emacs comes with a much older version (depending on what version of Emacs you're on). Try checking out an older version instead. For example:

```elisp
;; in $DOOMDIR/packages.el
(package! org-mode :pin "971eb6885ec996c923e955730df3bafbdc244e54")
```

I can't guarantee emacs-straight/org-mode@971eb6885ec996c923e955730df3bafbdc244e54 is the working commit you're looking for, but it is from March, whereas emacs-straight/org-mode@5a49cc5f4f09910fd03d5db590ae2b80f5981a66 is from 3 days ago.

**Comment by UndeadKernel** [comment] 2022-08-05 12:37
When `with-temp-buffer` finishes executing, the temp buffer is killed with `kill-buffer`. As "documented" in a comment inside `with-temp-buffer`:
> ;; `kill-buffer' can change current-buffer in some odd cases.

Because of this behavior of `kill-buffer`, the function tries to use `with-current-buffer`. This last function also fails to preserve the current buffer. Is this maybe an emacs bug?

My current solution is to force emacs to do what I want with something like:
```lisp
(defun clock-and-stay ()
  (interactive)
  (let ((this-buffer (current-buffer)))
    (org-agenda-clockreport-mode)
    (switch-to-buffer this-buffer))
  )

(define-key! org-agenda-mode-map
  "R" #'clock-and-stay)
```

**Comment by tobiaskn** [comment] 2022-08-05 13:16
I'm still struggling with pinning org-mode as doom sync gives me errors (`":pre-build command error in "org-mode" recipe in command "(\"make\" \"oldorg\" \"EMACS=/opt/homebrew/Cellar/emacs-plus\\\\@28/28.1/Emacs.app/Contents/MacOS/Emacs\")"`) but I'm pretty sure that it's not only the changes in org causing the problem, because:

I cannot reproduce the behavior without doom but with the same version of org as doom uses (I added the following config to my vanilla emacs):
`(add-to-list 'load-path (expand-file-name "~/.emacs.d/.local/straight/build-28.1/org"))`

**Comment by hlissner** [comment] 2022-08-10 14:04
> I'm still struggling with pinning org-mode as doom sync

Try using the entire recipe:

```elisp
;; in $DOOMDIR/packages.el
(package! org
  :recipe (:host github
           :repo "emacs-straight/org-mode"
           :files (:defaults "etc")
           :depth 1
           :build t
           :pre-build
           (with-temp-file "org-version.el"
             (let ((version
                    (with-temp-buffer
                      (insert-file-contents (doom-path "lisp/org.el") nil 0 1024)
                      (if (re-search-forward "^;; Version: \\([^\n-]+\\)" nil t)
                          (match-string-no-properties 1)
                        "Unknown"))))
               (insert (format "(defun org-release () %S)\n" version)
                       (format "(defun org-git-version (&rest _) \"%s-??-%s\")\n"
                               version (cdr (doom-call-process "git" "rev-parse" "--short" "HEAD")))
                       "(provide 'org-version)\n"))))
  :pin "971eb6885ec996c923e955730df3bafbdc244e54")
```

**Comment by tobiaskn** [comment] 2022-08-10 17:09
Thanks a lot, that worked and pinning to that version has also fixed the issue for me. 

When I have time, I'll continue to look into the issue a bit further because I still don't understand why I cannot reproduce it without doom (but same org version).

**Comment by AdamG012** [comment] 2022-09-05 04:59
Hey all,

Thanks for the tip on pinning. In the meantime, I did tinker around with `org-macs.el` and found that replacing the call to the`org-encode-time` wrapper function in `org-matcher-time` to `apply #'encode-time` got it working for me. Not sure if it's taboo to modify files directly in .local/straight but so far it has been working.

**Comment by myme** [comment] 2022-09-17 13:38
> When I have time, I'll continue to look into the issue a bit further because I still don't understand why I cannot reproduce it without doom (but same org version).

Well, I was noticing something strange. I use clock tables both in the Agenda and in some Timesheet.org files for summation of weekly hours. I noticed that the `*Org Agenda*` buffer kept experiencing this bug, but not when I was updating the tables in `Timesheet.org`.

I tried to narrow this down, and figured that this issue doesn't occur to me for file-visiting buffers. However, creating e.g. a `*new*` doom scratch buffer in `org-mode` and doing table operations in it quickly reveals the issue. I know that doom has various rules for how certain "non-important" buffers are buried/killed. 

This video shows a `*new*` buffer set to `org-mode` where `(doom-real-buffer-p (current-buffer)) => nil`. It's "impossible" to work in the table because the buffer constantly switches to `*doom*` (previous buffer). Then, setting `(setq-local doom-real-buffer-p t)` the issue "magically" disappears:

![msrdc_o7gHg2DdSA](https://user-images.githubusercontent.com/148158/190859736-0b781ac1-8a50-4786-bcd1-be8137c4dffb.gif)

I would assume the culprit is to do with whatever advicing doom does of buffer switching functions that's exposed by leaving `(with-temp-buffer ...)`.

**Comment by myme** [comment] 2022-09-17 21:05
Here's a brief excerpt from the backtrace in the situation above:

![image](https://user-images.githubusercontent.com/148158/190876144-394036e0-8efa-4d77-ab99-dca9fde21a86.png)

When the `*temp-*` buffer used by `org-string-width` is killed `switch-to-prev-buffer` confers the `buffer-predicate` which is `doom-buffer-frame-predicate` which will ignore "unreal" buffers like `*new*` and `*Org Agenda*`.

**Comment by tobiaskn** [comment] 2022-09-25 08:05
Interesting, thanks @myme for digging into this! 

Would one possible approach be to add some predicate function that matches the org agenda buffer to `doom-real-buffer-functions`? In my configuration, there's something similar already in there for magit: `+magit-buffer-p`.

**Comment by myme** [comment] 2022-09-25 08:17
I've added https://github.com/myme/dotfiles/commit/6f1cd98f0652ac57d7bdf402d3eee33bb2baede8 in my own private `org-mode` config module. It's somewhat of a hack though because it only handles `org-agenda-mode` cases, not other temporary buffers that somehow invoke `org-string-width`, like doing table work in a `*new*` or `*scratch*` regular `org-mode` buffer. And it also breaks the (I'm guessing - intentional) assumption that Org Agenda buffers should be considered "unreal", and managed accordingly.

I don't really know the implications of messing with these hooks and how Doom expects them to behave to really suggest a proper fix at this time though.

**Comment by dustinfarris** [comment] 2022-10-07 13:56
I'm not sure what changed, but as of the latest `doom upgrade` this has started working again for me.

**Comment by dschaehi** [comment] 2022-10-07 14:46
I can confirm that the problem is gone, but now I face a different problem, i.e., links in the org agenda clock table is not displayed properly as you can see below. Do you also experience the same problem?

```
| Headline          |   Time |
|-------------------+--------|
| *Total time*      | *0:03* |
|-------------------+--------|
| [[file:/org/home.org::*Tasks][Routine Tasks]]     |   0:03 |
|-------------------+--------|
```

**Comment by dustinfarris** [comment] 2022-10-07 15:00
Yes I am seeing that as well.Sent from my iPhoneOn Oct 7, 2022, at 07:46, Jae Hee Lee ***@***.***> wrote:﻿
I can confirm that the problem is gone, but now I face a different problem, i.e., links in the org agenda clock table is not displayed properly as you can see below. Do you also experience the same problem?
| Headline          |   Time |
|-------------------+--------|
| *Total time*      | *0:03* |
|-------------------+--------|
| [[file:/org/home.org::*Tasks][Routine Tasks]]     |   0:03 |
|-------------------+--------|

**Comment by tobiaskn** [comment] 2022-10-07 16:06
Same here, it looks as if that temp buffer for rendering the table didn‘t have the org-mode enabled or so. For now, I‘ve deactivated the links as I hardly use them anyway.

**Comment by dschaehi** [comment] 2022-10-07 16:10
> Same here, it looks as if that temp buffer for rendering the table didn‘t have the org-mode enabled or so. For now, I‘ve deactivated the links as I hardly use them anyway.

@tobiaskn Can you tell me how you deactivated the links? I'd like to do the same. Thanks!

**Comment by dschaehi** [comment] 2022-10-07 17:29
Never mind. I set `:link nil` for `org-agenda-clockreport-parameter-plist` and it worked.

**Comment by Bounga** [comment] 2022-11-04 16:01
> I'm not sure what changed, but as of the latest `doom upgrade` this has started working again for me.

I just upgraded to the latest version of Doom and it doesn't fix the issue here

**Comment by hlissner** [comment] 2024-06-28 22:59
It's been some time and I suspect this has been resolved upstream at some point (or at least, I can't reproduce it anymore). A lot has changed in `org` since this issue was created. I'll close this for now, but feel free to follow up here if that's not the case.

**Closed by hlissner** 2024-06-28 22:59 UTC
Labels: is:bug, module:lang/org, module:core
