### ISSUE TITLE
After Upgrade can not open any files hook global-git-commit-mode Error

### ISSUE THREAD

**Issue by Syphixs** [doomemacs/doomemacs#6425] opened 2022-05-29 09:27 UTC
### What did you expect to happen?

```
Error (doom-first-file-hook): Error running hook "global-git-commit-mode" because: (wrong-type-argument json-value-p t)
```

It seems a wrong argument is called. Tried with an empty config.el as well , same problem. 

attached are my init enabled packages.

[init.txt](https://github.com/doomemacs/doomemacs/files/8792994/init.txt)

System: MacOS Monterey 12.3.1
Emacs 27.2

### What actually happened?

Open File in Emacs

### Steps to reproduce

Open Emacs 
Open file

### System Information

https://pastebin.com/iggj1JS7

**Comment by Syphixs** [comment] 2022-05-29 17:59
Solved with installing Emacs Version 28 

Installed via https://github.com/d12frosted/homebrew-emacs-plus

**Comment by bagelbyte** [comment] 2022-05-29 21:49
Also getting this error with emacs 27.2 running on ubuntu 22.04, getting the error when trying to open up org roam with  "SPC n r f"

**Comment by BR00l** [comment] 2022-05-29 22:31
same here, just updated and this occured

**Comment by hlissner** [comment] 2022-05-29 22:43
Please include [a backtrace](https://discourse.doomemacs.org/t/what-is-a-backtrace-how-to-produce-them/85#how-to-produce-a-backtrace-3).

Also see if running `doom build && doom sync -u` fixes the issue.

**Comment by bagelbyte** [comment] 2022-05-29 23:25
when running `SPC n r f`

```
Explain-pause-mode: please report this bug by creating a Github
issue at https://github.com/lastquestion/explain-pause-mode. Explain-pause-mode
is now _disabled_ so you can continue to hopefully use Emacs. Info follows:

explain-pause version: 0.1
emacs version: 27.2

not top level in wrap-native for #<subr recursive-edit>
current
#s(explain-pause-command-record root-emacs nil nil -1 (25235 65512 407843 475000) nil nil nil nil 0)

Backtrace:
  explain-pause-report-measuring-bug("not top level in wrap-native for #<subr recursive-..." "current" #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time -1 :entry-snap (25235 65512 407843 475000) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0))
  explain-pause--wrap-native(#<subr recursive-edit>)
  apply(explain-pause--wrap-native #<subr recursive-edit> nil)
  recursive-edit()
  debug(error (wrong-type-argument json-value-p t))
  json-serialize(t)
  (condition-case nil (json-serialize t) (:success t) (json-unavailable nil))
  (not (condition-case nil (json-serialize t) (:success t) (json-unavailable nil)))
  (and (not (condition-case nil (json-serialize t) (:success t) (json-unavailable nil))) (not (fboundp 'json-serialize)))
  (if (and (not (condition-case nil (json-serialize t) (:success t) (json-unavailable nil))) (not (fboundp 'json-serialize))) (progn (defalias 'json-serialize #'compat--json-serialize)))
  eval-buffer(#<buffer  *load*-132154> nil "/home/itsme/.emacs.d/.local/straight/build-27.2/com..." nil t)  ; Reading at buffer position 3929
  load-with-code-conversion("/home/itsme/.emacs.d/.local/straight/build-27.2/com..." "/home/itsme/.emacs.d/.local/straight/build-27.2/com..." nil t)
  require(compat)
  eval-buffer(#<buffer  *load*-973757> nil "/home/itsme/.emacs.d/.local/straight/build-27.2/mag..." nil t)  ; Reading at buffer position 1544
  load-with-code-conversion("/home/itsme/.emacs.d/.local/straight/build-27.2/mag..." "/home/itsme/.emacs.d/.local/straight/build-27.2/mag..." nil t)
  require(magit-section)
  eval-buffer(#<buffer  *load*-69670> nil "/home/itsme/.emacs.d/.local/straight/build-27.2/org..." nil t)  ; Reading at buffer position 3562
  load-with-code-conversion("/home/itsme/.emacs.d/.local/straight/build-27.2/org..." "/home/itsme/.emacs.d/.local/straight/build-27.2/org..." nil t)
  require(org-roam)
  eval-buffer(#<buffer  *load*> nil "/home/itsme/.emacs.d/.local/straight/build-27.2/org..." nil t)  ; Reading at buffer position 1381
  load-with-code-conversion("/home/itsme/.emacs.d/.local/straight/build-27.2/org..." "/home/itsme/.emacs.d/.local/straight/build-27.2/org..." nil t)
  autoload-do-load((autoload "org-roam-node" ("/home/itsme/.emacs.d/.local/autoloads.27.2.elc" . 834969) t nil) org-roam-node-find)
  command-execute(org-roam-node-find)
```

**Comment by daanturo** [comment] 2022-05-30 13:47
Looks like it's a bug in Emacs 27, `json-serialize` should handle `t` as OBJECT (stated in its docstring) but doesn't.

Perhaps it was fixed from Emacs 28. I can't find where `global-git-commit-mode` calls `json-serialize`.

Maybe this can workaround `t` as the first argument (I haven't tested on Doom/Emacs 27 so there are possibly more cases to handle):

```lisp
(advice-add #'json-serialize :around
            (lambda (func obj &rest args)
              (cond ((equal obj t)
                     "true")
                    (t
                     (apply func obj args)))))
```

**Comment by dekkers** [comment] 2022-07-12 19:55
I hit the same problem in May, but with the latest version the problem seems to be gone. Maybe some module broke Emacs 27 compatibility and that has been fixed now?

**Comment by bsturk** [comment] 2023-02-14 14:31
New user, installed today with Emacs 28.1, getting a similar error:

hostname[~]% emacs --version
GNU Emacs 28.1
Copyright (C) 2022 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

-- attempt to open file with :e

Error (doom-first-file-hook): Error running hook "global-git-commit-mode" because: (void-variable transient-base-map) Disable showing Disable logging
Error: failed to incrementally load with-editor because: (void-function defvar-keymap)

Backtrace

 Debugger entered--Lisp error: (void-variable transient-base-map)
   byte-code("\304\10\305\306\307\310\311\312\313\310\314\315\316\317\320\321\322\317\323\321&\23\210\304\11\305\324\325\10\326\327\330\331\332\333\334\335\336\335\337\3$
   require(transient)
   eval-buffer(#<buffer  *load*> nil "/home/<user>/.emacs.d/.local/straight/build-28.1/g..." nil t)  ; Reading at buffer position 5337
   load-with-code-conversion("/home/<user>/.emacs.d/.local/straight/build-28.1/g..." "/home/<user>/.emacs.d/.local/straight/build-28.1/g..." nil t)
   global-git-commit-mode()
   funcall(global-git-commit-mode)
   (condition-case e (funcall hook) ((debug error) (signal 'doom-hook-error (list hook e))))
   doom-run-hook(global-git-commit-mode)
   run-hook-wrapped(doom-run-hook global-git-commit-mode)
   (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook))
   (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running $
   (let ((hook (car --dolist-tail--))) (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error ni$
   (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error$
   (let ((--dolist-tail-- hooks)) (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run$
   doom-run-hooks(doom-first-file-hook)
   (progn (setq running\? t) (doom-run-hooks hook-var) (set hook-var nil))
   (if (and after-init-time (not running\?) (or (daemonp) (and (boundp hook) (symbol-value hook)))) (progn (setq running\? t) (doom-run-hooks hook-var) (set hook-var nil$
   chain-doom-first-file-hook-to-find-file-hook-h(nil t)
   apply(chain-doom-first-file-hook-to-find-file-hook-h (nil t))
   after-find-file(nil t)
   find-file-noselect-1(#<buffer .bashrc> "~/.bashrc" nil nil "/mnt/nas/.bashrc" (4016899 56))
   find-file-noselect("~/.bashrc" nil nil nil)
   find-file("~/.bashrc")
Error: failed to incrementally load with-editor because: (void-function defvar-keymap)

**Comment by yuhrao** [comment] 2023-02-14 23:06
I'm experiencing the same problem

```
GNU Emacs 28.2.50
Copyright (C) 2022 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

```
Debugger entered--Lisp error: (void-variable transient-base-map)
  byte-code("\304\10\305\306\307\310\311\312\313\310\314\315\316\317\320\321\322\317\323\321&\23\210\304\11\305\324\325\10\326\327\330\331\332\333\334\335\336\335\337\340\341\342&\23\210\304\n\305\343..." [transient-base-map transient-map transient-edit-map transient-sticky-map defvar-keymap :doc "Parent of other keymaps used by Transient.\n\nThis i..." "ESC ESC ESC" transient-quit-all "C-g" transient-quit-one "C-q" "C-z" transient-suspend "C-v" transient-scroll-up "C-M-v" transient-scroll-down "<next>" "<prior>" "Top-level keymap used by all transients.\n\nIf you a..." :parent "C-u" universal-argument "C--" negative-argument "C-t" transient-show "?" transient-help "C-h" "C-M-p" transient-history-prev "C-M-n" transient-history-next "Keymap that is active while a transient in is in \"..." "C-x l" transient-set-level "Keymap that is active while an incomplete key sequ..." transient-quit-seq] 20)
  require(transient)
  load-with-code-conversion("/home/yuhri/.emacs.d/.local/straight/build-28.2.50..." "/home/yuhri/.emacs.d/.local/straight/build-28.2.50..." nil t)
  global-git-commit-mode()
  funcall(global-git-commit-mode)
  (condition-case e (funcall hook) ((debug error) (signal 'doom-hook-error (list hook e))))
  doom-run-hook(global-git-commit-mode)
  run-hook-wrapped(doom-run-hook global-git-commit-mode)
  (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook))
  (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp (car (cdr e))) (symbol-name (car (cdr e))) (car (cdr e))) (car (cdr (cdr e))))) (signal 'doom-hook-error (cons hook (cdr e)))))
  (let ((hook (car --dolist-tail--))) (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp (car ...)) (symbol-name (car ...)) (car (cdr e))) (car (cdr (cdr e))))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp ...) (symbol-name ...) (car ...)) (car (cdr ...)))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- hooks)) (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if ... ... ...) (car ...))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  doom-run-hooks(doom-first-file-hook)
  (progn (setq running\? t) (doom-run-hooks hook-var) (set hook-var nil))
  (if (and after-init-time (not running\?) (or (daemonp) (and (boundp hook) (symbol-value hook)))) (progn (setq running\? t) (doom-run-hooks hook-var) (set hook-var nil)))
  chain-doom-first-file-hook-to-find-file-hook-h(nil t)
  apply(chain-doom-first-file-hook-to-find-file-hook-h (nil t))
  after-find-file(nil t)
  find-file-noselect-1(#<buffer config.el> "~/.doom.d/config.el" nil nil "~/.doom.d/config.el" (547457530 65024))
  #<subr find-file-noselect>("/home/yuhri/.doom.d/config.el" nil nil nil)
  apply(#<subr find-file-noselect> "/home/yuhri/.doom.d/config.el" (nil nil nil))
  editorconfig--advice-find-file-noselect(#<subr find-file-noselect> "/home/yuhri/.doom.d/config.el" nil nil nil)
  apply(editorconfig--advice-find-file-noselect #<subr find-file-noselect> ("/home/yuhri/.doom.d/config.el" nil nil nil))
  find-file-noselect("/home/yuhri/.doom.d/config.el" nil nil nil)
  find-file("/home/yuhri/.doom.d/config.el")
  #<subr counsel-projectile-find-file-action>("config.el")
  apply(#<subr counsel-projectile-find-file-action> "config.el")
  (let ((default-directory (ivy-state-directory ivy-last))) (apply fn args))
  +ivy--run-from-ivy-directory-a(#<subr counsel-projectile-find-file-action> "config.el")
  apply(+ivy--run-from-ivy-directory-a #<subr counsel-projectile-find-file-action> "config.el")
  counsel-projectile-find-file-action("config.el")
  ivy-call()
  ivy-read("[.doom.d] Find file: " ("../.cache/yay/emacs28-git/src/emacs28-git/src/byte..." "config.el" "custom.el" "init.el" "modules/protobuffer-mode/protobuf-mode.el" "packages.el" "snippets/clojure-mode/require_as" "snippets/clojure-mode/t_deps_new_mvn_dep" "snippets/go-mode/__go" "snippets/rjsx-mode/React_Functional_Component" "snippets/typescript-mode/scc" "snippets/typescript-mode/scf" "snippets/typescript-tsx-mode/rfc" "themes/dracula-pro-default-theme.el" "themes/dracula-pro-vanhelsing-theme.el") :matcher counsel-projectile--find-file-matcher :require-match t :sort nil :action (1 ("o" counsel-projectile-find-file-action "current window") ("j" counsel-projectile-find-file-action-other-window "other window") ("x" counsel-projectile-find-file-action-extern "open externally") ("r" counsel-projectile-find-file-action-root "open as root") ("m" counsel-projectile-find-file-action-find-file-manually "find file manually") ("k" counsel-projectile-find-file-action-delete "delete") ("p" counsel-projectile-find-file-action-switch-project "switch project")) :caller counsel-projectile-find-file)
  counsel-projectile-find-file(nil)
  funcall-interactively(counsel-projectile-find-file nil)
  call-interactively(counsel-projectile-find-file)
  (cond ((and projectile-project-root (file-equal-p projectile-project-root default-directory)) (if (doom-project-p default-directory) nil (setq projectile-enable-caching nil)) (call-interactively (if (doom-module-p :completion 'ivy) #'counsel-projectile-find-file #'projectile-find-file))) ((and (and (boundp 'vertico-mode) vertico-mode) (fboundp '+vertico/find-file-in)) (+vertico/find-file-in default-directory)) ((and (and (boundp 'ivy-mode) ivy-mode) (fboundp 'counsel-file-jump)) (call-interactively #'counsel-file-jump)) ((project-current nil dir) (project-find-file-in nil nil dir)) ((and (and (boundp 'helm-mode) helm-mode) (fboundp 'helm-find-files)) (call-interactively #'helm-find-files)) ((call-interactively #'find-file)))
  (let* ((default-directory (file-truename dir)) (projectile-project-root (doom-project-root dir)) (projectile-enable-caching projectile-enable-caching)) (cond ((and projectile-project-root (file-equal-p projectile-project-root default-directory)) (if (doom-project-p default-directory) nil (setq projectile-enable-caching nil)) (call-interactively (if (doom-module-p :completion 'ivy) #'counsel-projectile-find-file #'projectile-find-file))) ((and (and (boundp 'vertico-mode) vertico-mode) (fboundp '+vertico/find-file-in)) (+vertico/find-file-in default-directory)) ((and (and (boundp 'ivy-mode) ivy-mode) (fboundp 'counsel-file-jump)) (call-interactively #'counsel-file-jump)) ((project-current nil dir) (project-find-file-in nil nil dir)) ((and (and (boundp 'helm-mode) helm-mode) (fboundp 'helm-find-files)) (call-interactively #'helm-find-files)) ((call-interactively #'find-file))))
  doom-project-find-file("/home/yuhri/.doom.d/")
  doom/find-file-in-private-config()
  funcall-interactively(doom/find-file-in-private-config)
  command-execute(doom/find-file-in-private-config)
```

**Comment by lumpsoid** [comment] 2023-02-14 23:09
same with emacs 28.2-2
fresh install today

debug info:
```
Debugger entered--Lisp error: (void-variable transient-base-map)
  byte-code("\304\10\305\306\307\310\311\312\313\310\314\315\316\317\320\321\322\317\323\321&\23\210\304\11\305\324\325\10\326\327\330\331\332\333\334\335\336\335\337\340\341\342&\23\210\304\n\305\343..." [transient-base-map transient-map transient-edit-map transient-sticky-map defvar-keymap :doc "Parent of other keymaps used by Transient.\n\nThis i..." "ESC ESC ESC" transient-quit-all "C-g" transient-quit-one "C-q" "C-z" transient-suspend "C-v" transient-scroll-up "C-M-v" transient-scroll-down "<next>" "<prior>" "Top-level keymap used by all transients.\n\nIf you a..." :parent "C-u" universal-argument "C--" negative-argument "C-t" transient-show "?" transient-help "C-h" "C-M-p" transient-history-prev "C-M-n" transient-history-next "Keymap that is active while a transient in is in \"..." "C-x l" transient-set-level "Keymap that is active while an incomplete key sequ..." transient-quit-seq] 20)
  require(transient)
  eval-buffer(#<buffer  *load*> nil "/home/qq/.emacs.d/.local/straight/build-28.2/git-c..." nil t)  ; Reading at buffer position 5337
  load-with-code-conversion("/home/qq/.emacs.d/.local/straight/build-28.2/git-c..." "/home/qq/.emacs.d/.local/straight/build-28.2/git-c..." nil t)
  global-git-commit-mode()
  funcall(global-git-commit-mode)
  (condition-case e (funcall hook) ((debug error) (signal 'doom-hook-error (list hook e))))
  doom-run-hook(global-git-commit-mode)
  run-hook-wrapped(doom-run-hook global-git-commit-mode)
  (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook))
  (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp (car (cdr e))) (symbol-name (car (cdr e))) (car (cdr e))) (car (cdr (cdr e))))) (signal 'doom-hook-error (cons hook (cdr e)))))
  (let ((hook (car --dolist-tail--))) (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp (car ...)) (symbol-name (car ...)) (car (cdr e))) (car (cdr (cdr e))))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp ...) (symbol-name ...) (car ...)) (car (cdr ...)))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- hooks)) (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if ... ... ...) (car ...))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  doom-run-hooks(doom-first-file-hook)
  (progn (setq running\? t) (doom-run-hooks hook-var) (set hook-var nil))
  (if (and after-init-time (not running\?) (or (daemonp) (and (boundp hook) (symbol-value hook)))) (progn (setq running\? t) (doom-run-hooks hook-var) (set hook-var nil)))
  chain-doom-first-file-hook-to-find-file-hook-h(nil t)
  apply(chain-doom-first-file-hook-to-find-file-hook-h (nil t))
  after-find-file(nil t)
  find-file-noselect-1(#<buffer init.el> "~/.doom.d/init.el" nil nil "~/.doom.d/init.el" (15862481 66307))
  find-file-noselect("~/.doom.d/init.el" nil nil t)
  find-file("~/.doom.d/init.el" t)
  funcall-interactively(find-file "~/.doom.d/init.el" t)
  call-interactively(find-file nil nil)
  command-execute(find-file)
```

**Comment by yuhrao** [comment] 2023-02-14 23:11
This one has solved the problem for me. Hope it works for you as well \o

https://emacs.stackexchange.com/questions/75827/doom-emacs-error-running-hook-global-git-commit-mode-because-void-variable

**Comment by tavurth** [comment] 2023-02-16 15:14
Confirmed this can be fixed by:

1. Adding the following lines to `~/.doom.d/packges.el`:
```lisp
(package! transient
      :pin "c2bdf7e12c530eb85476d3aef317eb2941ab9440"
      :recipe (:host github :repo "magit/transient"))

(package! with-editor
          :pin "bbc60f68ac190f02da8a100b6fb67cf1c27c53ab"
          :recipe (:host github :repo "magit/with-editor"))
```

2. Running `~/.emacs.d/bin/doom sync -u`

Worked for me on Emacs 28

**Closed** 2024-04-21 09:46 UTC
Labels: is:upstream
