### ISSUE TITLE
Formatter defined with `set-formatter!` does not gets executed on hook

### ISSUE THREAD

**Issue by vincentbernat** [doomemacs/doomemacs#6936] opened 2022-11-05 16:06 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When using `set-formatter!`, the provided formatter should be executed when saving on the provided mode. For example:

```elisp
(set-formatter! 'nixpkgs-fmt "nixpkgs-fmt" :modes '(nix-mode))
```

### Current behavior

Invoking `format-all-buffer--from-hook` does not invoke the formatter because no executable is associated with it. `editor/format/config.el` contains:

```elisp
;; Don't pop up imposing warnings about missing formatters, but still log it in
;; to *Messages*.
(defadvice! +format--all-buffer-from-hook-a (fn &rest args)
  :around #'format-all-buffer--from-hook
  (letf! (defun format-all-buffer--with (formatter mode-result)
           (when (or (eq formatter 'lsp)
                     (eq formatter 'eglot)
                     (condition-case-unless-debug e
                         (format-all--formatter-executable formatter)
                       (error
                        (message "Warning: cannot reformat buffer because %S isn't installed"
                                 (gethash formatter format-all--executable-table))
                        nil)))
             (funcall format-all-buffer--with formatter mode-result)))
    (apply fn args)))
```

`(format-all--formatter-executable 'nixpkgs-fmt)` returns nil. I don't see anywhere in the code of `set-formatter!` a way to bind an executable (despite the documentation using a `:executable` keyword for one of the examples).

### Steps to reproduce

1. In `config.el`:
```elisp
(after! format-all
(set-formatter! 'nixpkgs-fmt "nixpkgs-fmt" :modes '(nix-mode)))
```
2. Open a nix file
3. Try to format it `M-:` `(format-all-buffer--from-hook)`

### System Information

https://pastebin.com/drwxxyDX

**Comment by vincentbernat** [comment] 2022-11-05 16:13
To confirm the issue, it works when I use:

```elisp
(after! nix-mode
  (set-formatter! 'nixpkgs-fmt "nixpkgs-fmt" :modes '(nix-mode))
  (puthash 'nixpkgs-fmt "nixpkgs-fmt" format-all--executable-table))
```

**Comment by BenediktBroich** [comment] 2022-12-09 21:49
Same error when using `(set-formatter! 'alejandra "alejandra --quiet" :modes '(nix-mode))`.

`SPC m p` in `nix-mode-map` should not invoke `(nix-format-buffer)` when a different formatter is set. Since `nix-format-buffer` from `nix-format.el` can only use `nixfmt`.

**Comment by chairfield** [comment] 2022-12-27 16:31
The current implementation of Doom's `+format--all-buffer-from-hook-a` function is failing to format `ledger-mode` or `bibtex-mode` out of the box, even without a `set-formatter!` call. The root cause appears to be the same; Doom's advice function requires the existence of a formatter executable, even though some formatters don't require one.

Example in upstream [lassik/emacs-format-all-the-code/format-all.el](https://github.com/lassik/emacs-format-all-the-code/blob/47d862d40a088ca089c92cd393c6dca4628f87d3/format-all.el#L541):
```
(define-format-all-formatter ledger-mode
  (:executable)
  (:install)
  (:modes ledger-mode)
  (:format
   (format-all--buffer-native 'ledger-mode 'ledger-mode-clean-buffer)))
```

Rather than further hack around the existing hack (Doom's `editor/format/config.el` has this function under the `;;; Hacks` heading), I'll try disabling `+format--all-buffer-from-hook-a` altogether. I think I'll be okay having `format-all-mode` warn me about missing formatters.

**Comment by peterhoeg** [comment] 2023-05-26 06:36
I think you're dealing with a race issue here. `set-formatter!` does `(after! format-all` which I think is what you need to do with the `puthash` bit:

```elisp
(set-formatter! 'nixpkgs-fmt "nixpkgs-fmt" :modes '(nix-mode))
(after! format-all
  (puthash 'nixpkgs-fmt "nixpkgs-fmt" format-all--executable-table))
```

I simply gave up fighting `format-all` and merged https://github.com/doomemacs/doomemacs/pull/6369 to my doom fork and it works wonderfully.

**Comment by panchoh** [comment] 2024-02-10 11:14
Hi, @asymmetric.

In case this is still causing you trouble, I think I can shed some light on the issue.
It seems that `nix-mode` expects `nixfmt` by default.
You can tweak that by adding to your `config.el`:

``` elisp
(use-package! nix-mode
  :custom (nix-nixfmt-bin "alejandra-the-quiet" ))
```

There are currently three different interfaces for the formatter: `nix-mode`, `apheleia` and `lsp-nix`, it begs for some unification).
In my [config](https://github.com/panchoh/dotconfig-doom/blob/54ad763eebea0acd278335bf5f8f749773784b5a/config.el#L215-L228) you have a workable solution (albeit tweaked for `alejandra`).

Hope that it helps.

**Comment by hlissner** [comment] 2024-07-30 06:38
The `:editor format` module replaced [format-all](https://github.com/lassik/emacs-format-all-the-code) with [Apheleia](https://github.com/radian-software/apheleia/) in 4ecd616cd8f60640d6b0be2ffc3d762e88099bb4, so I will close this issue as it's obsolete (and likely resolved). Thanks for bringing it to my attention, in any case!

**Closed by hlissner** 2024-07-30 06:38 UTC
Labels: is:bug, needs-triage
