### ISSUE TITLE
package! :pin nil not working for unpinning

### ISSUE THREAD

**Issue by xeruf** [doomemacs/doomemacs#6828] opened 2022-09-20 15:45 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

```lisp
 :pin STR|nil
   Pin this package to commit hash STR. Setting this to nil will unpin this
   package if previously pinned.
```

### Current behavior

With the following, it stays pinned:
```elisp
(package! org-journal
  :recipe (:host github :repo "toemacs/org-journal")
  :pin nil
  )
```
but this works
```elisp
(unpin! org-journal)
(package! org-journal
  :recipe (:host github :repo "toemacs/org-journal")
  )
```

### Steps to reproduce

see above

### System Information

pastebin.com/VDRZPhYp

**Comment by hlissner** [comment] 2022-09-20 15:58
Duplicate of https://github.com/doomemacs/doomemacs/issues/3490 (and https://github.com/doomemacs/doomemacs/issues/3490).

**Closed as not planned by hlissner** 2022-09-20 15:58 UTC
Labels: duplicate

**Comment by hlissner** [comment] 2022-09-30 23:54
To clarify: the problem isn't CLI parameters, it's that it's an issue with how package recipes are merged by our package manager _which runs in the context of the CLI_. The CLI rewrite introduces a new package manager, which will indirectly fix this issue.
