### ISSUE TITLE
Doom Emacs client instances cannot be launched with Doom Emacs installed in ~/.config/emacs

### ISSUE THREAD

**Issue by pardub** [doomemacs/doomemacs#7285] opened 2023-07-02 07:07 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When Emacs is run as a server with the command `/usr/bin/emacs --daemon,` the command `emacsclient -c` should start a Doom Emacs client instance and not an Emacs client instance.

### Current behavior

Emacs is run as a daemon with the command `/usr/bin/emacs --daemon` .

If Doom Emacs is installed with `git clone https://github.com/hlissner/doom-emacs ~/.emacs.d` and if we run the command `emacsclient -c`, a Doom Emacs client instance is starting.

If Doom Emacs in installed with `git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs` and if we run the command `emacsclient -c`,a Doom Emacs client instance is not started but an Emacs client instance is starting instead of.

How can we get a Doom Emacs client instance launched with Doom Emacs installed on ~/.config/emacs ?

### Steps to reproduce

1 - Install Doom Emacs with `git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs` 
2 - Run the command `/usr/bin/emacs --daemon`
3 - Run the command `emacsclient -c`
4 - An Emacs client instance is launched instead of a Doom Emacs client instance.

### System Information

https://pastebin.com/jgzi2qBb

**Comment by frisodubach** [comment] 2023-07-07 20:20
I think I have the same issue. I install doom on NixOS and when emacs launches it's either a completely white or black window, and none of the emacs keybindings work. It seemingly doesn't run the doom config when launching emacs.

**Comment by hlissner** [comment] 2023-07-24 14:19
I believe this is a duplicate of https://github.com/doomemacs/doomemacs/issues/7292. See if any of the advice in https://github.com/doomemacs/doomemacs/issues/7292#issuecomment-1647995851 helps.

**Closed by hlissner** 2023-07-24 14:19 UTC
Labels: duplicate
