### ISSUE TITLE
[BUG] Python completion not workling in certain files only

### ISSUE THREAD

**Issue by vikigenius** [doomemacs/doomemacs#2015] opened 2019-11-05 06:50 UTC
**Describe the issue**
Python completion not working in files created using touch command

Today I encountered a really weird bug when I was trying to debug completion not working in certain python files. Seems like completion is not working in files created with touch command

**Steps to reproduce**
1. touch filename.py
2. open emacs
3. open filename.py
4. describe variable company-backends = (company-yapf company-yasnippet)
5. completion no longer working

Other important things to note, completion works absolutely fine when I use emacs to create a new file or even vim to create a new file.
Even more interestingly using touch to create a file when emacs is open does not cause this bug.

However I always manage to reproduce this issue when I follow the steps outlined above, I even reproduced it on my laptop (although both my laptop and desktop are running the same linux distro so could be an OS issue)

This seems like a very weird bug and I am not even sure if using touch has anything to do with it because certain pre generated files from project creation scripts also have this issue.

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--with-x-toolkit=gtk3 --with-xwidgets --prefix=/usr --sysconfdir=/etc --sbindir=/usr/bin --bindir=/usr/bin --mandir=/usr/share/man --infodir=/usr/share/info --localstatedir=/var --with-file-notification=inotify --with-modules --with-jpeg --with-tiff --with-gif --with-png --with-xpm --with-rsvg --without-imagemagick --with-xml2 --with-gnutls --with-sound --with-m17n-flt --host=x86_64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu 'CFLAGS=-fno-PIE -mtune=generic -O2 -pipe   -g' 'CPPFLAGS=   ' 'LDFLAGS=-no-pie -Wl,--as-needed    '")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 8db3b7dca 2019-11-04 17:21:56 -0500"))
 (system
  (type . gnu/linux)
  (config . "x86_64-unknown-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.3.8_2 #1 SMP PREEMPT Fri Nov 1 01:39:56 UTC 2019 x86_64")
  (path "~/.zplug/bin" "~/.miniconda3/condabin" "/usr/local/bin" "/bin" "/usr/bin" "/usr/local/sbin" "/usr/sbin" "/sbin" "~/.symlinks" "/usr/libexec/emacs/26.3/x86_64-unknown-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +present) (python +conda) sh :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment] 2019-11-05 06:54
Possibly a duplicate of #1696.

Does completion work if you kill the buffer and reopen it (within the same Emacs session)?

**Comment by vikigenius** [comment] 2019-11-05 07:03
@hlissner yes, it works if i kill buffer and reopen it, it also works if i disable and re enable auto completion using +company/toggle-auto-completion

**Closed** 2024-09-11 03:44 UTC
Labels: is:bug, module:completion/company, module:lang/python

**Comment by hlissner** [comment] 2024-09-11 03:45
As of https://github.com/doomemacs/doomemacs/commit/88a396148922a2cb5d1e1a731f741e02aada691a, this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
