### ISSUE TITLE
Error running timer with flyspell-lazy-check

### ISSUE THREAD

**Issue by Enrico68** [doomemacs/doomemacs#7493] opened 2023-10-09 06:23 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I open an `org` files got this message 
````
Error running timer ‘flyspell-lazy-check-pending’: (invalid-function org-element-with-disabled-cache)
`````

### Current behavior

xx

### Steps to reproduce

1. Open Emacs
2. open `.org` file
3. start writing 

### System Information

https://pastebin.com/1f7UKQMj

**Comment by tad-lispy** [comment] 2023-11-15 19:57
Same in my system. I suspect it has something to do with Doom upgrading to unstable and as of yet unreleased version 9.7 of Org Mode.

**Comment by samuelaebi** [comment] 2023-11-19 11:55
The same happens with my installation.

**Comment by dreamkidd** [comment] 2024-01-11 12:28
any process on this ?  i got same error message 

#7347 

have a template solution for this issue but not really fix

**Comment by lyndhurst** [comment] 2024-03-29 17:42
Same error for me.

`doom upgrade` also throws an error with a 10k lines backtrace. No idea if it is related:

```
> Upgrading Doom Emacs...
  x There was an unexpected runtime error
    Message: Symbol's function definition is void
    Details: (doom-compile-clean)
```

Doom version:

```
GNU Emacs     v29.2            nil
Doom core     v3.0.0-pre       HEAD -> master 286be1b24 2024-03-24 18:55:43 -0400
Doom modules  v24.03.0-pre     HEAD -> master 286be1b24 2024-03-24 18:55:43 -0400
```

**Comment by hlissner** [comment] 2024-03-29 18:15
Closing because duplicate of #7347.

> doom upgrade also throws an error with a 10k lines backtrace

@lyndhurst Unrelated issue. See 7769.

**Closed by hlissner** 2024-03-29 18:15 UTC
Labels: duplicate
