### ISSUE TITLE
Completion acting strangely under cc-mode

### ISSUE THREAD

**Issue by joshualex** [doomemacs/doomemacs#7047] opened 2023-01-19 10:27 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I turn on lsp for cc mode using the following in `init.el`:
` (cc +lsp)`

I also have company enabled under `:completion`

When running this configuration with clangd installed, opening a `.c` file and hitting something that ends with a colon (e.g. `case 2:`) I expect nothing to happen and no completion dropdown to appear

### Current behavior

writing the above triggers the completion dropdown with irrelevant suggestions (e.g. comment-line).

### Steps to reproduce

1. Open emacs with doom and the above configuration (clangd installed, cc+lsp, company, yasnippet)
2. Open a fresh C file
3. write `2:` in the file

### System Information

https://pastebin.com/9sdNAz0n

**Comment by joshualex** [comment] 2023-01-19 10:27
As far as I can understand this is not a bug in lsp-mode, as it doesn't reproduce in lsp-start-plain

**Comment by hlissner** [comment] 2024-09-11 03:18
I can't reproduce this, so I suspect it might've been addressed upstream at some point, so I'll close this. And with `company-minimum-prefix-length` defaulting to 2 or greater, it shouldn't trigger on a word boundary character like `:`. Thanks for bringing it to my attention, in any case!

**Closed by hlissner** 2024-09-11 03:18 UTC
Labels: invalid
