### ISSUE TITLE
mu 1.10 support

### ISSUE THREAD

**Issue by kepi** [doomemacs/doomemacs#7196] opened 2023-04-13 13:17 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I expect mu 1.10 to behave similar to previous versions.

### Current behavior

mu 1.10 is stable for about two weeks now and after system upgrade, I find myself unable to use it at all.

There are multiple issues, but major ones at least for now:

1. mu4e is displayed in side window on start even when I have `mu4e-split-view` set to `horizontal`
2. vim keybindings are not working, so I'm not able to do much in mu views :) Looks like `(evil +everywhere)` is not working with new version.

I'm evil only user and with lost keybindings (probably because of changed maps?) I struggle even to switch to next e-mail. And I'm not able to read it as it is in super small window and normal key bindings are not working :)

There are big changes related to views in mu 1.10, views had been reworked. [Documentation](https://www.djcbsoftware.nl/code/mu/mu4e/Buffer-display.html), [NEWS](https://github.com/djcb/mu/blob/release/1.10/NEWS.org#mu4e)

I'll would try to adapt it myself, but to be honest, email/mu4e module isn't exactly small and I'm not familiar with it. I suppose there are ppl who has it running now, as git version with these changes had been around for long time.

I'll gladly help with testing. Hacks to get it at least semi-working are welcome too.

### Steps to reproduce

1. Open Emacs
2. `o m`

### System Information

https://pastebin.com/4jpzHRjt

**Comment by shanff** [comment] 2023-04-14 01:28
I've been seeing the same issues for a few days trying to get a wrangle on my own config.  Even  rebuilt things, because I tend to mess things up while playing.  Thanks @kepi  - (popup +all) was indeed my issue.  The keybindings from the OP, however, are an issue with me.  The default Emacs bindings for navigation still work, so at least it's not a _royal_ PITA.

**Comment by edgar-vincent** [comment] 2023-04-14 11:27
Until https://github.com/emacs-evil/evil-collection/pull/720 is merged and `evil-collection`'s commit is bumped in Doom, one can use this fork:
```
(unpin! evil-collection)
(package! evil-collection
  :recipe (:repo "meliache/evil-collection" :branch "mu4e-development"))
```

**Comment by kepi** [comment] 2023-04-14 12:55
@edgar-vincent huge thanks! I can finally read my e-mail without troubles :)

Btw. what is really weird, when adding your snippet to `packages.el`,  `doom sync` didn't pick up the change and I had to manually remove `.local/straight/repos/evil-collection` to get that *evil-collection* fork.

I'm not sure how to proceed with this issue, as it might be good reference for workarounds for others. Evil-collection PR would be hopefully merged some day, but not sure if `popup` `+all` needs some fix or maybe only warning for `mu` users in `doom doctor`?

**Comment by Dadams2** [comment] 2023-04-15 08:18
I have a small workaround for the popup issues. Add the following to the `config:` section of `~/.emacs.d/modules/email/mu4e/config.el`:
```  (set-popup-rule! "^\\*mu4e-\\(main\\|headers\\)\\*" :ignore t)
```

**Comment by edgar-vincent** [comment] 2023-04-16 11:02
The window management has indeed been completely reworked with the help of Mickey Petersen (see https://github.com/djcb/mu/blob/master/NEWS.org#mu4e), hence the popup issues.

`mu4e~view-gather-mime-parts` has been renamed to `mu4e--view-gather-mime-parts`, hence the issues with opening attachments.

**Comment by rbocheux** [comment] 2023-05-09 11:42
Since the last merge of `evil-collection` I have issues with the key bindings. I use the doom `layout +bepo`, but I still have the standard evil key bindings in mu4e (like `ji` instead of `Ti` to go to the inbox,  `jk` instead of `ts` to navigate between mails, and so on).

Interestingly, it worked correctly before the merge, when I used edgar-vincent’s workaround : `(package! evil-collection :recipe (:repo "meliache/evil-collection" :branch "mu4e-development"))`, but this branch no longer exists.

I don’t understand what happened between this branch and the current `evil-collection` master branch, but something is bypassing the remapping for the bepo layout.
Is it a problem for the doom layout module, or should I create an issue in the evil-collection repo? I have a hunch that it is something that evil-collection should fix, because I don’t have any issue with the bepo layout anywhere else.

**Comment by wedens** [comment] 2023-05-18 09:13
Has someone managed to find a workaround? mu4e is pretty much unusable with half-working keybinds :/

**Comment by kepi** [comment] 2023-05-18 12:44
I'm still on `(:repo "meliache/evil-collection" :branch "mu4e-development")` and it's working fine.

As it looks like there is no possibility in `straight.el` to set specific commit, you might try to use  branch which worked before. I forked `evil-collection` and pushed `mu4e-development` branch from my computer now, so you can try it. Let me know if it helped or I should remove it. Changed recipe:

```elisp
(unpin! evil-collection)
(package! evil-collection
  :recipe (:repo "kepi/evil-collection" :branch "mu4e-development"))
```

**Comment by rbocheux** [comment] 2023-05-19 09:45
Great, it’s nice that you have a fork. It works just fine for me as well. Many thanks!

**Comment by kepi** [comment] 2023-05-19 11:52
> I have no trouble at all, and the only thing I have in my config is
> 
> ```
> (unpin! evil-collection)
> ```
> 
> Why does this work?

I'm only guessing, as I don't understand internals of Doom Emacs well - and I might be wrong. But from what I understand every Doom "version" has dependencies pinned to specific commits. And when you only unpin it, it simply get latest version available from git. So your

```elisp
(unpin! evil-collection)
```

Is IMHO same as:

```elisp
(unpin! evil-collection)
(package! evil-collection
  :recipe (:repo "emacs-evil/evil-collection" :branch "master"))
```

If that is true, than current master is indeed fixed and next Doom version can pin to currently working version.

**Comment by edgar-vincent** [comment] 2023-05-19 16:45
Shot in the dark, but have you tried deleting the repo directory before unpinning/changing package versions? I have found that sometimes changing branches for a given package does not update the repo contents accordingly.

19 May 2023 17:41:51 Dominik Schrempf ***@***.***>:

**Comment by dschrempf** [comment] 2023-05-19 18:18
I am on `evil-collection` revision `0df5c4815d7be01ab52e9f957c56e6318c871217`, April 18 which is the latest commit as far as I can see.

**Comment by ret2pop** [comment] 2023-07-10 02:10
I am on mu version 1.10.3, and unpinning the package is not workinng for me. I get this error:
`evil-collection error: (void-function mu4e--main-action-str)` and of course the evil mode keybindings do not work, which I suspect is because of this. Unpinning the package does not install a later version of the package for me.

**Comment by LoganBarnett** [comment] 2023-07-19 04:05
I'd unpinned and then repinned per the suggestions here, but still no joy. I intermixed `doom sync` and Emacs restarts between all of the changes.

Removing my `~/.emacs.d/.local/straight/repos/evil-collection` didn't do the trick for me for me either. But going to that directory and doing a `git pull origin master` (remote and branch had to be explicit) worked. Even when pinned to `master`, it still was floating on some specific branch. Perhaps straight/Doom didn't respect the pinning settings? I would offer that there was something wrong with the local repo, but if it's removed it would seem very remote to be the cause.

**Comment by dschrempf** [comment] 2023-08-05 14:50
Is this still an issue? There have been some commits last week, and they may have fixed this problem.

**Closed** 2023-09-24 16:51 UTC
Labels: module:email/mu4e, is:update
