### ISSUE TITLE
Cider layer missing from clojure-mode after upgrade to most recent version until cider-jack-in has been run

### ISSUE THREAD

**Issue by reify-tanner-stirrat** [doomemacs/doomemacs#7156] opened 2023-03-17 21:29 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I open a clojure file and I'm using vim keybindings, when I type `<space> m`, I should be offered the context menu for CIDER, which allows me to run `cider-jack-in` using `<space> m '`.

### Current behavior

After upgrading to most recent HEAD, I no longer have the CIDER layer (`<space> m` is undefined) until after I've already run `cider-jack-in`.

### Steps to reproduce

Fresh install of emacs, fresh install of most recent doom. Enable `(clojure +lsp)`. Open a clojure file. Press `<space>` to show available layers. See that the one for `m` is undefined.

### System Information

https://gist.github.com/reify-tanner-stirrat/197b419fd03b0f35a918ee623d1b9450

**Comment by ericdallo** [comment] 2023-03-20 12:30
@paulocavaro has the same issue, it seems related to recent clojure-mode changes @elken, WDYT?

**Comment by elken** [comment] 2023-03-20 12:32
This is a duplicate of #7130

**Closed by elken** 2023-03-20 12:32 UTC
Labels: is:bug, needs-triage
