### ISSUE TITLE
"no such formatter defined in 'aphelia-formatters': :none" Error Received When Attempting To Save In Typescript / NextJS Project With Doom Emacs And Prettier On MacOS

### ISSUE THREAD

**Issue by SamuelBanya** [doomemacs/doomemacs#7886] opened 2024-06-12 13:04 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I have the following sections in the 'doom/config.el' config:
```
;; CUSTOM:
;; Adding 'Prettier' support:
(setq-hook! 'js-mode-hook +format-with-lsp nil)
(setq-hook! 'js-mode-hook +format-with :none)
(add-hook 'js-mode-hook 'prettier-js-mode)

(setq-hook! 'typescript-mode-hook +format-with-lsp nil)
(setq-hook! 'typescript-mode-hook +format-with :none)
(add-hook 'typescript-mode-hook 'prettier-js-mode)

(setq-hook! 'rjsx-mode-hook +format-with-lsp nil)
(setq-hook! 'rjsx-mode-hook +format-with :none)
(add-hook 'rjsx-mode-hook 'prettier-js-mode)
```

I also have the following sections in the 'doom/init.el' config:
```
       :editor
       (evil +everywhere); come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       (format +onsave)  ; automated prettiness
```

I have the following in 'doom/packages.el':
```
;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;; (package! some-package)
;; CUSTOM:
;; Installing 'Prettier' support:
(package! prettier-js)
```

The expected behavior would be to format on use 'prettier' to format the current buffer upon saving.

### Current behavior

I receive this error within the Doom modeline when attempting to save a buffer in the Typescript / NextJS project I am working on:
```
no such formatter defined in 'aphelia-formatters': :none
```

### Steps to reproduce

1. Open Doom Emacs
2. Navigate to affected file using .tsx file format
3. Make simple obvious change like deliberately leaving out a semi-colon for the file in a related line
4. Save the buffer with ':w' + enter
5. Receive error message in Doom Modeline

### System Information

https://gist.github.com/SamuelBanya/478c696aa61626054b8e595317e4baec

**Comment by gchape** [comment] 2024-06-29 21:38
Why do not you just enable ```(format +onsave)``` in under :editor in ```init.el```?

Also, is prettier available globally through npm? 

■https://www.npmjs.com/package/prettier

**Comment by hlissner** [comment] 2024-06-29 22:07
You get this error because `:none` is not a valid name of a formatter. There are a number of ways to disable the `:editor format` module (or `apheleia-mode`) for specific modes. Here are some common approaches:

1. Add it to `+format-on-save-disabled-modes`. E.g.

   ```elisp
   (add-to-list '+format-on-save-disabled-modes 'rjxs-mode)
   ```

2. Add a function to `apheleia-inhibit-functions` to return `nil` in contexts where you don't want it to trigger.

   ```elisp
   ;; Disables apheleia in cases where `prettier-js-mode` is enabled.
   (add-hook! 'apheleia-inhibit-functions (bound-and-true-p prettier-js-mode))
   ```

3. Disable `apheleia-mode` in the modes you want it off.

   ```elisp
   (add-hook! '(js2-mode-hook typescript-mode-hook rjsx-mode-hook) (apheleia-mode -1))
   ```

4. Enable `apheleia-inhibit` in the buffers you want it off.

   ```elisp
   (setq-hook! '(js2-mode-hook typescript-mode-hook rjsx-mode-hook) apheleia-inhibit t)
   ```

In any case, this is not a bug, so I will close this. Thanks for bringing it to my attention.

**Closed by hlissner** 2024-06-29 22:07 UTC
Labels: invalid
