### ISSUE TITLE
Doom Emacs still not opening after latest fix.

### ISSUE THREAD

**Issue by Skullamortis** [doomemacs/doomemacs#8142] opened 2024-11-03 17:41 UTC
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Open doom emacs without errors.

### Current behavior

Doom Emacs does not open. This is the output of "emacs --debug-init":

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-directory(nil)
  doom--startup-package-autoloads()
  (let ((startup-or-reload? (or (doom-context-p 'startup) (doom-context-p 'reload)))) (if startup-or-reload? (progn (doom--startup-vars))) (doom--startup-module-autoloads) (doom--startup-package-autoloads) (if startup-or-reload? (progn (doom--startup-modules))))
  (let ((init-file-name (doom-profile-init-file doom-profile))) (setq user-init-file (concat (string-remove-suffix ".elc" user-init-file) ".el")) (setq load-history (delete (assoc init-file-name load-history) load-history)) (let ((startup-or-reload? (or (doom-context-p 'startup) (doom-context-p 'reload)))) (if startup-or-reload? (progn (doom--startup-vars))) (doom--startup-module-autoloads) (doom--startup-package-autoloads) (if startup-or-reload? (progn (doom--startup-modules)))))
  (progn (let ((init-file-name (doom-profile-init-file doom-profile))) (setq user-init-file (concat (string-remove-suffix ".elc" user-init-file) ".el")) (setq load-history (delete (assoc init-file-name load-history) load-history)) (let ((startup-or-reload? (or (doom-context-p 'startup) (doom-context-p 'reload)))) (if startup-or-reload? (progn (doom--startup-vars))) (doom--startup-module-autoloads) (doom--startup-package-autoloads) (if startup-or-reload? (progn (doom--startup-modules))))))
  (if init-file-user (progn (let ((init-file-name (doom-profile-init-file doom-profile))) (setq user-init-file (concat (string-remove-suffix ".elc" user-init-file) ".el")) (setq load-history (delete (assoc init-file-name load-history) load-history)) (let ((startup-or-reload? (or (doom-context-p ...) (doom-context-p ...)))) (if startup-or-reload? (progn (doom--startup-vars))) (doom--startup-module-autoloads) (doom--startup-package-autoloads) (if startup-or-reload? (progn (doom--startup-modules)))))))
  (condition-case error (if init-file-user (progn (let ((init-file-name (doom-profile-init-file doom-profile))) (setq user-init-file (concat (string-remove-suffix ".elc" user-init-file) ".el")) (setq load-history (delete (assoc init-file-name load-history) load-history)) (let ((startup-or-reload? (or ... ...))) (if startup-or-reload? (progn (doom--startup-vars))) (doom--startup-module-autoloads) (doom--startup-package-autoloads) (if startup-or-reload? (progn (doom--startup-modules))))))) ((debug error) (display-warning 'initialization (format-message "An error occurred while booting Doom Emacs:\n\n%s%s%..." (get (car error) 'error-message) (if (cdr error) ": " "") (mapconcat #'(lambda (s) (prin1-to-string s t)) (cdr error) ", ")) :warning) (setq init-file-had-error t)))
  (let ((debug-on-error debug-on-error-initial)) (condition-case error (if init-file-user (progn (let ((init-file-name (doom-profile-init-file doom-profile))) (setq user-init-file (concat (string-remove-suffix ".elc" user-init-file) ".el")) (setq load-history (delete (assoc init-file-name load-history) load-history)) (let ((startup-or-reload? ...)) (if startup-or-reload? (progn ...)) (doom--startup-module-autoloads) (doom--startup-package-autoloads) (if startup-or-reload? (progn ...)))))) ((debug error) (display-warning 'initialization (format-message "An error occurred while booting Doom Emacs:\n\n%s%s%..." (get (car error) 'error-message) (if (cdr error) ": " "") (mapconcat #'(lambda ... ...) (cdr error) ", ")) :warning) (setq init-file-had-error t))) (or (eq debug-on-error debug-on-error-initial) (progn (setq debug-on-error-should-be-set t) (setq debug-on-error-from-init-file debug-on-error))))
  (let ((debug-on-error-from-init-file nil) (debug-on-error-should-be-set nil) (debug-on-error-initial (if (eq init-file-debug t) 'startup init-file-debug)) (inhibit-null-byte-detection t)) (let ((debug-on-error debug-on-error-initial)) (condition-case error (if init-file-user (progn (let ((init-file-name ...)) (setq user-init-file (concat ... ".el")) (setq load-history (delete ... load-history)) (let (...) (if startup-or-reload? ...) (doom--startup-module-autoloads) (doom--startup-package-autoloads) (if startup-or-reload? ...))))) ((debug error) (display-warning 'initialization (format-message "An error occurred while booting Doom Emacs:\n\n%s%s%..." (get (car error) 'error-message) (if (cdr error) ": " "") (mapconcat #'... (cdr error) ", ")) :warning) (setq init-file-had-error t))) (or (eq debug-on-error debug-on-error-initial) (progn (setq debug-on-error-should-be-set t) (setq debug-on-error-from-init-file debug-on-error)))) (if debug-on-error-should-be-set (progn (setq debug-on-error debug-on-error-from-init-file))))
  startup--load-user-init-file@init-doom(#f(compiled-function () #<bytecode -0x1338a73a3094f80c>) #f(compiled-function () #<bytecode 0x4d131ce0e73e6cb>) t)
  apply(startup--load-user-init-file@init-doom (#f(compiled-function () #<bytecode -0x1338a73a3094f80c>) #f(compiled-function () #<bytecode 0x4d131ce0e73e6cb>) t))
  #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100)))(#f(compiled-function () #<bytecode -0x1338a73a3094f80c>) #f(compiled-function () #<bytecode 0x4d131ce0e73e6cb>) t)
  apply(#f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100))) (#f(compiled-function () #<bytecode -0x1338a73a3094f80c>) #f(compiled-function () #<bytecode 0x4d131ce0e73e6cb>) t))
  #f(advice startup--load-user-init-file@load-site-files :before #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100))) ((depth . 100)))(#f(compiled-function () #<bytecode -0x1338a73a3094f80c>) #f(compiled-function () #<bytecode 0x4d131ce0e73e6cb>) t)
  apply(#f(advice startup--load-user-init-file@load-site-files :before #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100))) ((depth . 100))) (#f(compiled-function () #<bytecode -0x1338a73a3094f80c>) #f(compiled-function () #<bytecode 0x4d131ce0e73e6cb>) t))
  (unwind-protect (apply fn args) (progn (set-default 'inhibit-message nil)) (advice-remove #'tool-bar-setup #'ignore) (let ((sym 'tool-bar-mode)) (defalias 'doom-transient-hook5 #'(lambda (&rest _) "Transient hook for tool-bar-mode" (tool-bar-setup) (let ((sym ...)) (cond (... ...) (... ...))) (unintern 'doom-transient-hook5 nil))) (cond ((functionp sym) (advice-add 'tool-bar-mode :before #'doom-transient-hook5)) ((symbolp sym) (put 'doom-transient-hook5 'permanent-local-hook t) (add-hook sym #'doom-transient-hook5 nil)))) (if (default-toplevel-value 'mode-line-format) nil (progn (set-default 'mode-line-format (get 'mode-line-format 'initial-value)))))
  startup--load-user-init-file@undo-hacks(#f(advice startup--load-user-init-file@load-site-files :before #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100))) ((depth . 100))) #f(compiled-function () #<bytecode -0x1338a73a3094f80c>) #f(compiled-function () #<bytecode 0x4d131ce0e73e6cb>) t)
  apply(startup--load-user-init-file@undo-hacks #f(advice startup--load-user-init-file@load-site-files :before #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100))) ((depth . 100))) (#f(compiled-function () #<bytecode -0x1338a73a3094f80c>) #f(compiled-function () #<bytecode 0x4d131ce0e73e6cb>) t))
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x1338a73a3094f80c>) #f(compiled-function () #<bytecode 0x4d131ce0e73e6cb>) t)
  command-line()
  normal-top-level()

### Steps to reproduce

I just upgraded to the latest version. 

### System Information

Emacs lucid nativecomp 29.4

**Comment by jessy836** [comment] 2024-11-03 18:02
Hello @Skullamortis  even if is marked as closed the discussion continue at https://github.com/doomemacs/doomemacs/issues/8140, I think it would be better if the discussion is centralised at a single issue. Otherwise thank for your contribution.

P.S.

I'm just a random user of doomemacs, and here is just a suggestion that I suppose can simplify the work of hlissner but don't know what is the official procedure _

**Comment by Skullamortis** [comment] 2024-11-03 19:06
@jessy836 any updates? Any hints on how to solve it? Im trying to understand it.

**Comment by hlissner** [comment] 2024-11-03 19:10
Duplicate of #8140

**Closed by hlissner** 2024-11-03 19:10 UTC
Labels: duplicate
