### ISSUE TITLE
After `doom up`: `Error: void-function (doom-modules-initialize)`

### ISSUE THREAD

**Issue by RomeoV** [doomemacs/doomemacs#8037] opened 2024-09-01 22:48 UTC
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

After I upated with `doom up`, I get the error below on any invocation of the doom command.
I have managed to fix it by checking out a previous commit of doom, namely d6db88162e5ff515d6daa73d1a8896a26e31fd70.

### Current behavior

```
[romeo@Romeo-P1 ~]$ ./.emacs.d/bin/doom

Error: void-function (doom-modules-initialize)
  mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode 0x1a4b9c2fafae807f>))
  debug-early-backtrace()
  debug-early(error (void-function doom-modules-initialize))
  (doom-modules-initialize)
  (let ((doom-context doom-context)) (let ((tail (ensure-list 'cli))) (while tail (let ((context (car tail))) (doom-context-push context) (setq tail (cdr tail))))) (doom-modules-initialize) (let* ((args (flatten-list args)) (context (make-doom-cli-context :prefix prefix :whole args)) (doom-cli--context context) (write-logs-fn (doom-partial #'doom-cli--output-write-logs-h context)) (show-benchmark-fn (doom-partial #'doom-cli--output-benchmark-h context))) (let* ((doomctxt context) (debugger (doom-rpartial #'doom-cli-debugger doomctxt)) (debug-on-error t)) (let ((streamspec (list (list '>= 'notice (progn (or (progn (and (memq (type-of doomctxt) cl-struct-doom-cli-context-tags) t)) (signal 'wrong-type-argument (list 'doom-cli-context doomctxt))) (aref doomctxt 16))) (cons t (progn (or (progn (and (memq (type-of doomctxt) cl-struct-doom-cli-context-tags) t)) (signal 'wrong-type-argument (list 'doom-cli-context doomctxt))) (aref doomctxt 17)))))) (let ((standard-output (doom-print--redirect-standard-output streamspec t))) (let* ((vnew (doom-print--redirect-message streamspec (if noninteractive 'debug 'notice))) (old (symbol-function #'message))) (unwind-protect (progn (fset #'message vnew) (let ((doom-print-stream standard-output)) (progn (if doom-inhibit-log nil (doom--log "run!: %s %s" prefix (combine-and-quote-strings args))) (add-hook 'kill-emacs-hook show-benchmark-fn 94) (add-hook 'kill-emacs-hook write-logs-fn 95) (if (doom-cli-context-pipe-p context :out t) (progn (setq doom-print-backend nil))) (if (doom-cli-context-pipe-p context :in) (progn (save-current-buffer (set-buffer (progn (or (progn (and (memq (type-of context) cl-struct-doom-cli-context-tags) t)) (signal 'wrong-type-argument (list 'doom-cli-context context))) (aref context 15))) (while (let* ((in (and t (condition-case nil (progn (read-from-minibuffer "")) (error nil))))) (if in (insert in "\n") (condition-case nil (progn (delete-char -1)) (error nil)))))))) (doom-cli--exit (catch 'exit (condition-case e (let* ((args (cons (if (getenv "__DOOMDUMP") :dump prefix) args)) (context (doom-cli-context-restore (getenv "__DOOMCONTEXT") context)) (context (doom-cli-context-parse args context))) (run-hook-with-args 'doom-cli-before-run-functions context) (let ((result (doom-cli-context-execute context))) (run-hook-with-args 'doom-cli-after-run-functions context result)) 0) (doom-cli-wrong-number-of-arguments-error (let* ((val (cdr e))) (progn (ignore (consp val)) (let* ((x26 (car-safe val)) (x27 (cdr-safe val))) (progn (ignore (consp x27)) (let* ((x28 (car-safe x27)) (x29 (cdr-safe x27))) (progn (ignore (consp x29)) (let* ((x30 (car-safe x29)) (x31 (cdr-safe x29))) (progn (ignore (consp x31)) (let* ((x32 (car-safe x31)) (x33 (cdr-safe x31))) (progn (ignore (consp x33)) (let* ((x34 (car-safe x33)) (x35 (cdr-safe x33))) (progn (ignore (null x35)) (let ((command x26) (flag x28) (args x30) (min x32) (max x34)) (progn (doom-print (doom-print--format (doom-print--style 'red "Error: %S expected %s argument%s, but got %d") (or flag (doom-cli-command-string (if (keywordp (car command)) command (cdr command)))) (if (or (= min max) (= max most-positive-fixnum)) min (format "%d-%d" min max)) (if (or (= min 0) (> min 1)) "s" "") (length args))) (doom-cli-call (cons ':help (cons "--synopsis" (cons "--postamble" (cdr (doom-cli--command context))))) context e))))))))))))))) 5) (doom-cli-unrecognized-option-error (doom-print (doom-print--format (doom-print--style 'red "Error: unknown option %s") (car (cdr e)))) (doom-cli-call (cons ':help (cons "--synopsis" (cons "--postamble" (cdr (doom-cli--command context))))) context e) 5) (doom-cli-invalid-option-error (let* ((val (cdr e))) (progn (ignore (consp val)) (let* ((x36 (car-safe val)) (x37 (cdr-safe val))) (progn (ignore (consp x37)) (let* ((x38 (car-safe x37)) (x39 (cdr-safe x37))) (progn (ignore (consp x39)) (let* ((x40 (car-safe x39)) (x41 (cdr-safe x39))) (progn (ignore (consp x41)) (let* ((x42 (car-safe x41)) (x43 (cdr-safe x41))) (progn (ignore (null x43)) (let ((types x36) (option x38) (value x40) (errors x42)) (progn (doom-print (doom-print--format (doom-print--style 'red "Error: %s received invalid value %S") (string-join (progn (or (progn (and (memq (type-of option) cl-struct-doom-cli-option-tags) t)) (signal 'wrong-type-argument (list 'doom-cli-option option))) (aref option 5)) "/") value)) (doom-print (doom-print--format (doom-print--style 'bold "\nValidation errors:"))) (let ((tail errors)) (while tail (let ((err (car tail))) (doom-print (doom-print--format (doom-print--class 'item "%s." (doom-print--class 'fill err)))) (setq tail (cdr tail))))))))))))))))) (doom-cli-call (cons ':help (cons "--postamble" (cdr (doom-cli--command context)))) context e) 5) (doom-cli-command-not-found-error (let* ((command (cdr e)) (cli (doom-cli-get command))) (cond ((null cli) (doom-print (doom-print--format (doom-print--style 'red "Error: unrecognized command '%s'") (doom-cli-command-string (or (cdr command) command)))) (doom-cli-call (cons ':help (cons "--similar" (cons "--postamble" (cdr command)))) context e)) ((null (progn (or (progn (and (memq (type-of cli) cl-struct-doom-cli-tags) t)) (signal 'wrong-type-argument (list 'doom-cli cli))) (aref cli 9))) (doom-print (doom-print--format (doom-print--style 'red "Error: a subcommand is required"))) (doom-cli-call (cons ':help (cons "--subcommands" (cons "--postamble" (cdr command)))) context e)))) 4) (doom-cli-invalid-prefix-error (let ((prefix (car (cdr e)))) (doom-print (doom-print--format (doom-print--style 'red "Error: `run!' called with invalid prefix %S") prefix)) (let* ((suggested (and t (let* ((--cl-var-- t) --cl-var--) (catch '--cl-block---cl-finish---- (maphash #'(lambda (--cl-var-- cli) (or (if (progn (or (progn (and (memq (type-of cli) cl-struct-doom-cli-tags) t)) (signal 'wrong-type-argument (list 'doom-cli cli))) (aref cli 2)) t (progn (setq --cl-var-- (car (progn (or (progn (and (memq (type-of cli) cl-struct-doom-cli-tags) t)) (signal 'wrong-type-argument (list 'doom-cli cli))) (aref cli 1)))) (setq --cl-var-- nil))) (throw '--cl-block---cl-finish---- nil))) doom-cli--table)) --cl-var--)))) (if suggested (doom-print (doom-print--format "Did you mean %S?" suggested)) (doom-print (doom-print--format "There are no commands defined under %S." prefix))))) 4) (user-error (doom-print (doom-print--format (doom-print--style 'red "Error: %s") (car (cdr e)))) (doom-print (doom-print--format "\nAborting...")) 3))) context)))) (fset #'message old))))))))
  run!("doom" nil)
  load-with-code-conversion("/home/romeo/.emacs.d/bin/doom" "/home/romeo/.emacs.d/bin/doom" nil t)
  command-line-1(("--load" "./.emacs.d/bin/doom" "--"))
  command-line()
  normal-top-level()
Symbol’s function definition is void: doom-modules-initialize
```

### Steps to reproduce

```
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
cd ~/.config/emacs
git checkout fb2f79033c0572863a346e2e94bba608929cfba9
~/.config/emacs/bin/doom install  # or any other doom command
```

### System Information

https://pastebin.com/DuS8DPmu

**Comment by hlissner** [comment] 2024-09-01 22:57
Duplicate of https://github.com/doomemacs/doomemacs/issues/8036

**Closed by hlissner** 2024-09-01 22:57 UTC
Labels: duplicate
